### ISSUE TITLE
adapter and agent connectivity issue

### ISSUE THREAD

**Issue by sundaskhansk** [mtconnect/cppagent#100]
![adapter](https://user-images.githubusercontent.com/38851014/40968353-cd4bfb10-68ce-11e8-9789-cdd8a3f80aa7.PNG)
![agent](https://user-images.githubusercontent.com/38851014/40968354-cdb2ac48-68ce-11e8-89c3-ac7b0202a9d6.PNG)
I am having this when i run dump.exe for adapter
and agent.exe for agent
I am having a connectivity issue kindly guide me.
thank you

**Comment by MatthewPowley** [comment]
You can use the '-debug' flag when starting the agent to get more information from this process. As the 'dump.exe' program has been compiled in Release mode (no debugging information) a stack dump is not really of any use. All this says is that the process attempted to use a 'null' pointer. You will have to compile it with debugging information to get more insights.

**Comment by wsobel** [comment]
This is interesting, because the we only release dump.c and the build.bat is pretty generic. If you want to create a MSDev project, you can do that too. The code is very simple. It looks like a bad build. 

How did you build it?

**Comment by sundaskhansk** [comment]
I'm following this video of yours.
https://www.youtube.com/watch?v=pvz2d3WrsS8&feature=youtu.be
