### ISSUE TITLE
beginner issues 

### ISSUE THREAD

**Issue by sundaskhansk** [mtconnect/cppagent#101]
Hi,
I am a beginner, and my programming skills are not strong. **I want to work with MTConnect. I watched many videos and read many articles about MTConnect. Now I want to start mtconnect agent and adapter and my task is to connect agent and adapter, adapter should generate a fake file to agent because right now no machine is connected.**
I have encounter many problems and I have no idea how to solve it. My problems are:

**1. how to start with Mtconnect means from which step agent adapter or with something else.
2. I use the code of agent which is given here. and now I want to know how to start the agent and it will send a ping to adapter.
3. As you told here to change agent.cfg and devices.xml so tell me at which point I have to change.
4. I take the code of adapter from github and that code contains fake adapter now I don't know how to start that code so it can give a response to ping.
5. how to create a network between agent and adapter
6. In different articles I read about simulator but it was not explained completely help me with that.**

**Comment by wsobel** [comment]
Answers below:

>> 1. how to start with Mtconnect means from which step agent adapter or with something else.

You will need to configure the agent and connect it to an adapter to collect data from a machine. The agent can also work with a simulator that can replay a log of data stored in a file. The adapter is a simple socket server that provide a continuous stream of data.

The application only interacts with the Agent (as in the spec), an HTTP server providing a RESTful interface.

> 2. I use the code of agent which is given here. and now I want to know how to start the agent and it will send a ping to adapter.

Do you already have an adapter for a machine?

> 3. As you told here to change agent.cfg and devices.xml so tell me at which point I have to change.

The agent configuration matches the data supplied from the piece of equipment. This is given in part 2 of the MTConnect specification. I would suggest reading the spec.

> 4. I take the code of adapter from github and that code contains fake adapter now I don't know how to start that code so it can give a response to ping.

The adapter will by default start on port 7878–it creates a socket server and waits for the agent to connect. The agent connects to the adapter and begins collecting data. The PING is just a heartbeat.

> 5. how to create a network between agent and adapter

Put both applications on the same network. There is nothing to create. Please read about TCP/IP and sockets.

> 6. In different articles I read about simulator but it was not explained completely help me with that.

The simulator is in the simulator sub-directory. (https://github.com/mtconnect/cppagent/tree/master/simulator) The script is in Ruby (run_scenario.rb) and can be started with the VMC-3Axis-Log.txt file to provide data to the agent using the default cfg file in the bin directory of the pre-built agent.

**Comment by sundaskhansk** [comment]
**I use the code of agent which is given here. and now I want to know how to start the agent and it will send a ping to adapter.**
Do you already have an adapter for a machine?
no right now I don't have any machine I want to use fake file which will show data of machine
