### ISSUE TITLE
couldn't install agent.exe to Windows Services

### ISSUE THREAD

**Issue by MEUGER** [mtconnect/cppagent#105]
Using "cppagent_win32_Vista_1.3.0.17_bin" Version on Windows 10 64bit System.

1. not able to install the agent.exe to the Windows Services.
2. even with command Shell manually not possible.
3. full user rights on the PC 

Any ideas how to solve that Problem??

**Comment by wsobel** [comment]
Did you use an administrator shell?

(Sent from mobile)

**Comment by MEUGER** [comment]
yes, used administrator shell

**Comment by dkiktenko** [comment]
Hi @MEUGER,

Try the following:

1. Open Command Prompt with Administrative rights
2. cd to the directory ../bin/ directory (make sure that cppagent_win32_Vista_1.3.0.17_bin is NOT a zipped file)
3. Run the following command: `agent.exe install agent.cfg`

If the installation succeeds, agent will return the following:
`MTConnect Agent Version 1.3.0.17 - build on Fri Mar 25 10:22:19 2016`

If the installation fails, can you post what the Agent logs to agent.log in the ../bin/ directory?

**Comment by wsobel** [comment]
Is this still an issue? Need to reproduce
