### ISSUE TITLE
Different values of Execution tag in schema for 1.3 spec

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#107]
The schema of MTConnectStreams_1.3.xsd is different from the original one of the Public Release  1.3 spec.
One of the values should be PROGRAM_OPTIONAL_STOP instead of OPTIONAL_STOP for Execution tag.

I also see other changes in the same schema file version between this release and the release in 1.3.0.17.

Client application might have a problem if they receive different values from the different versions of MTConnect Agent 1.3.0.17 and 1.4.0.10.

Thanks

	<xs:complexType name="ExecutionType">
		<xs:annotation>
			<xs:documentation>
        Program execution events
      </xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:restriction base="EventType">
				<xs:enumeration value="READY"/>
				<xs:enumeration value="INTERRUPTED"/>
				<xs:enumeration value="ACTIVE"/>
				<xs:enumeration value="STOPPED"/>
				<xs:enumeration value="FEED_HOLD"/>
				<xs:enumeration value="PROGRAM_COMPLETED"/>
				<xs:enumeration value="PROGRAM_STOPPED"/>
				<xs:enumeration value="OPTIONAL_STOP"/>
				<xs:enumeration value="UNAVAILABLE"/>
			</xs:restriction>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="Execution" type="ExecutionType" substitutionGroup="Event">
		<xs:annotation>
			<xs:documentation>
        Program execution events
      </xs:documentation>
		</xs:annotation>
	</xs:element>

**Comment by wsobel** [comment]
I’ll check it out. Thanks. 

(Sent from mobile)

**Comment by hulinning2** [comment]
Will, 
Have you got a chance to review this yet?
Thanks

**Comment by wsobel** [comment]
Merged in the changes and fixed schema_dev. Merged files to schema and made the schema directory a submodule for the schema repo to make things easier to manage.

Still need to build and release. Files should be correct now. Please validate in master branch.

**Comment by hulinning2** [comment]
Will, 
Still, there are some differences between 1..3.0.17 and the latest release

Only include these new lines in the new MTConnectStreams_1.3_1.0.xsd  and other files:
Line 129: <xs:restriction base='xs:NMTOKEN'/>
Line 341: <xs:enumeration value='CLOCK_TIME'/>
Line 417: <xs:enumeration value='ROTARY'/>
Line 418: <xs:enumeration value='LINEAR'/>

Can you check again?

Thanks

**Comment by wsobel** [comment]
Can you attach the file you are checking against?

Thx
W

(Sent from mobile)

**Comment by hulinning2** [comment]
Will, 
I compared the schema files I download from version 1.3.0.17 on this site.

[MTConnectStreams_1.3_1.0.xsd.zip](https://github.com/mtconnect/cppagent/files/2535610/MTConnectStreams_1.3_1.0.xsd.zip)

New schema file from 1.4 from https://github.com/mtconnect/schema/blob/b11a40f84f4f2d5d19e2f7d8e82ba78301883228/MTConnectStreams_1.3_1.0.xsd

[MTConnectStreams_1.3_1.0_New.xsd.zip](https://github.com/mtconnect/cppagent/files/2535619/MTConnectStreams_1.3_1.0_New.xsd.zip)

Thanks

**Comment by hulinning2** [comment]
Will,
I will check it again when you fix the ClockTime  data item.

Thanks

**Comment by wsobel** [comment]
I have pushed the changes to the schema repo on GitHub. If you want to do a quick check, i can then resist 1.3 if it works for you. 

Thanks
W

(Sent from mobile)

**Comment by hulinning2** [comment]
Will, 
Where can I get the latest copy of schema on GitHub?

**Comment by wsobel** [comment]
https://github.com/mtconnect/schema

(Sent from mobile)

**Comment by wsobel** [comment]
I am now using the schema as a submodule, so we should not have any deviation in the future.
