### ISSUE TITLE
Not getting correct XML data

### ISSUE THREAD

**Issue by memayank2007** [mtconnect/cppagent#109]
I am connecting Fanuc 0id and with MT connect adapter(https://github.com/mtconnect/adapter) and able to access the data on localhost:7878.

![adapter_result](https://user-images.githubusercontent.com/5354069/47901369-cb810300-dea5-11e8-8299-d0e4271f708f.jpg)

![adapter_result2](https://user-images.githubusercontent.com/5354069/47901385-d5a30180-dea5-11e8-8eb6-b4aac1dc85a1.jpg)

but not able to get the correct data stream on the agent at localhost:5000 . I am using windows and getting this xml on localhost:5000 without data. 

![xml_error1](https://user-images.githubusercontent.com/5354069/47901481-1733ac80-dea6-11e8-8cf9-44da38486bd0.jpg)
![xml_error3](https://user-images.githubusercontent.com/5354069/47901482-1733ac80-dea6-11e8-8161-82cc0c90aeef.jpg)

I want to get the data stream in this format https://github.com/mtconnect/adapter/blob/master/fanuc/fanuc.xml

How can I get this XML  and what I am missing?

**Comment by wsobel** [comment]
My guess is you have not connected the agent to the adapter. I will need to see your Device.xml file and your agent.cfg. The agent.cfg needs to associate the device with the adapter. 

Best
W

(Sent from mobile)

**Comment by memayank2007** [comment]
@wsobel , I guess you want to see the agent.cfg which is being created after installing the setup inside c drive. my agent.cfg looks like -

![agent_confg](https://user-images.githubusercontent.com/5354069/47947943-c2973c80-df4c-11e8-9214-f2a78e64a630.jpg)

Device.xml looks like as below -

![xml_created](https://user-images.githubusercontent.com/5354069/47947956-ece8fa00-df4c-11e8-858e-04e2ab1deb8e.jpg)

![xml_created_2](https://user-images.githubusercontent.com/5354069/47948252-6e438b00-df53-11e8-8f83-fcacd39eb3b7.jpg)

![xml_created3](https://user-images.githubusercontent.com/5354069/47947994-b5c71880-df4d-11e8-8a19-8faac262e855.jpg)

**Comment by hulinning2** [comment]
One possible reason is that the agent is registered and running on the different location on this PC.
You can check Windows Services to see where it is running from.

Although agent.cfg seems to be right it might not be the one running.

It has different uuid from devices.xml and stream output
