### ISSUE TITLE
MTConnect dataitem can not show

### ISSUE THREAD

**Issue by guoxiangguoxiang** [mtconnect/cppagent#113]
Hello，i have a problem.When I delete the dataitem "f_command",i can use http to access.
but will have a new problem , you can see in the following:
![image](https://user-images.githubusercontent.com/40424974/58161295-95c13180-7cb2-11e9-8990-622239ad04ca.png)
and my dataitem which i **delete**  is:`<DataItem` category="SAMPLE" id="p1_feedcommand" name="f_command" nativeUnits="MILLIMETER/SECOND" Type="PATH_FEEDRATE" subType="COMMANDED" units="MILLIMETER/SECOND"/>`
and what's more,when i re-add this dataitem in device.xml， i could not use http to sccess ip.
Does anyone give me some advice?
Thank you inadvance.

**Comment by guoxiangguoxiang** [comment]
And,I have another new problem,that agent always say it could not find dataitem "slload,slservo,slspeed",like the following shows:
![12](https://user-images.githubusercontent.com/40424974/58161464-e20c7180-7cb2-11e9-8451-6617fbf36567.png)
but i find adapter already sent these data to agent.
do you know why this problem happen?
thank u inadvance.

**Comment by wsobel** [comment]
was this issue resolved?
