### ISSUE TITLE
Device file per adapter?

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#114]
Is there a way to specify the device xml file per adapter in the configuration file of agent version 1.4?
I checked the README but there is no example of how that can be possible or not.

    Devices = VMC-3Axis.xml

    Adapters
    {
        Adapter_1
        {
            Device = VMC-3Axis
            Host = 192.168.10.22
            Port = 7878 # *Default* value...
        }
    
        # Energy sensor
        Adapter_2
        {
            Device = VMC-3Axis
            Host = 192.168.10.2
            Port = 7878 # *Default* value...
        }
    }
Thanks

**Comment by MatthewPowley** [comment]
You can only have one file referenced.
In your case you would need to amalgamate the two adapter 'device.xml' files into one and use this for the agent.

**Comment by hulinning2** [comment]
Will it be in 1.5?
It is really convenient to support different adapters' device xml file from different vendors and would not require vendors to modify OEM devices.xml.

**Comment by MatthewPowley** [comment]
It won't be in version 1.5. Although the release schedule of the agent can be different to that of the standard, so it could be added as a feature.
In future versions if 'plug n play' functionality is added then this would be part of that (with the caveat that the adapters would need to support the request of the agent for their device configuration).
I will add this feature request to the development version of the agent.

**Comment by wsobel** [comment]
Linh,

Please add an issue to the cppagent_dev project for the ongoing 1.5 development. We will be reviewing the issues and prioritizing the work to be done. 

If you don’t have access, I can add you to the group. 

Best
W

(Sent from mobile)

**Comment by hulinning2** [comment]
Will,
I do not think that I am in the cppagent_dev  group.

Thanks

**Comment by wsobel** [comment]
You are now added to the membership of the Agent team.

- W

**Comment by wsobel** [comment]
The issue was migrated to the dev project.
