### ISSUE TITLE
Is there some demo to run MTConnect simulator?

### ISSUE THREAD

**Issue by RaymondCui21** [mtconnect/cppagent#115]
Hi members,

It seems that the document of running a MTConnect simulator is missing in the Github. As a beginner for MTConnect, it is very useful to setup a demo to get some hands-on experience about MTConnect. The first demo maybe how to setup the communication between the adapter/simulator and MTC agent since it is neither hardware-based (requires CNC machine) nor application-based (develop MTConnect client). 

I learned MTConnect documents about its theory, structures and terms, and the examples on Githubs about the configurations of two files: Devices.xml, agent.cfg
I found that there is no document about implementing MTConnect simulator. There is an example about running 8 simulators online (http://photonsandelectrons.blogspot.com/2017/08/pranab-chakrabortys-blog-post-3-common.html). However, it explains that how to configure the above two files clearly for the example but not explicitly show how to run the simulator it self. 

Then I looked for some answers from the previous issues and tried to summarize them. There is much knowledge, but some information is limited and incomplete, e.g: the questioners did not provide their environments, OS and software versions etc. Also, there maybe some issue about firewall such as telnet on windows. That is not mentioned in the examples.

Is it possible to provide a wiki page to explicitly explain MTConnect implementations with some simple demos such as 1 prerequisite for OS, dependency and steps to setup agent, configure firewall, run simulator, collect data;  2 For a specific CNC machine, setup or develop an adapter, 3 develop MTConnect client etc.? 
This effort would make MTConnect as a out-of-box tool. It would be very helpful to beginners and also save much time for members to answer similar questions. Thank you very much.

Kind regards,
Raymond

**Comment by wsobel** [comment]
Hi Raymond,

Thanks for the comments. 

There is more info on the http://mtcup.org, please check there and see if there are any docs that addresses these areas. 

We appreciate you helping to provide the specific areas where we need to improve. If it’s possible to create issues for each area, we can try to address them as soon as we have spare cycles. 

 Since this is a volunteer effort, we accept all contributions and appreciate any help we can get. 

Thanks
Will


(Sent from mobile)

**Comment by RaymondCui21** [comment]
Hi Will,

Thank you for the info and the volunteer effort with your private time. I found one topic "[Installing C++ Agent on Ubuntu](http://mtcup.org/wiki/Installing_C%2B%2B_Agent_on_Ubuntu)" at http://mtcup.org. It uses ubuntu 14.04 LTS as the OS to build the agent. So I loaded ubuntu 14.04 LTS image in my VirtualBox and followed all the steps. But app can not be built and shown with two errors when running the Make utility as shown below:

![image](https://user-images.githubusercontent.com/31235714/59234565-b5ec6c80-8c30-11e9-9b5e-e6bf5c4c3bcb.png)
![image](https://user-images.githubusercontent.com/31235714/59234690-4fb41980-8c31-11e9-92c3-bdf340a44deb.png)

The same errors occurred when I use the Docker image of Ubuntu 14.04. If the docker image could build the app successfully, I would share the docker image to the community then new learners do not need to worry about the OS and dependency issues any more. 

I tried to use ubuntu 16.04 and build successfully. However, it can not run Upstart scripts since ubuntu 16.04 replace upstart with systemd. 

Do you have some update info about it? Thank you.

Raymond

**Comment by russwaddell** [comment]
I was only ever able to get the agent running with upstart. With systemd you may be able to remove it and replace with upstart (but risk system instability elsewhere) or tweak the agent/adapter simulator to run with systemd. The agent should be able to run with either upstart or systemd but it might require additional configuration.

**Comment by wsobel** [comment]
I would suggest using Ubuntu 18 LTS and try again. I need to update the page, but was waiting for 1.5 because a lot of the instructions will need to change. I also have appveyor set up for the development version. 

Best
W

(Sent from mobile)

**Comment by RaymondCui21** [comment]
@wsobel Hi Will,
I tried Ubuntu 18.04 and fixed some issues such as: Schemas since there is only a 'Schema' folder in the directory of the "~/agent/cppagent". Also have to modify the configuration file of Agent. 
The agent works finally.
However, it can not pass "Setup the Upstart scripts" part. The error is that "/etc/init/mtc_agent.conf" does not exist. 
I found that Ubuntu 18.04 does not have "/etc/init" and Ubuntu 16.04 still has the init for Upstart. 
Maybe it is the only way to wait for the new version and the new instruction at the current stage.
Regards,
Raymond

**Comment by RaymondCui21** [comment]
Hi, @russwaddell 
Yes, you are right. Replace systemd with Upstart results in the Desktop environment of Ubuntu 16.04 crash. 
Also, it seems that there is no instruction to setup MTC agent and simulator on Windows. 
Regards,
Raymond

**Comment by RaymondCui21** [comment]
@wsobel  I found one error about the name folder of Schemas is schema from the github (git clone https://github.com/mtconnect/cppagent.git). 
I am using Ubuntu 18.04 and followed the instruction of "Installing C++ Agent on Ubuntu"
The following command shows copy Schemas folder which can not be found.
            sudo cp -r styles schemas simulator/VMC-3Axis.xml /etc/mtconnect/agent

Also, there is no schema file in the schema folder. 

![image](https://user-images.githubusercontent.com/31235714/59479216-80998600-8e9f-11e9-9f46-2aa099350097.png)

**Comment by wsobel** [comment]
It is a submodule. 

You need to do the following:

git submodule unit
git submodule update

After cloning. 

(Sent from mobile)

**Comment by RaymondCui21** [comment]
@wsobel Thank you very much. It works after updating the submodule, the schema files are added into the schema folder. Then rename the schema folder with schemas ( coding:  "mv schema schemas" ). Then, the error message (can not find schemas folder) would not show after typing codes ( sudo cp -r styles schemas simulator/VMC-3Axis.xml /etc/mtconnect/agent).  

The connection is successful between the simulator and the agent, as shown below screenshots:

Only issue left is that the value is not update if the simulator runs in RUN mode (codes: agent run /etc/mtconnect/agent/agent.cfg ). If the simulator runs in Debug model (codes: agent debug /etc/mtconnect/agent/agent.cfg), the simulator would send out new messages after manually refresh the webpage (URL: localhost:5000/current) 
(Testing environment: Ubuntu 18.04, Ruby 2.5.1 p57 x86_64)

**Comment by wsobel** [comment]
When running in run mode it logs to a rolling log file. Check the directory for a log file. 

You can either tail the log file or configure for logging. Instructions are in the readme 



(Sent from mobile)

**Comment by RaymondCui21** [comment]
@wsobel  Thank you very much! Appreciate! It works well now.
