### ISSUE TITLE
Can not setup connection between Simulator and Agent 

### ISSUE THREAD

**Issue by RaymondCui21** [mtconnect/cppagent#116]
I am using the file "[cppagent_win32_Vista_1.4.0.10_bin](https://github.com/mtconnect/cppagent/releases)" on Window 10. 
I used Powershell Administrator right and run simulator on one terminal:
ruby simulator.rb -p 7878 .\VMC-3Axis-Log.txt 
or
ruby simulator.rb -p 7878 .\VMC-3Axis.XML

Run agent debug mode on anther terminal:
 .\agent.exe debug .\agent.cfg

Problem is that simulator keeps waiting for connection and agent failed to connect. 

Using telnet to test 7878 port and display:

Connecting To 127.0.0.1...Could not open connection to the host, on port 7878: Connect failed 

![image](https://user-images.githubusercontent.com/31235714/59406291-f561b700-8df0-11e9-8617-ebf655b99af1.png)

Besides, I also turned off Firewalls:
![image](https://user-images.githubusercontent.com/31235714/59406315-0b6f7780-8df1-11e9-8925-d9ebbda12ecd.png)

Agent.cfg file is attached. 
[agent.zip](https://github.com/mtconnect/cppagent/files/3284349/agent.zip)

Anyone can help! Thank you.
Kind regards,
Raymond

**Comment by wsobel** [comment]
Check to see in netstat it port 7878 on 127.0.0.1 is bound? Make sure it isn’t the ipv6 port. I thought we were binding to 0.0.0.0 which is ipv4 any, but don’t remember. 

(Sent from mobile)

**Comment by RaymondCui21** [comment]
@wsobel Thank you very much, Will. 
 I ran the simulator and test with the command: 
netstat -na | findStr "7878". Nothing happened. 
Then I ran the agent and using netstat to see 5000, and shown:

TCP 0.0.0.0:5000          0.0.0.0:0           Listening
UDP 0.0.0.0:5000          *.*
 
It seems that simulator does not setup port successfully, is it right?

**Comment by wsobel** [comment]
You’re using the wrong script. The one you should be using is run_scenario.rb. 

You also should not feed in the xml configuration device file, that is for the agent. 

Run as follows:

ruby run_scenario.rb VMC-3Axis-Log.txt

It by default binds to port 7878

simulator.rb is provides a single line entry for adapter simulation. 

That script is run ruby simulator.rb 7878





(Sent from mobile)

**Comment by RaymondCui21** [comment]
I tried this simulator but shown some errors.
![image](https://user-images.githubusercontent.com/31235714/59408978-89834c80-8df8-11e9-8295-7578f7d2fed1.png)

**Comment by wsobel** [comment]
Change in the option parser library in later versions of ruby. Change to Sting from OptionParser::String

(Sent from mobile)

**Comment by RaymondCui21** [comment]
@wsobel Installed the latest version of Ruby 2.6.3 i386 for Windows and modified the code to Sting from OptionParser::String in run_scenario.rb 
The same error occurred: 
![image](https://user-images.githubusercontent.com/31235714/59477840-56919500-8e9a-11e9-8773-6aab74afa141.png)
Could you please give some instruction to change  "option parser library" in Ruby?
I listed the paths of Ruby for your reference. Thank you very much.

**Comment by wsobel** [comment]
I’m traveling now and have not had a chance to check. Should get to it in a day. 

(Sent from mobile)

**Comment by wsobel** [comment]
Rmoved OptionParser:: before String and tested with ruby 2.5

**Comment by RaymondCui21** [comment]
@wsobel Thank you very much for the prompt reply.  
Yes, the error is removed after removed "OptionParser:: ". The agent is not able to connect the simulator as shown below:
![image](https://user-images.githubusercontent.com/31235714/59538826-695da580-8f3e-11e9-91ed-0a52ee5d0a7a.png)
The simulator showed the message: <TCPServer:0x0512a390> which seems that the TCP Server address is incorrect, like a pointer address.  
(Testing environment: ruby 2.6.3p62 (2019-04-16 revision 67580) [i386-mingw32], Win10  )

**Comment by wsobel** [comment]
That is just the way ruby logs the server. I don’t know why you are disconnecting immediately. That seems odd. 

You can try telneting to the run_simulator.rb adapter on 127.0.0.1 7878 and see if it disconnects. 

(Sent from mobile)

**Comment by RaymondCui21** [comment]
It showed TIME_WAIT and connect failed. 

![image](https://user-images.githubusercontent.com/31235714/59543435-9914a980-8f4e-11e9-9c24-4f3f087d1d8b.png)

**Comment by wsobel** [comment]
What’s in your log file? Is it empty?

(Sent from mobile)

**Comment by RaymondCui21** [comment]
Sorry, just came back from a trip. 
Yes, the log file is empty. 
Just found one thing that the simulator stays at the state of "Waiting on #<TCPServer:0x0509ad68> 7878", once executes agent program, the state of the simulator changes to "Received * PING, responding with pong" and quit the program.

**Comment by wsobel** [comment]
The vmc... log file needs data. 

(Sent from mobile)

**Comment by RaymondCui21** [comment]
@wsobel Sorry, I did not notice the log file was empty, but it was filled with data before. 
It works well on Win7, Win10 and Ubuntu 18.04 now. Thank you very much, William. 
I left all my steps to run the simulators on Ubuntu 18.04 below for the following learners: 

•	Create testing Ubuntu 18.04 OS (Install [VirtualBox](url:https://www.virtualbox.org/wiki/Downloads) and download Ubuntu 18.04 [image)](url:https://ubuntu.com/download/desktop/thank-you?country=AU&version=18.04.2&architecture=amd64)
•	Following steps: (refer to: [Installing C++ Agent on Ubuntu](ur:http://mtcup.org/wiki/Installing_C%2B%2B_Agent_on_Ubuntul))
o	sudo apt-get update
o	sudo apt-get install libxml2 libxml2-dev cmake git libcppunit-dev build-essential screen ruby curl
o	mkdir -p ~/agent/build
o	 cd ~/agent
o	git clone https://github.com/mtconnect/cppagent.git
o	cd cppagent
o	git submodule init
o	git submodule update
o	mv -f schema schemas
o	cd ..
o	cd build
o	cmake -D CMAKE_BUILD_TYPE=Release ../cppagent/
o	make
o	 sudo cp agent/agent /usr/local/bin
o	sudo mkdir -p /etc/mtconnect/agent /etc/mtconnect/adapter
o	 cd ~/agent/cppagent
o	sudo cp -r styles schemas simulator/VMC-3Axis.xml /etc/mtconnect/agent
o	sudo cp simulator/VMC-3Axis-Log.txt simulator/run_scenario.rb /etc/mtconnect/adapter
o	Configure the Agent with copy the script codes
o	agent debug /etc/mtconnect/agent/agent.cfg
o	Can not run Upstart scripts since Upstart is not available after Ubuntu 14.04 (eg: Ubuntu 16.04 and Ubuntu 18.04)
o	Start agent with the command: /usr/local/bin/agent run /etc/mtconnect/agent/agent.cfg
o	Start simulator with the command: ruby /etc/mtconnect/adapter/run_scenario.rb -l /etc/mtconnect/adapter/VMC-3Axis-Log.txt

**Comment by RaymondCui21** [comment]
Windows 7/10:

1.	Download agent file cppagent_win32_Vista_1.4.0.10_bin.zip from https://github.com/mtconnect/cppagent/releases 
2.	Unzip it and remember the directory X, eg: create a folder etc and move it into the folder etc C:\etc\cppagent_win32_Vista_1.3.0.17_bin\
3.	Open Command Prompt with Administrative rights
4.	Change to the directory X with the command: cd  X/bin/
5.	Run the following command: agent.exe install agent.cfg

•	Config agent.cfg file under the bin folder:  \bin\ 
Devices = C:\etc\cppagent_win32_Vista_1.3.0.17_bin\simulator\VMC-3Axis.xml
•	Run Agent with Run or Debug mode 
Run mode with the following command: agent.exe run agent.cfg
Debug mode with the following command: agent.exe debug agent.cfg
•	Run Simulator with log file
   Install Ruby installer on Windows https://rubyinstaller.org/
1.	Modify the simulator ruby file under the directory ../simulator/run_scenario.rb . Change OptionParser:: String to String 
2.	Open (Command Prompt/PowerShell) with Administrative rights
3.	cd to the directory ../simulator/
4.	Run the simulator with the following command: ruby run_scenario.rb VMC-3Axis-Log.txt (make sure VMC-3Axis-Log.txt is not empty, otherwise the simulator stops after agent runs)

**Comment by wsobel** [comment]
When you install the agent it will automatically run as a windows service when the machine starts or if you open Services and the start the service manually. 

(Sent from mobile)

**Comment by RaymondCui21** [comment]
@wsobel Do you mean install the agent is that execute the command to install the agent at the powershell ( agent.exe install agent.cfg ) ? 
I run the simulator before start the agent, the localhost:5000/current is empty and the simulator keeps waiting for connection, do I need to config the agent as an automatic windows service ?

Also, while keeping the simulator and Agent running, the trace data is automatically stored in every 10 MB log file in Ubuntu, but stored all data in one large file in Windows after stop the agent, is it intended in Windows? Is it better to split data into small files?

**Comment by michaell-nz** [comment]
@RaymondCui21 I followed your steps listed above, but still could not get it working on windows. always waiting for Pong. Here is my files: 
[agent.zip](https://github.com/mtconnect/cppagent/files/3316697/agent.zip)

Would you please see whether there are any issues?

Much appreciated. My skype is: yuqian.m.lu, if it is easier to exchange ideas via skype.

Yuqian

**Comment by RaymondCui21** [comment]
@michaell-nz Hi Yuqian, Have you tried Powershell? I am using it but not command prompt.
