### ISSUE TITLE
cannot set up communication between simulator and agent

### ISSUE THREAD

**Issue by michaell-nz** [mtconnect/cppagent#117]
I tried to get the simulator and agent working on windows 10, same PC. However, cannot get it working.

Below are the steps:
1. Download https://github.com/mtconnect/cppagent/releases/tag/v1.4.0.10 vista version
2. Unzip it and remember the directory X, eg: create a folder etc and move it into the folder etc C:\etc\cppagent_win32_Vista_1.3.0.17_bin\
3. Change the host in agent.cfg to '127.0.0.1'
4. Modify the simulator ruby file under the directory ../simulator/run_scenario.rb . Change OptionParser:: String to String
5. Open Command Prompt with Administrative rights
6. Change to the directory X with the command: cd X/bin/
7. Run the following command: agent.exe install agent.cfg
8. Run Agent with Run or Debug mode. Run mode with the following command: agent.exe run agent.cfg. Debug mode with the following command: agent.exe debug agent.cfg
9. Install Ruby installer on Windows https://rubyinstaller.org/
10. Open (Command Prompt/PowerShell) with Administrative rights
11. cd to the directory ../simulator/
12. Run the simulator with the following command: ruby run_scenario.rb VMC-3Axis-Log.txt

However, I got the following:

![image](https://user-images.githubusercontent.com/4574749/59970972-49c21f00-95c7-11e9-982d-d81b7e7c6407.png)

and empty page at localhost:5000/current
![image](https://user-images.githubusercontent.com/4574749/59970979-6fe7bf00-95c7-11e9-9ca4-b656138264db.png)

Can anyone verify and share?

**Comment by RaymondCui21** [comment]
@michaell-nz Hi Yuqian, Have you tried Powershell? I am using it but not command prompt.

**Comment by michaell-nz** [comment]
@RaymondCui21, thank you for your suggestion. Tried powershell and changed favicon path and location as suggested. Still the same error.

Below is the agent.log file:

```
2019-06-23T06:35:32.0662Z: ERROR [5] dlib.server_http: Error processing request from: 127.0.0.1 - HTTP field from client terminated incorrectly

2019-06-23T06:35:34.0224Z: DEBUG [6] agent: Request: GET /current from 127.0.0.1:60936

2019-06-23T06:35:44.0528Z: ERROR [7] dlib.server_http: Error processing request from: 127.0.0.1 - HTTP field from client terminated incorrectly

2019-06-23T06:35:45.0557Z: ERROR [8] dlib.server_http: Error processing request from: 127.0.0.1 - HTTP field from client terminated incorrectly
```
My agent file is below:
[agent.zip](https://github.com/mtconnect/cppagent/files/3317538/agent.zip)

Is there any special settings or system configuration? I am running on Windows 10 PC.

**Comment by wsobel** [comment]
What user agent (browser) are you using to make the http request? This is an error from the http server that the request header is malformed and not terminated. 

(Sent from mobile)

**Comment by michaell-nz** [comment]
> What user agent (browser) are you using to make the http request? This is an error from the http server that the request header is malformed and not terminated. (Sent from mobile)
> […](#)
> On Jun 23, 2019, at 08:40, michaell-nz ***@***.***> wrote: @RaymondCui21, thank you for your suggestion. Tried powershell and changed favicon path and location as suggested. Still the same error. Below is the agent.log file: 2019-06-23T06:35:32.0662Z: ERROR [5] dlib.server_http: Error processing request from: 127.0.0.1 - HTTP field from client terminated incorrectly 2019-06-23T06:35:34.0224Z: DEBUG [6] agent: Request: GET /current from 127.0.0.1:60936 2019-06-23T06:35:44.0528Z: ERROR [7] dlib.server_http: Error processing request from: 127.0.0.1 - HTTP field from client terminated incorrectly 2019-06-23T06:35:45.0557Z: ERROR [8] dlib.server_http: Error processing request from: 127.0.0.1 - HTTP field from client terminated incorrectly My agent file is below: agent.zip Is there any special settings or system configuration? I am running on Windows 10 PC. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I used Chrome. Any specific requirement?

**Comment by michaell-nz** [comment]
@wsobel , used IE just now, still the same issue. Below are all the agent files that I am using.
[agent.zip](https://github.com/mtconnect/cppagent/files/3317568/agent.zip)

**Comment by RaymondCui21** [comment]
@michaell-nz How about update the directory in your agent.cfg such as: 
Devices = ../simulator/VMC-3Axis.xml
to 
Devices = 'the complete directory of your VMC-3Axis.xml'

**Comment by wsobel** [comment]
Do you load anything in the browser? Do you get an error in the browser?

(Sent from mobile)

**Comment by wsobel** [comment]
Try using the command line curl utility. You can download it. It will make a minimal http request. 

The code is in dlib and it logs this message if  a field has started in the header and does not have a NL character before the input stream closes. This could be the browser terminating the connection. 

It is strange a standard browser would do this. Otherwise it could be another service trying to connect to port 5000 and causing the problem which is unrelated to the browser issue. 

(Sent from mobile)

**Comment by wsobel** [comment]
Reviewing a bit more. The request succeeded since the browser was making subsequent requests for the stylesheets. These are requested by the browser after it receives the page. So the request is going through. Not sure why you would see GET / when you made a request for /current. That is odd. 


(Sent from mobile)

**Comment by michaell-nz** [comment]
@wsobel, localhost:5000/probe or localhost:5000 loads correct xml file. Just that localhost:5000/current will display empty page. I have also tested the same on a brand new Windows 10 laptop, which returned the same problem.

**Comment by wsobel** [comment]
Check view source. May not be resolving style sheet. Remove style sheet reference from cfg file. 

(Sent from mobile)

**Comment by RaymondCui21** [comment]
@wsobel highly possible. I also occurred some problems of style sheet before, and it works well now after changed favicon secion.

**Comment by michaell-nz** [comment]
Hi @wsobel, tried as per your suggestion, still no luck. Any other possibilities from your test?
> Check view source. May not be resolving style sheet. Remove style sheet reference from cfg file. (Sent from mobile)
> […](#)
> On Jun 23, 2019, at 22:37, michaell-nz ***@***.***> wrote: @wsobel, localhost:5000/probe or localhost:5000 loads correct xml file. Just that localhost:5000/current will display empty page. I have also tested the same on a brand new Windows 10 laptop, which returned the same problem. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wsobel** [comment]
Use curl from the command line. The agent is not really a web server, it is a REST service meant for data collection. 

(Sent from mobile)

**Comment by michaell-nz** [comment]
@wsobel, much appreciated. Use curl from command line is the answer.

**Comment by Krdera89** [comment]
@wsobel @russwaddell I am trying to get the TCP server to connect on port 7878 but it seems to drop connection. I am except using Raspberry Pi 3 OS and followed steps on https://mtcup.org/Installing_C++_Agent_on_Ubuntu     and   https://hub.docker.com/r/raymondhub/mtconnect

cd ~/agent/cppagent/simulator
ruby run_scenario.rb -l VMC-3Axis-Log.txt      # After running this command i get the following:

#waiting for first connection
#waiting on #<TCPServer:0x0199f6c8>7878
#Client connected
#waiting on #<TCPServer:0x0199f6c8>7878
#Heartbeat thread error, exiting: connection reset by peer
#broken pipe

Any ideas on what the issue could be? I have tried a variety of solutions but none of them have seemed to work.

**Comment by wsobel** [comment]
I'm not sure why the agent disconnect. To diagnose, you should set the agent logging level to debug and then upload the logs from the agent. 

Once we see the logs, we should have a better idea. 

```
logger_config
{
    logging_level = debug
    output = file agent.log
}

```

**Comment by Krdera89** [comment]
@wsobel hello, sorry for the late response. My raspberry pi seemed to be acting up after running a command to try and fix the problem I stated above so I had to reformat the sd card and start from scratch again... What logs specifically are you referring to? How would I be able to show you the log? would you like a screenshot of it..?

**Comment by wsobel** [comment]
I’m currently on vacation right now and will look into this next week. I have a Pi at home and can try to reproduce your issue. The logs I was referring to are in the directory that the agent executable resides in. You can also change it by configuring the logger section of the agent.cfg. Best RegardsW(Sent from mobile)On Feb 20, 2023, at 21:58, Kevin Deras ***@***.***> wrote:﻿
@wsobel hello, sorry for the late response. My raspberry pi seemed to be acting up after running a command to try and fix the problem I stated above so I had to reformat the sd card and start from scratch again... What logs specifically are you referring to? How would I be able to show you the log? would you like a screenshot of it..?

**Comment by Krdera89** [comment]
@wsobel were you able to reproduce the issue I have been having? I'll provide screenshots of the issue of it helps.

**Comment by Krdera89** [comment]
Hello @wsobel sorry for the late response, if you wouldnt mind reproduce the issue I am having on your rpi at home that would be helpful.. I am not seeing the logs you are referring to, I tried changing the logger section of the agent.cfg but I am still having issues.. Please refer to the screen shots below just unzip the folder and view.
I hope this is an easy fix. 
Thank you.

[Rpi.zip](https://github.com/mtconnect/cppagent/files/11147912/Rpi.zip)
