### ISSUE TITLE
Agent adding name attributes to components in stream

### ISSUE THREAD

**Issue by NeilDes** [mtconnect/cppagent#118]
In the V1.4 Part2 doc, It states that the ‘name=’ attribute for a Component is optional.  I left it off a few new components (Personnel, Stock, Environmental) but the AGENT (V1.4.10) added the attribute automatically in the stream with no value (name=””).  This caused a validation error for part3.

Device file…
<Personnel id="personnel">
Stream from agent…
<ComponentStream component="Personnel" name="" componentId="personnel">

**Comment by wsobel** [comment]
Fixed in Commit 9f0db074b0 Version v1.4.0.11

**Comment by wsobel** [comment]
Tested and fixed.
