### ISSUE TITLE
Built MTConnect docker image

### ISSUE THREAD

**Issue by RaymondCui21** [mtconnect/cppagent#119]
Prepared a MTConnect docker image (https://hub.docker.com/r/raymondhub/mtconnect)
This docker image could be useful to beginners to quickly setup a testing scenario for MTConnect. 
It works well in the docker of CentOS and Ubuntu.
Please let me know if it works in Windows.

**Comment by wsobel** [comment]
Thanks! This is great. Thanks a lot for putting this together. We will try to promote.

**Comment by RaymondCui21** [comment]
@wsobel You are welcome, William.

**Comment by russwaddell** [comment]
Installed and tested for Raspberry Pi. I couldn't get the adapter simulator running, but successfully connected to another adapter on a machine we have for testing. The docker image saved a lot of time and trouble versus building the agent.

**Comment by RaymondCui21** [comment]
@russwaddell Thank you very much for the feedback. Sorry, I do not have Raspberry Pi for testing the docker image now. But I will try to find one to test the image later. I will update the image if the new version 1.5 is published.

**Comment by russwaddell** [comment]
I talked to @wsobel about the adapter sim before you created the docker image because I was also having problems getting it to work then. I think the issue may be with the simulator itself.

**Comment by wsobel** [comment]
Raymond,

Thanks a lot for putting this together. 

Do you have access to the mtconnect/cppagent_dev repo? If not, have you signed the MTConnect IP policy?

If you have signed the ip policy, I can give you access. 

Thanks!
W

(Sent from mobile)

**Comment by russwaddell** [comment]
IP Policy is at www.mtconnect.org/join

**Comment by RaymondCui21** [comment]
@wsobel I do not have the access and have not signed the policy.
@russwaddell Thank you very much. Will have a quick look at the policy and get back to you.

**Comment by wsobel** [comment]
tell me when you have signed and I’ll give you access. 

I welcome your assistance!

- W

**Comment by RaymondCui21** [comment]
@wsobel Thank you very much for your prompt reply. I would like to assist the development of MTConnect as possible as I can.  On the policy page, because the field of Company or Organization is required, how could I sign the policy since I am not affiliated with a company, just my own?

**Comment by wsobel** [comment]
@russwaddel is the best person to answer these questions...

**Comment by RaymondCui21** [comment]
@wsobel Thank you.

**Comment by RaymondCui21** [comment]
> IP Policy is at [www.mtconnect.org/join](http://www.mtconnect.org/join)

@russwaddell Hi Russ, because the field of Company or Organization is required, how could I sign the policy since I am not affiliated with a company, just my own? Thanks.

**Comment by russwaddell** [comment]
Just leave the field blank or put "Individual." The overwhelming majority who join are affiliated with an organization but individual contributors are welcome as well.

**Comment by RaymondCui21** [comment]
@russwaddell Thank you. I signed it online.

**Comment by wsobel** [comment]
You've been added to the Agent team... you'll have access to cppagent_dev

**Comment by RaymondCui21** [comment]
@wsobel Thank you very much.

**Comment by RaymondCui21** [comment]
@wsobel @russwaddell Hi William and Russ, I updated the docker image to MTConnect v1.5  (https://hub.docker.com/r/raymondhub/mtconnect). Is it appropriate to make it open to the public since it is built from the cppagent_dev (private)?

**Comment by wsobel** [comment]
The 1.5 affect in cppagent can be released since it contains some new capabilities that have not passed ip approval. People can use it as an agent and expose it publically, but they are not allowed to make use our expose the new normative capabilities. 

The source cannot be made public yet since it will expose new data items that are going through review. 

The docker fike can be added to 1.5 if that is possible. The Unix directory has new build instructions and some other scripts for systemd and upstart. Seems like a good home. 

(Sent from mobile)

**Comment by paulkling** [comment]
@RaymondCui21 
I know this issue closed but I am wondering if the Dockerfile for docker image could be made available.  That way I can build it locally on my computer. I worry about using someones pre-built container. Never know what was stuck into the the container. 

I am willing to contribute Dockerfile myself but unsure the state of this issue.

@wsobel for this project are you interested in having a Dockerfile added to repo for people to build there own version?

**Comment by RaymondCui21** [comment]
@wsobel Thank you very much. The 1.5 version is added to the docker image.

@paulkling Hi Paul, I have not added the Dockerfile to the repo yet. But will definitely do it soon. Thank you very much if you could contribute your Dockerfile as well.

**Comment by RaymondCui21** [comment]
@paulkling Hi Paul, MTConnect V1.4 Dockerfile is uploaded to the Dockerhub. The code is released publicly. Hopefully it could remove you worry.

@wsobel Hi William, do you mean that the new build instructions and some other scripts for systemd and upstart are provided in MTConnect github?
