### ISSUE TITLE
Heartbeat read exception: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall.

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#120]
I am having this issue when running agent and adapter on Windows XP SP3 but not on every machine.

**Heartbeat read exception: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall.**

Eventually, the connection between agent and adapter is terminated. As a result, agent receives no more data from adapter. 

I am not sure why this error is happening
Anyone has this kind of error happening between agent and adapter.

Thanks

**Comment by wsobel** [comment]
Is this still happening? Please copy to dev if it is.

**Comment by hulinning2** [comment]
It is still happening. I just work around it by detecting and reconnecting the again.
I am not sure it is related to OS or not.
