### ISSUE TITLE
Issue with MonitorConfigFiles parameter

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#121]
MonitorConfigFiles=true 
does not work correctly when the devices.xml is changed.

Thanks

**Comment by wsobel** [comment]
Please provide the operating system and platform info. 

(Sent from mobile)

**Comment by hulinning2** [comment]
Win7x86 and WinXPSp3 x86
I am using cppagent_win32_XP_1.4.0.11_bin

Thanks

**Comment by wsobel** [comment]
Thanks. I’ll check it out. 

(Sent from mobile)

**Comment by wsobel** [comment]
Found a problem with windows xp and stat. Switched to Windows internal GetFileTime function with windows and converted back to time_t for comparison. Fixed in v1.4.0.12

**Comment by wsobel** [comment]
Is this now fixed?

**Comment by hulinning2** [comment]
Fixed
Thanks
