### ISSUE TITLE
Multiple devices and different addresses

### ISSUE THREAD

**Issue by maddionacsmt** [mtconnect/cppagent#123]
Good morning,
I have N devices to connect and I've tried to set 1 adapter for each device as described in the readme. I am able to receive data from each device, but I am not able to identify a unique IP address for each device.
For example if I listen to "localhost:5000/deviceID1" I receive the stream from all the adapters. 
Is it possible to have unique IP one for each device? Or I need to install multiple agents one per machine?

Thank you

[Devices.txt](https://github.com/mtconnect/cppagent/files/3599533/Devices.txt)

[Agent.txt](https://github.com/mtconnect/cppagent/files/3599534/Agent.txt)

**Comment by wsobel** [comment]
The agent will have a single ip and port from which it serves data. The agent can support  one or more devices , that choice is yours. 

Each device can be treated separately by using the rest requests with the device name or uuid as the first part of the URI. 

http://example.com:5000/1-ALC400G/current

Will give only current data for the one device 

A separate IP address would mean deploying an agent on separate physical or virtual machines or network interfaces. You could also have multiple agents on the same machine bound to different ports:

example:5000
example:5001
Etc...

Please tell me more about what you are trying to do. 

Best 
Will

(Sent from mobile)
