### ISSUE TITLE
"sampelInterval" attribute per Device or Component not working

### ISSUE THREAD

**Issue by vladislav-mitev** [mtconnect/cppagent#131]
Hello all,
we are reading data from Nakamura Tome machines with Fanuc controllers. For the purpose we have a licensed FOCAS library.
One issue that we are trying to solve is that some machines are sending too much data for axis speeds and loads - several times per second. We want to skip or aggregate values so that we get only one value per specified interval e.g. 1 value per 2 seconds.

According to the documentation we should be able to use the attribute `sampleInterval` on the device or component level. What we expect is that if we set this to `sampleInterval="2000.0"` the MTC Agent should send us samples on every 2 seconds. However, when we set this, nothing changes..

We tried using the `statistic="AVERAGE"` and `sampleRate="0.5"` attributes for the specific DataItems, but nothing changes. Still receiving values more often than 2 seconds.

We also tried combining the above two approaches, but again no success.

How should we approach our problem?
Any help is highly appreciated!

**Comment by wsobel** [comment]
The sample interval is for documentation. The adapter controls the actual sample rates–this should be set to reflect the adapters' rate. The agent itself does not sample or poll the data sources, the adapters are responsible for all polling and communication with the proprietary API.

This information could be passed from the adapter to the agent, there are some development items open to having the Devices.xml information pushed from the adapter to the agent. This has not been completed yet.

Statistics are used to include the duration in the report of the data. The average is computed in the adapter and sent to the agent. The agent then presents the average value and the duration back from the timestamp (observation time) the data were averaged.

I'd be happy to discuss. There are a lot of new features we're planning on adding to the agent. As it is open-source, features can always be suggested and added.

Hope this helps, 
Will Sobel

**Comment by vladislav-mitev** [comment]
Thank you, Will,
actually that was also our conclusion. We somehow thought that only some XML configurations are "passive"/"descriptive".
