### ISSUE TITLE
Agent is not compatible with schema 1.3 for sample and current data stream

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#134]
MTConnect Agent Version 1.5.0.12 Release is not compatible with schema 1.3 for sample and current.
data stream.  It is not an issue with schema since I did try older version of MTConnect 1.3.0.17 and it works as expected.

**Comment by wsobel** [comment]
What is the specific incompatibility? I can probably adjust the features to accommodate. 

Thanks
W

(Sent from mobile)

**Comment by hulinning2** [comment]
I got this error in XmlSpy for current and sample data stream when using new Agent.

File http://localhost:5000/current is not valid.
	Attribute 'assetType' is required in element <AssetChanged>.
		Annotations of element 'AssetChanged' (see below)
			An asset was just modified
		Annotations of type 'AssetChangedType' (see below)
			An asset was just modified
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Events / AssetChanged
		Details
			cvc-complex-type.4: Required attribute 'assetType' is missing from element <AssetChanged>.
			cvc-type.3.2: Element <AssetChanged> is not valid with respect to type definition 'AssetChangedType'.
			cvc-elt.5: The element <AssetChanged> is not valid with respect to the actual type definition 'AssetChangedType'.
			cvc-assess-elt.1.1: Strict assessment of element <AssetChanged> with governing element declaration 'AssetChanged' failed.
	Attribute 'assetType' is required in element <AssetRemoved>.
		Annotations of element 'AssetRemoved' (see below)
			An asset was just modified
		Annotations of type 'AssetRemovedType' (see below)
			An asset was just modified
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Events / AssetRemoved
		Details
			cvc-complex-type.4: Required attribute 'assetType' is missing from element <AssetRemoved>.
			cvc-type.3.2: Element <AssetRemoved> is not valid with respect to type definition 'AssetRemovedType'.
			cvc-elt.5: The element <AssetRemoved> is not valid with respect to the actual type definition 'AssetRemovedType'.
			cvc-assess-elt.1.1: Strict assessment of element <AssetRemoved> with governing element declaration 'AssetRemoved' failed.

**Comment by wsobel** [comment]
I need to patch the xsd. Thanks - W

(Sent from mobile)

**Comment by hulinning2** [comment]
Fixed on 1.3
but I think I still got issues on 1.5 
I am checking again

**Comment by wsobel** [comment]
Check with the schemas out of the repo, I'm going to do the next build once we have these issues closed.

Thanks - W

**Comment by hulinning2** [comment]
I think the issues are with the extended schema. I checked my extended schema and it is not valid with 1.5 spec

The schema doesn't appear to be valid by itself (as a part of another schema, it might still be OK).
	The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
		Error location: xs:schema / xs:complexType / xs:simpleContent
		Details
			st-props-correct.1: The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
	The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
		Error location: xs:schema / xs:complexType / xs:simpleContent
		Details
			st-props-correct.1: The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
	The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
		Error location: xs:schema / xs:complexType / xs:simpleContent
		Details
			st-props-correct.1: The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
	The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
		Error location: xs:schema / xs:complexType / xs:simpleContent
		Details
			st-props-correct.1: The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
	The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
		Error location: xs:schema / xs:complexType / xs:simpleContent
		Details
			st-props-correct.1: The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
	The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
		Error location: xs:schema / xs:complexType / xs:simpleContent
		Details
			st-props-correct.1: The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
	The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
		Error location: xs:schema / xs:complexType / xs:simpleContent
		Details
			st-props-correct.1: The variety of simple type definition '{anonymous}' is absent. This is only permitted for xs:anySimpleType.
	User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
		Details
			cos-st-restricts: User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
	User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
		Details
			cos-st-restricts: User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
	User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
		Details
			cos-st-restricts: User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
	User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
		Details
			cos-st-restricts: User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
	User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
		Details
			cos-st-restricts: User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
	User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
		Details
			cos-st-restricts: User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
	User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.
		Details
			cos-st-restricts: User-defined simple type definition '{anonymous}' cannot restrict the simple ur-type definition.

**Comment by wsobel** [comment]
This could be because of the schema refactor. I was trying to get the other changes working first. I’ll check out your extension.

**Comment by wsobel** [comment]
Please upload your extended schema to this issue.

**Comment by hulinning2** [comment]
[Spec1_5.zip](https://github.com/mtconnect/cppagent/files/3975823/Spec1_5.zip)

**Comment by wsobel** [comment]
I have added some additional `simpleType` declarations and made the samples just extensions of the `CommonSample` which is a floating-point value. See attached.


[OkumaStreams_1.5.xsd.zip](https://github.com/mtconnect/cppagent/files/3976536/OkumaStreams_1.5.xsd.zip)

**Comment by hulinning2** [comment]
Fixed
