### ISSUE TITLE
1.4 Assets schema: cuttingToolId vs toolId attribute

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#137]
still does not work correctly in the latest Agent. I think schema is not updated yet for 1.4

File http://localhost:5000/assets is not valid.
Attribute 'toolId' is not allowed in element
Annotations of element 'CuttingTool' (see below)
A cutting tool
Annotations of type 'CuttingToolType' (see below)
A cutting tool
Error location: MTConnectAssets / Assets / CuttingTool / @toolId
Details
cvc-complex-type.2.2.1: Complex type definition 'CuttingToolType' of element does not allow attribute 'toolId' and has no attribute wildcard.
cvc-type.3.2: Element is not valid with respect to type definition 'CuttingToolType'.
cvc-elt.5: The element is not valid with respect to the actual type definition 'CuttingToolType'.
cvc-assess-elt.1.1: Strict assessment of element with governing element declaration 'CuttingTool' failed.
Attribute 'cuttingToolId' is required in element .
Annotations of element 'CuttingTool' (see below)
A cutting tool
Annotations of type 'CuttingToolType' (see below)
A cutting tool
Error location: MTConnectAssets / Assets / CuttingTool
Details
cvc-complex-type.3: Required attribute 'cuttingToolId' is missing from element .
cvc-type.3.2: Element is not valid with respect to type definition 'CuttingToolType'.
cvc-elt.5: The element is not valid with respect to the actual type definition 'CuttingToolType'.
cvc-assess-elt.1.1: Strict assessment of element with governing element declaration 'CuttingTool' failed.

**Comment by wsobel** [comment]
Is this the build or the repo? I have not repackaged since I was waiting to validate the schemas are correct. Please check with the schema file in the repo and if correct I will repackage. 

Thanks
W

(Sent from mobile)

**Comment by hulinning2** [comment]
schema in repo are correct but not in the latest release of Agent 13

**Comment by wsobel** [comment]
Thanks. I’ll repackage. 

(Sent from mobile)

**Comment by hulinning2** [comment]
Fixed. 
I only checked 1.2 to 1.5 spec.

Thanks

**Comment by wsobel** [comment]
Thanks!

(Sent from mobile)
