### ISSUE TITLE
MonitorConfigFiles not working intermittently

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#138]
SchemaVersion = 1.2			# using schema version 1.2
Port=5000						# default port number for agent  
UpcaseDataItemValue=false
MonitorConfigFiles=true			# True = reload devices.xml and agent.cfg if they are changed
MinimumConfigReloadAge = 1		# Number of seconds agent service will wait before performing reload config files

On my adapter, it can support multiple versions of MTConnect specs by updating agent.cfg first and the devices.xml next.  It works most of the times.  However, sometimes agent cannot detect the changes  and still sends old devices.xml from the previous spec.
Ex: I switch my adapter to support spec 1.2 from spec 1.3 and agent.cfg and devices.xml are changed accordingly. Once my adapter is fully configured for spec 1.2 the browser is still displaying devices for spec 1.3 instead of spec 1.2 although the  agent.cfg and evices.xml have been changed to 1.3. 

Of course, If I try again it will work or manually restart the agent service itself.

Thanks

**Comment by wsobel** [comment]
Check the logs and see if the agent is warm restarting. 

Thanks
W

(Sent from mobile)

**Comment by hulinning2** [comment]
No I do not see any warming restarting in log file

**Comment by wsobel** [comment]
What OS are you testing on? Is it the win64 or win32 build?

Thanks
W

(Sent from mobile)

**Comment by hulinning2** [comment]
Windows 10 x 64 
I am using win32 build since my Adapter must be in win32 only

**Comment by hulinning2** [comment]
It seems that agent has an issue when agent.cfg is changed and client also requests for data.

Thanks

**Comment by wsobel** [comment]
Hmm. This may be because the server is not cleanly shutting down. Thanks for the info, helps reproduce. 

(Sent from mobile)

**Comment by hulinning2** [comment]
Have you got a chance to look into this issue yet?

**Comment by wsobel** [comment]
I have not had a lot of time to work on this–will work on reproducing soon. - W

**Comment by hulinning2** [comment]
any update on this issue?

**Comment by wsobel** [comment]
sorry, not yet, will get to once we are a bit further along with the 1.6 release.

**Comment by hulinning2** [comment]
any progress on this issue?
