### ISSUE TITLE
LineLabel error in schema 1.4

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#139]
It is ok in schema 1.5 but not in 1.4

File http://localhost:5000/current is not valid.
	Element <LineLabel> is not allowed under element <Events>.
		Reason: The following elements are expected at this location (see below)
			'Variables'
			'Macman'
			'InputSignal'
			'OutputSignal'
			'InputOutputSignal'
			'BlockNumber'
			'Event'
			'Code'
			'Block'
			'Line'
			'PowerStatus'
			'PowerState'
			'PartCount'
			'Direction'
			'Program'
			'Execution'
			'ControllerMode'
			'ToolId'
			'ToolNumber'
			'ToolAssetId'
			'PartId'
			'DoorState'
			'RotaryMode'
			'ActiveAxes'
			'CoupledAxes'
			'AxesCoupling'
			'Message'
			'EmergencyStop'
			'Availability'
			'ActuatorState'
			'PathMode'
			'LinePowerState'
			'ControlPowerState'
			'AssetChanged'
			'AssetRemoved'
			'WorkholdingId'
			'ChuckState'
			'EndOfBar'
			'AxisInterlock'
			'ChuckInterlock'
			'AxisState'
			'PathFeedrateOverride'
			'AxisFeedrateOverride'
			'RotaryVelocityOverride'
			'PartAssetId'
			'FunctionalMode'
			'PalletId'
			'ProgramComment'
			'ProgramHeader'
			'OperatorId'
			...
		Annotations of element 'Events' (see below)
			A collection of events
		Annotations of type 'EventsType' (see below)
			A collection of events and alarms for this component
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Events / LineLabel
		Details
			cvc-complex-type.1.4: Element <LineLabel> unexpected by type 'EventsType' of element <Events>.
			cvc-type.3.2: Element <Events> is not valid with respect to type definition 'EventsType'.
			cvc-elt.5.2.1: The element <Events> is not valid with respect to the actual type definition 'EventsType'.

**Comment by wsobel** [comment]
Please attach the example. 

There were changes in 1.5 from the 1.4 that don’t allow the same schema extension to work for both. 

(Sent from mobile)

**Comment by hulinning2** [comment]
I use exactly the same devices.xml file for 1.4 and 1.5 except for referencing different schema of 1.4 or 1.5.
[LatheDevices.zip](https://github.com/mtconnect/cppagent/files/4011171/LatheDevices.zip)

thanks

**Comment by hulinning2** [comment]
Still does not work in the latest release of schema 1.4

File http://localhost:5000/current is not valid.
	Element <LineLabel> is not allowed under element <Events>.
		Reason: The following elements are expected at this location (see below)
			'Variables'
			'Macman'
			'InputSignal'
			'OutputSignal'
			'InputOutputSignal'
			'BlockNumber'
			'Event'
			'Code'
			'Block'
			'Line'
			'PowerStatus'
			'PowerState'
			'PartCount'
			'Direction'
			'Program'
			'Execution'
			'ControllerMode'
			'ToolId'
			'ToolNumber'
			'ToolAssetId'
			'PartId'
			'DoorState'
			'RotaryMode'
			'ActiveAxes'
			'CoupledAxes'
			'AxesCoupling'
			'Message'
			'EmergencyStop'
			'Availability'
			'ActuatorState'
			'PathMode'
			'LinePowerState'
			'ControlPowerState'
			'AssetChanged'
			'AssetRemoved'
			'WorkholdingId'
			'ChuckState'
			'EndOfBar'
			'AxisInterlock'
			'ChuckInterlock'
			'AxisState'
			'PathFeedrateOverride'
			'AxisFeedrateOverride'
			'RotaryVelocityOverride'
			'PartAssetId'
			'FunctionalMode'
			'PalletId'
			'ProgramComment'
			'ProgramHeader'
			'OperatorId'
			...
		Annotations of element 'Events' (see below)
			A collection of events
		Annotations of type 'EventsType' (see below)
			A collection of events and alarms for this component
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Events / LineLabel
		Details
			cvc-complex-type.1.4: Element <LineLabel> unexpected by type 'EventsType' of element <Events>.
			cvc-type.3.2: Element <Events> is not valid with respect to type definition 'EventsType'.
			cvc-elt.5.2.1: The element <Events> is not valid with respect to the actual type definition 'EventsType'.

**Comment by wsobel** [comment]
Added LineLabel to the 1.4 streams. Updated to http://schemas.mtconnect.org and github.

**Comment by hulinning2** [comment]
Fixed
