### ISSUE TITLE
Auxiliaries is not valid in probe command for schema 1.4

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#141]
It is ok in schema 1.5

File http://localhost:5000/probe is not valid.
	Element <Auxiliaries id="LAux1"> is not allowed under element <Components>.
		Reason: The following elements are expected at this location (see below)
			'Component'
			'CommonComponent'
			'Device'
			'Controller'
			'Power'
			'Sensor'
			'Path'
			'Actuator'
			'Door'
			'Axes'
			'Axis'
			'Linear'
			'Rotary'
			'Spindle'
			'Systems'
			'System'
			'Pneumatic'
			'Hydraulic'
			'Lubrication'
			'Coolant'
			'Electric'
			'Interfaces'
			'Interface'
			'BarFeederInterface'
			'MaterialHandlerInterface'
			'DoorInterface'
			'ChuckInterface'
		Annotations of element 'Components' (see below)
			The sub components
		Annotations of type 'ComponentsType' (see below)
			A list of generic components
		Error location: MTConnectDevices / Devices / Device / Components / Auxiliaries
		Details
			cvc-complex-type.1.4: Element <Auxiliaries id="LAux1"> unexpected by type 'ComponentsType' of element <Components>.
			cvc-type.3.2: Element <Components> is not valid with respect to type definition 'ComponentsType'.
			cvc-elt.5.2.1: The element <Components> is not valid with respect to the actual type definition 'ComponentsType'.

**Comment by wsobel** [comment]
Please attach the example. 

(Sent from mobile)

**Comment by wsobel** [comment]
Was auxiliaries included in 1.4? This was pro  an oversight if it was. Thanks for testing. 

(Sent from mobile)

**Comment by hulinning2** [comment]
Yes it is in 1.4 part 2 spec.
5.4 Auxiliaries ........................................................................................................................................... 40
5.4.1 Loader System ................................................................................................................................... 41
5.4.2 WasteDisposal System .................................................................................................................. 41
5.4.3 ToolingDelivery System ............................................................................................................. 41
5.4.4 BarFeeder System ............................................................................................................................ 41
5.4.5 Environmental System .................................................................................................................. 41
5.4.6 Sensor System ................................................................................................................................... 41

**Comment by wsobel** [comment]
Added to 1.4 schemas. Check on http://schemas.mtconnect.org/

**Comment by hulinning2** [comment]
Fixed
