### ISSUE TITLE
Equipment_Timer is not valid in spec 1.4

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#142]
File http://localhost:5000/current is not valid.
	Element <EquipmentTimer> is not allowed under element <Samples>.
		Reason: The following elements are expected at this location (see below)
			'SurfaceSpeed'
			'PathFeedratePerRev'
			'AnalogInputOutput'
			'Sample'
			'Amperage'
			'GlobalPosition'
			'Position'
			'Velocity'
			'Acceleration'
			'AngularAcceleration'
			'AngularVelocity'
			'PathFeedrate'
			'AxisFeedrate'
			'SpindleSpeed'
			'RotaryVelocity'
			'Angle'
			'Temperature'
			'Load'
			'Frequency'
			'Volts'
			'Voltage'
			'Watt'
			'Pressure'
			'Torque'
			'PathPosition'
			'Wattage'
			'Displacement'
			'Tilt'
			'AccumulatedTime'
			'PowerFactor'
			'Strain'
			'Flow'
			'SoundPressure'
			'Resistance'
			'Conductivity'
			'Viscosity'
			'Concentration'
			'ElectricalEnergy'
			'FillLevel'
			'LinearForce'
			'Length'
			'AbsTimeSeries'
			'TimeSeries'
			'AmperageTimeSeries'
			'GlobalPositionTimeSeries'
			'PositionTimeSeries'
			'VelocityTimeSeries'
			'AccelerationTimeSeries'
			'AngularAccelerationTimeSeries'
			'AngularVelocityTimeSeries'
			...
		Annotations of element 'Samples' (see below)
			A collection of samples
		Annotations of type 'SamplesType' (see below)
			A collection of samples for this component
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Samples / EquipmentTimer
		Details
			cvc-complex-type.1.4: Element <EquipmentTimer> unexpected by type 'SamplesType' of element <Samples>.
			cvc-type.3.2: Element <Samples> is not valid with respect to type definition 'SamplesType'.
			cvc-elt.5.2.1: The element <Samples> is not valid with respect to the actual type definition 'SamplesType'.
	Element <LineLabel> is not allowed under element <Events>.
		Reason: The following elements are expected at this location (see below)
			'Variables'
			'Macman'
			'InputSignal'
			'OutputSignal'
			'InputOutputSignal'
			'BlockNumber'
			'Event'
			'Code'
			'Block'
			'Line'
			'PowerStatus'
			'PowerState'
			'PartCount'
			'Direction'
			'Program'
			'Execution'
			'ControllerMode'
			'ToolId'
			'ToolNumber'
			'ToolAssetId'
			'PartId'
			'DoorState'
			'RotaryMode'
			'ActiveAxes'
			'CoupledAxes'
			'AxesCoupling'
			'Message'
			'EmergencyStop'
			'Availability'
			'ActuatorState'
			'PathMode'
			'LinePowerState'
			'ControlPowerState'
			'AssetChanged'
			'AssetRemoved'
			'WorkholdingId'
			'ChuckState'
			'EndOfBar'
			'AxisInterlock'
			'ChuckInterlock'
			'AxisState'
			'PathFeedrateOverride'
			'AxisFeedrateOverride'
			'RotaryVelocityOverride'
			'PartAssetId'
			'FunctionalMode'
			'PalletId'
			'ProgramComment'
			'ProgramHeader'
			'OperatorId'
			...
		Annotations of element 'Events' (see below)
			A collection of events
		Annotations of type 'EventsType' (see below)
			A collection of events and alarms for this component
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Events / LineLabel
		Details
			cvc-complex-type.1.4: Element <LineLabel> unexpected by type 'EventsType' of element <Events>.
			cvc-type.3.2: Element <Events> is not valid with respect to type definition 'EventsType'.
			cvc-elt.5.2.1: The element <Events> is not valid with respect to the actual type definition 'EventsType'.

**Comment by wsobel** [comment]
I'll check the schema.

**Comment by wsobel** [comment]
Added to 1.4 schemas. Check on http://schemas.mtconnect.org/

**Comment by hulinning2** [comment]
still having issues with 1.4

File http://localhost:5000/current is not valid.
	Value 'LOADED' is not allowed for attribute 'subType'.
		Annotations of type 'DataItemSubEnumType' (see below)
			The sub-types for a measurement
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Samples / EquipmentTimer / @subType
		Details
			cvc-datatype-valid.1.2.3: For type definition 'DataItemSubEnumType' the string 'LOADED' should be a literal in the lexical space of at least one member of its member type definitions: 'DataItemSubEnumTypeEnum', 'DataItemExtType'.
			cvc-simple-type.1: For type definition 'DataItemSubEnumType' the string 'LOADED' is not valid.
			cvc-attribute.3: Value 'LOADED' of attribute 'subType' does not match simple type definition 'DataItemSubEnumType'.
			cvc-assess-elt.2: Assessment of attribute 'subType' failed.
	Value 'OPERATING' is not allowed for attribute 'subType'.
		Annotations of type 'DataItemSubEnumType' (see below)
			The sub-types for a measurement
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Samples / EquipmentTimer / @subType
		Details
			cvc-datatype-valid.1.2.3: For type definition 'DataItemSubEnumType' the string 'OPERATING' should be a literal in the lexical space of at least one member of its member type definitions: 'DataItemSubEnumTypeEnum', 'DataItemExtType'.
			cvc-simple-type.1: For type definition 'DataItemSubEnumType' the string 'OPERATING' is not valid.
			cvc-attribute.3: Value 'OPERATING' of attribute 'subType' does not match simple type definition 'DataItemSubEnumType'.
			cvc-assess-elt.2: Assessment of attribute 'subType' failed.
	Value 'WORKING' is not allowed for attribute 'subType'.
		Annotations of type 'DataItemSubEnumType' (see below)
			The sub-types for a measurement
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Samples / EquipmentTimer / @subType
		Details
			cvc-datatype-valid.1.2.3: For type definition 'DataItemSubEnumType' the string 'WORKING' should be a literal in the lexical space of at least one member of its member type definitions: 'DataItemSubEnumTypeEnum', 'DataItemExtType'.
			cvc-simple-type.1: For type definition 'DataItemSubEnumType' the string 'WORKING' is not valid.
			cvc-attribute.3: Value 'WORKING' of attribute 'subType' does not match simple type definition 'DataItemSubEnumType'.
			cvc-assess-elt.2: Assessment of attribute 'subType' failed.
	Element <LineLabel> is not allowed under element <Events>.
		Reason: The following elements are expected at this location (see below)
			'Variables'
			'Macman'
			'InputSignal'
			'OutputSignal'
			'InputOutputSignal'
			'BlockNumber'
			'Event'
			'Code'
			'Block'
			'Line'
			'PowerStatus'
			'PowerState'
			'PartCount'
			'Direction'
			'Program'
			'Execution'
			'ControllerMode'
			'ToolId'
			'ToolNumber'
			'ToolAssetId'
			'PartId'
			'DoorState'
			'RotaryMode'
			'ActiveAxes'
			'CoupledAxes'
			'AxesCoupling'
			'Message'
			'EmergencyStop'
			'Availability'
			'ActuatorState'
			'PathMode'
			'LinePowerState'
			'ControlPowerState'
			'AssetChanged'
			'AssetRemoved'
			'WorkholdingId'
			'ChuckState'
			'EndOfBar'
			'AxisInterlock'
			'ChuckInterlock'
			'AxisState'
			'PathFeedrateOverride'
			'AxisFeedrateOverride'
			'RotaryVelocityOverride'
			'PartAssetId'
			'FunctionalMode'
			'PalletId'
			'ProgramComment'
			'ProgramHeader'
			'OperatorId'
			...
		Annotations of element 'Events' (see below)
			A collection of events
		Annotations of type 'EventsType' (see below)
			A collection of events and alarms for this component
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Events / LineLabel
		Details
			cvc-complex-type.1.4: Element <LineLabel> unexpected by type 'EventsType' of element <Events>.
			cvc-type.3.2: Element <Events> is not valid with respect to type definition 'EventsType'.
			cvc-elt.5.2.1: The element <Events> is not valid with respect to the actual type definition 'EventsType'.

**Comment by hulinning2** [comment]
still having issue with 1.4 probe command:

File http://localhost:5000/probe is not valid.
	Value 'WORKING' is not allowed for attribute 'subType'.
		Annotations of type 'DataItemSubEnumType' (see below)
			The sub-types for a measurement
		Error location: MTConnectDevices / Devices / Device / Components / Controller / DataItems / DataItem / @subType
		Details
			cvc-datatype-valid.2.3: For type definition 'DataItemSubEnumType' the string 'WORKING' should be a literal in the lexical space of at least one member of its member type definitions: 'DataItemSubEnumTypeEnum', 'DataItemExtType'.
			cvc-simple-type.2: For type definition 'DataItemSubEnumType' the string 'WORKING' is not valid.
			cvc-attribute.3: Value 'WORKING' of attribute 'subType' does not match simple type definition 'DataItemSubEnumType'.
			cvc-assess-elt.2.1: Assessment of attribute 'subType' failed.
	Value 'OPERATING' is not allowed for attribute 'subType'.
		Annotations of type 'DataItemSubEnumType' (see below)
			The sub-types for a measurement
		Error location: MTConnectDevices / Devices / Device / Components / Controller / DataItems / DataItem / @subType
		Details
			cvc-datatype-valid.2.3: For type definition 'DataItemSubEnumType' the string 'OPERATING' should be a literal in the lexical space of at least one member of its member type definitions: 'DataItemSubEnumTypeEnum', 'DataItemExtType'.
			cvc-simple-type.2: For type definition 'DataItemSubEnumType' the string 'OPERATING' is not valid.
			cvc-attribute.3: Value 'OPERATING' of attribute 'subType' does not match simple type definition 'DataItemSubEnumType'.
			cvc-assess-elt.2.1: Assessment of attribute 'subType' failed.
	Value 'LOADED' is not allowed for attribute 'subType'.
		Annotations of type 'DataItemSubEnumType' (see below)
			The sub-types for a measurement
		Error location: MTConnectDevices / Devices / Device / Components / Controller / DataItems / DataItem / @subType
		Details
			cvc-datatype-valid.2.3: For type definition 'DataItemSubEnumType' the string 'LOADED' should be a literal in the lexical space of at least one member of its member type definitions: 'DataItemSubEnumTypeEnum', 'DataItemExtType'.
			cvc-simple-type.2: For type definition 'DataItemSubEnumType' the string 'LOADED' is not valid.
			cvc-attribute.3: Value 'LOADED' of attribute 'subType' does not match simple type definition 'DataItemSubEnumType'.
			cvc-assess-elt.2.1: Assessment of attribute 'subType' failed.
	Element <Loader id="LLoaderSystem1"> is not allowed under element <Components>.
		Reason: The following elements are expected at this location (see below)
			'Component'
			'CommonComponent'
			'Device'
			'Controller'
			'Power'
			'Sensor'
			'Path'
			'Actuator'
			'Door'
			'Auxiliaries'
			'Axes'
			'Axis'
			'Linear'
			'Rotary'
			'Spindle'
			'Systems'
			'System'
			'Pneumatic'
			'Hydraulic'
			'Lubrication'
			'Coolant'
			'Electric'
			'Interfaces'
			'Interface'
			'BarFeederInterface'
			'MaterialHandlerInterface'
			'DoorInterface'
			'ChuckInterface'
		Annotations of element 'Components' (see below)
			The sub components
		Annotations of type 'ComponentsType' (see below)
			A list of generic components
		Error location: MTConnectDevices / Devices / Device / Components / Auxiliaries / Components / Loader
		Details
			cvc-complex-type.1.4: Element <Loader id="LLoaderSystem1"> unexpected by type 'ComponentsType' of element <Components>.
			cvc-type.3.2: Element <Components> is not valid with respect to type definition 'ComponentsType'.
			cvc-elt.5.2.1: The element <Components> is not valid with respect to the actual type definition 'ComponentsType'.

**Comment by wsobel** [comment]
EquipmentTimer is a sample, maybe not the right category, but that is most likely the problem.

**Comment by hulinning2** [comment]
Will, 
Have you got a chance to update the schema for 1.4 yet?

Thanks

**Comment by wsobel** [comment]
I think the issue was you had it as an EVENT and in the standard it is a SAMPLE. Have you checked the category? In the schemas.mtconnect.org <http://schemas.mtconnect.org/> site it is a Sample. Have you checked with the current files? Wanted to make sure before I cut another release.

Thanks,
W

**Comment by hulinning2** [comment]
It is listed as SAMPLE in my devices.xml
            <DataItem type="EQUIPMENT_TIMER" subType="WORKING" category="SAMPLE" id="Lp1ETWorking" nativeUnits="SECOND" units="SECOND" name="p1ETWorking" />
            <DataItem type="EQUIPMENT_TIMER" subType="OPERATING" category="SAMPLE" id="Lp1ETOperating" nativeUnits="SECOND" units="SECOND" name="p1ETOperating" />
            <DataItem type="EQUIPMENT_TIMER" subType="LOADED" category="SAMPLE" id="Lp1ETLoaded" nativeUnits="SECOND" units="SECOND" name="p1ETLoaded" />

However, the subtypes are not valid for EquipmentTimer as shown below

File http://localhost:5000/probe is not valid.
	Value 'WORKING' is not allowed for attribute 'subType'.
		Annotations of type 'DataItemSubEnumType' (see below)
			The sub-types for a measurement
		Error location: MTConnectDevices / Devices / Device / Components / Controller / DataItems / DataItem / @subType
		Details
			cvc-datatype-valid.2.3: For type definition 'DataItemSubEnumType' the string 'WORKING' should be a literal in the lexical space of at least one member of its member type definitions: 'DataItemSubEnumTypeEnum', 'DataItemExtType'.
			cvc-simple-type.2: For type definition 'DataItemSubEnumType' the string 'WORKING' is not valid.
			cvc-attribute.3: Value 'WORKING' of attribute 'subType' does not match simple type definition 'DataItemSubEnumType'.
			cvc-assess-elt.2.1: Assessment of attribute 'subType' failed.
	Value 'OPERATING' is not allowed for attribute 'subType'.
		Annotations of type 'DataItemSubEnumType' (see below)
			The sub-types for a measurement
		Error location: MTConnectDevices / Devices / Device / Components / Controller / DataItems / DataItem / @subType
		Details
			cvc-datatype-valid.2.3: For type definition 'DataItemSubEnumType' the string 'OPERATING' should be a literal in the lexical space of at least one member of its member type definitions: 'DataItemSubEnumTypeEnum', 'DataItemExtType'.
			cvc-simple-type.2: For type definition 'DataItemSubEnumType' the string 'OPERATING' is not valid.
			cvc-attribute.3: Value 'OPERATING' of attribute 'subType' does not match simple type definition 'DataItemSubEnumType'.
			cvc-assess-elt.2.1: Assessment of attribute 'subType' failed.
	Value 'LOADED' is not allowed for attribute 'subType'.
		Annotations of type 'DataItemSubEnumType' (see below)
			The sub-types for a measurement
		Error location: MTConnectDevices / Devices / Device / Components / Controller / DataItems / DataItem / @subType
		Details
			cvc-datatype-valid.2.3: For type definition 'DataItemSubEnumType' the string 'LOADED' should be a literal in the lexical space of at least one member of its member type definitions: 'DataItemSubEnumTypeEnum', 'DataItemExtType'.
			cvc-simple-type.2: For type definition 'DataItemSubEnumType' the string 'LOADED' is not valid.
			cvc-attribute.3: Value 'LOADED' of attribute 'subType' does not match simple type definition 'DataItemSubEnumType'.
			cvc-assess-elt.2.1: Assessment of attribute 'subType' failed.

**Comment by hulinning2** [comment]
Second issue: 

Element <Loader id="LLoaderSystem1"> is not allowed under element <Components>.
		Reason: The following elements are expected at this location (see below)
			'Component'
			'CommonComponent'
			'Device'
			'Controller'
			'Power'
			'Sensor'
			'Path'
			'Actuator'
			'Door'
			'Auxiliaries'
			'Axes'
			'Axis'
			'Linear'
			'Rotary'
			'Spindle'
			'Systems'
			'System'
			'Pneumatic'
			'Hydraulic'
			'Lubrication'
			'Coolant'
			'Electric'
			'Interfaces'
			'Interface'
			'BarFeederInterface'
			'MaterialHandlerInterface'
			'DoorInterface'
			'ChuckInterface'
		Annotations of element 'Components' (see below)
			The sub components
		Annotations of type 'ComponentsType' (see below)
			A list of generic components
		Error location: MTConnectDevices / Devices / Device / Components / Auxiliaries / Components / Loader
		Details
			cvc-complex-type.1.4: Element <Loader id="LLoaderSystem1"> unexpected by type 'ComponentsType' of element <Components>.
			cvc-type.3.2: Element <Components> is not valid with respect to type definition 'ComponentsType'.
			cvc-elt.5.2.1: The element <Components> is not valid with respect to the actual type definition 'ComponentsType'.

**Comment by hulinning2** [comment]
Third issue with current command:

Element <LineLabel> is not allowed under element <Events>.
	Reason: The following elements are expected at this location (see below)
		'Event'
		'Code'
		'Block'
		'Line'
		'PowerStatus'
		'PowerState'
		'PartCount'
		'Direction'
		'Program'
		'Execution'
		'ControllerMode'
		'ToolId'
		'ToolNumber'
		'ToolAssetId'
		'PartId'
		'DoorState'
		'RotaryMode'
		'ActiveAxes'
		'CoupledAxes'
		'AxesCoupling'
		'Message'
		'EmergencyStop'
		'Availability'
		'ActuatorState'
		'PathMode'
		'LinePowerState'
		'ControlPowerState'
		'AssetChanged'
		'AssetRemoved'
		'WorkholdingId'
		'ChuckState'
		'EndOfBar'
		'AxisInterlock'
		'ChuckInterlock'
		'AxisState'
		'PathFeedrateOverride'
		'AxisFeedrateOverride'
		'RotaryVelocityOverride'
		'PartAssetId'
		'FunctionalMode'
		'PalletId'
		'ProgramComment'
		'ProgramHeader'
		'OperatorId'
		'ProgramEdit'
		'ProgramEditName'
		'PartCountDiscrete'
		'ToolIdDiscrete'
		'ToolNumberDiscrete'
		'ToolAssetIdDiscrete'
		...
	Annotations of element 'Events' (see below)
		A collection of events
	Annotations of type 'EventsType' (see below)
		A collection of events and alarms for this component
	Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Events / LineLabel
	Details
		cvc-complex-type.1.4: Element <LineLabel> unexpected by type 'EventsType' of element <Events>.
		cvc-type.3.2: Element <Events> is not valid with respect to type definition 'EventsType'.
		cvc-elt.5.2.1: The element <Events> is not valid with respect to the actual type definition 'EventsType'.

**Comment by wsobel** [comment]
Do you have the xml for this issue? Please attach.

**Comment by hulinning2** [comment]
Here is the devices.xml for 1.4 spec
[Devices.zip](https://github.com/mtconnect/cppagent/files/4027674/Devices.zip)
Thanks

**Comment by wsobel** [comment]
Changed have been made to the schema files in http://schemas.mtconnect.org

**Comment by hulinning2** [comment]
Issue is fixed for Equipment_Timer in 1.4 spec
