### ISSUE TITLE
Line Number is not valid in schema 1.4

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#143]
File http://localhost:5000/current is not valid.
	Element <LineNumber> is not allowed under element <Events>.
		Reason: The following elements are expected at this location (see below)
			'Variables'
			'Macman'
			'InputSignal'
			'OutputSignal'
			'InputOutputSignal'
			'BlockNumber'
			'Event'
			'Code'
			'Block'
			'Line'
			'PowerStatus'
			'PowerState'
			'PartCount'
			'Direction'
			'Program'
			'Execution'
			'ControllerMode'
			'ToolId'
			'ToolNumber'
			'ToolAssetId'
			'PartId'
			'DoorState'
			'RotaryMode'
			'ActiveAxes'
			'CoupledAxes'
			'AxesCoupling'
			'Message'
			'EmergencyStop'
			'Availability'
			'ActuatorState'
			'PathMode'
			'LinePowerState'
			'ControlPowerState'
			'AssetChanged'
			'AssetRemoved'
			'WorkholdingId'
			'ChuckState'
			'EndOfBar'
			'AxisInterlock'
			'ChuckInterlock'
			'AxisState'
			'PathFeedrateOverride'
			'AxisFeedrateOverride'
			'RotaryVelocityOverride'
			'PartAssetId'
			'FunctionalMode'
			'PalletId'
			'ProgramComment'
			'ProgramHeader'
			'OperatorId'
			...
		Annotations of element 'Events' (see below)
			A collection of events
		Annotations of type 'EventsType' (see below)
			A collection of events and alarms for this component
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Events / LineNumber
		Details
			cvc-complex-type.1.4: Element <LineNumber> unexpected by type 'EventsType' of element <Events>.
			cvc-type.3.2: Element <Events> is not valid with respect to type definition 'EventsType'.
			cvc-elt.5.2.1: The element <Events> is not valid with respect to the actual type definition 'EventsType'.

**Comment by wsobel** [comment]
Added line number. In schemas.

**Comment by hulinning2** [comment]
Fixed
