### ISSUE TITLE
/current Loads Empty Page With Single Bar

### ISSUE THREAD

**Issue by dkiktenko** [mtconnect/cppagent#144]
Working with Release 1.5.0.14 (x32 build), Agent's /current page is loading an empty page with a single horizontal bar at the top on localhost (Windows 10).

![MTConnect Agent Current Page](https://user-images.githubusercontent.com/11392386/72273954-ecd49780-35f0-11ea-93d7-c8ccb541295f.png)

However, using the same files and folder structure (i.e. agent.cfg, devices.xml, schema, etc.) on either a Windows 7 or Windows 10 VM, results in the styled page loading without issue.

![MTConnect Agent Current Page 2](https://user-images.githubusercontent.com/11392386/72274454-d5e27500-35f1-11ea-84b6-8d08655ac77b.png)

**Comment by wsobel** [comment]
Did you check to see if the source is correct? Check the process header and if the xslt file is present. 

(Sent from mobile)

**Comment by dkiktenko** [comment]
Yes, source is correct (raw xml is populating correct data).
No .xslt file is present in any of the Agents (2/3 are producing /current's page).

What would I be looking for in the header?

**Comment by wsobel** [comment]
Xslt process instruction. Most likely the file is not registered in the config correctly. 

(Sent from mobile)

**Comment by dkiktenko** [comment]
Sorry - I may not be 100% familiar with all that you are referencing.

Using the same /schemas/, /styles/, and /tools/ files that were distributed with the 1.5.0.14 release.
Only changes made were to the agent.cfg file (which is the same across all 3 OS instances where I am testing):

```
Devices = ../simulator/VMC-3Axis.xml
SchemaVersion = 1.5

Adapters {
   VMC-3Axis {
      Host = 127.0.0.1
      Port = 7878
   } 
}

Files {
    schemas {
        Path = ../schemas
        Location = /schemas/
    }
    styles {
        Path = ../styles
        Location = /styles/
    }
    Favicon {
        Path = ../styles/favicon.ico
        Location = /favicon.ico
    }
}
StreamsStyle {
  Location = /styles/Streams.xsl
}
# Logger Configuration
logger_config
{
    logging_level = debug
}
```




Would expect any configuration issues to show up in the debug instance, but no such warnings/errors are logged below:




```
Configuration search path: current directory and C:\Program Files (x86)\MTConnect Agent\bin\
MTConnect Agent Version 1.5.0.14 - built on Fri Dec 20 14:08:19 2019
    4 DEBUG [0] init.config: Checking for Devices XML configuration file: ../simulator/VMC-3Axis.xml
    4 DEBUG [0] init.config:   Stat returned: 0
    5 INFO  [0] init.config: Starting agent on port 5000
  108 INFO  [0] init.config: Adding adapter for VMC-3Axis on 127.0.0.1:7878
  109 DEBUG [0] agent: registerFile: Path ../styles/favicon.ico is not a directory: Unable to find directory ../styles/favicon.ico, trying as a file
  111 DEBUG [1] input.connector: Connecting to data source: 127.0.0.1 on port: 7878
  112 DEBUG [1] input.connector: (Port:58904)Sending initial PING
  113 DEBUG [1] input.connector: (Port:58904)Received a PONG for 127.0.0.1 on port 7878
  114 DEBUG [1] input.connector: (Port:58904)    Time since last heartbeat: 0ms
  115 DEBUG [1] input.connector: (Port:58904)Received PONG, starting heartbeats every 10000ms
 6274 DEBUG [2] agent: Request: GET /current from 127.0.0.1:58916
 6296 DEBUG [3] agent: Request: GET /favicon.ico from 127.0.0.1:58917
10115 DEBUG [1] input.connector: (Port:58904)Sending a PING for 127.0.0.1 on port 7878
10116 DEBUG [1] input.connector: (Port:58904)Received a PONG for 127.0.0.1 on port 7878
10117 DEBUG [1] input.connector: (Port:58904)    Time since last heartbeat: 10003ms
```

**Comment by hulinning2** [comment]
you need to make sure that style is using 1.5 spec

**Comment by dkiktenko** [comment]
> you need to make sure that style is using 1.5 spec

How can I confirm that?

**Comment by hulinning2** [comment]
check the streams.xsl

<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:m="urn:mtconnect.org:MTConnectStreams:1.5" >
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">

**Comment by dkiktenko** [comment]
Yep - that's at the top of the Streams.xsl file

Just inspected the element for all of the Agents and I see that the Agent that does NOT load the /current page returns the following:

![Windows 10 Agent Header](https://user-images.githubusercontent.com/11392386/72289518-ece48f80-3610-11ea-9777-f98c90b62421.png)

Whereas the Agent that IS loading the /current page, is returning the following:
![Windows 10 2 Agent Header](https://user-images.githubusercontent.com/11392386/72289537-f4a43400-3610-11ea-9c92-04d424c3a1e9.png)

Hopefully this helps.

**Comment by dkiktenko** [comment]
For reference, here are the contents of the Streams.xsl file that's under ../schemas/ folder:

````
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:m="urn:mtconnect.org:MTConnectStreams:1.5" >
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
			<head>
				<title>MTConnect Device Streams</title>
				<link type="text/css" href="/styles/Streams.css" media="screen" rel="stylesheet"/>
			</head>
			<body>
				<p>
					<xsl:apply-templates select="/m:MTConnectStreams/m:Header" />
				</p>
				<hr/>
				<xsl:apply-templates select="/m:MTConnectStreams/m:Streams/m:DeviceStream" />
			</body>
	</xsl:template>
	
	<xsl:template match="m:DeviceStream">
		<h2>Device: <xsl:value-of select="@name"/>
		<xsl:text>; UUID: </xsl:text><xsl:value-of select="@uuid"/>
		</h2>
		<xsl:apply-templates select="m:ComponentStream"/>
	</xsl:template>
	
	<xsl:template match="m:Header">
		<ul>
			<xsl:for-each select="@*">
				<li>
					<xsl:value-of select="name()"/>
					<xsl:text>: </xsl:text>
					<xsl:value-of select="." />
				</li>
			</xsl:for-each>
		</ul>
	</xsl:template>
	
	<xsl:template match="m:ComponentStream">
		<h3>
			<xsl:value-of select="@component" />
			<xsl:text> : </xsl:text>
			<xsl:value-of select="@name" />
		</h3>
		<xsl:apply-templates select="	m:Samples"/>
		<xsl:apply-templates select="	m:Events"/>
		<xsl:apply-templates select="	m:Condition"/>
	</xsl:template>
	
	<xsl:template match="*">
		<p><xsl:value-of select="name()"/></p>
		<table border="1px">
			<thead>
				<th>Timestamp</th><th>Type</th><th>Sub Type</th><th>Name</th><th>Id</th>
				<th>Sequence</th><th>Value</th>
			</thead>
			<tbody>
				<xsl:for-each select="*">
					<tr>
						<td><xsl:value-of select="@timestamp"/></td>
						<td><xsl:value-of select="name()"/></td>
						<td><xsl:value-of select="@subType"/></td>
						<td><xsl:value-of select="@name"/></td>
						<td><xsl:value-of select="@dataItemId"/></td>
						<td><xsl:value-of select="@sequence"/></td>
						<td><xsl:value-of select="."/></td>
					</tr>
				</xsl:for-each>
			</tbody>
		</table>
	</xsl:template>
	
</xsl:stylesheet>
```

**Comment by wsobel** [comment]
I’ll fix the xslt. Thanks Linh. - W

(Sent from mobile)

**Comment by dkiktenko** [comment]
Just updating to close the issue out - restarting PC somehow resolved the issue.
Agent is working fine without issues.
