### ISSUE TITLE
WebSocket 

### ISSUE THREAD

**Issue by dan0st** [mtconnect/cppagent#145]
Is it possible to use web socket between agent and client instead of http request?

**Comment by wsobel** [comment]
Currently we do not support websockets. There is a task to update the server to boost beast and provide websockets. We would appreciate any help with getting that task completed. 

Thanks
W

(Sent from mobile)

**Comment by dan0st** [comment]
Ok, understood. I try to use mtconnect for cnc systems monitoring, and it will be very nice to have websocket implementation. Where i can find something like "agent implementation manual", because I have only been able to find "Adapter implementation manual"? 
Thanks for your reply!

**Comment by wsobel** [comment]
The agent implants the MTConnect standard. So the manual is the standard. 

Part one describes the protocol. 

If you would be interested in contributing to the open source project, it would be greatly appreciated. 



(Sent from mobile)

**Comment by wsobel** [comment]
The latest version in development will address TLS and WebSockets. Would be interested in what websockets pub/sub protocol you would suggest. We are using boost beast so this is now possible.

**Comment by wsobel** [comment]
The new agent (2.0) in the cppagent_dev repo (private) is addressing new protocol requirements. If you would like access please get back.
