### ISSUE TITLE
Updating data

### ISSUE THREAD

**Issue by dan0st** [mtconnect/cppagent#147]
how to make agent mtconnect update the XML page in case of data changes. I remember that there is such a possibility.

**Comment by wsobel** [comment]
The data can stream using x multipart replace by putting a query parameter of interval=<ms> where <ms> is the time between pushes. 

(Sent from mobile)

**Comment by dan0st** [comment]
Something like this - "http://localhost:5000/stream?interval=1000" ?

**Comment by wsobel** [comment]
http://localhost:5000/sample?interval=1000 

To send samples every second. 

Also works with current, but less useful. 

(Sent from mobile)

**Comment by dan0st** [comment]
But it's no working(( 
![err](https://user-images.githubusercontent.com/37585195/73282416-a98a4380-4202-11ea-8fb9-6e8c43683000.png)

**Comment by wsobel** [comment]
This may be an issue with the user agent. 

(Sent from mobile)

**Comment by dan0st** [comment]
i tried new agent release, and this problem gone, but in my browser i still see just black screen.
![image](https://user-images.githubusercontent.com/37585195/73295689-33450b80-4219-11ea-9e30-4e8ede338138.png)

**Comment by diamondadam** [comment]
Hi, did you ever figure out how to fix the black screen? I appear to have run into the same issue.

**Comment by wsobel** [comment]
It should be fixed. See if when you view source if the data is there? Or if the doc was downloaded. 

(Sent from mobile)

**Comment by diamondadam** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/22235340/105257017-df7fb080-5b54-11eb-864e-60da6f928684.png)

Unfortunately it isn't downloading anything or sending any data. I've even tried other browsers and devices.

**Comment by diamondadam** [comment]
I used curl instead of a browser and everything worked perfect. So, I'm thinking the browser may be the issue.

**Comment by wsobel** [comment]
I’ll check the content type and make sure it’s corrected. 

(Sent from mobile)
