### ISSUE TITLE
Unable to clone cppagent_dev.git

### ISSUE THREAD

**Issue by philipslack** [mtconnect/cppagent#148]
Attempting to follow instructions for cppagent/unix but uable to clone from github.
Have ssh key installed but command "git clone git@github.com:mtconnect/cppagent_dev.git" returns

ERROR:  Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.

Has that repository been moved or deleted?
Thank you.

**Comment by wsobel** [comment]
Repo is fine. My guess is your ssh agent is not running and communicating the key. If it is password protected you will need to run the agent in the background. 

Best
W

(Sent from mobile)

**Comment by philipslack** [comment]
Maybe I'm missing something or should have realized this immediately, but
the step-by-step instructions for unix include the lines:

$ git clone git@github.com:mtconnect/cppagent_dev.git
$ cd cppagent_dev

Using 'cppagent.git' works, but I could not get 'cppagent_dev.git' to
work.     Could be a typo in the instructions, or I'm missing something.
Just
wanted to let you know.   I'm progressing now...
Thanks,
Phil

**Comment by wsobel** [comment]
Hi Phil,

Dev is a private repo that contains wip items from the MTConnect standard. I can add you to the access list if you have joined the standards committee.  There is no fee, but we require you sign an IP agreement that insures that the information contained in pre-published work will not be claimed. 

Are you a member of the SC? The cppagent and the Dev versions are very close. There are a few new features in development. 

Best
W

(Sent from mobile)

**Comment by philipslack** [comment]
Hi William,
 No, I am not a member of the SC.  I don't have a problem signing an IP
agreement, but also don't have the expertise to add to the discussion.  I'm
sure the standard
version is fine for me - no need to get the development version.  But thank
you for making me aware of the difference.  If it seems like I can
contribute in the future I'll apply
to join the SC.  And thanks for your help.
-Phil

**Comment by wsobel** [comment]
Have you applied to the SC? If so, I can give you access.

**Comment by efreeman74** [comment]
wsobel
I have the same issues as Phil is having, but I want to install the software on a unix system and not windows, but is there a binary for unix or do I need the dev kit to run on CentOS system?

**Comment by wsobel** [comment]
see the unix sub-directory for build instructions. just clone, run cmake and build.

for centos you would use yum. may need to find equivalent packages as the deb packages.

Best,
W

**Comment by efreeman74** [comment]
Thanks William

I see the unix subdirectory and the README.md file, I can see the instructions but the line with the clone.


I am using the command >>  git clone git@github.com:mtconnect/cppagent_dev<mailto:git@github.com:mtconnect/cppagent_dev>



Is this correct?


[cid:image001.png@01D67AEA.941FB450]


I also have a screen shot of the instructions below:

[cid:image002.png@01D67AEA.941FB450]

Elton L. Freeman
Research Physicists
Engineering Research and Development Center
Information Technology Lab, Building 8000
Cell 1-706-266-9335
Office 1-601-634-2419

**Comment by wsobel** [comment]
you can use either form for clone. git@… or https. Either works.

best,
W

**Comment by efreeman74** [comment]
William

It does work, but I don’t have permission to access the dev files?  Not sure why



Elton L. Freeman
Research Physicists
Engineering Research and Development Center
Information Technology Lab, Building 8000
Cell 1-706-266-9335
Office 1-601-634-2419

**Comment by wsobel** [comment]
not sure what you mean by the dev files?

**Comment by efreeman74** [comment]
Unix systems require the development files…..





Elton L. Freeman
Research Physicists
Engineering Research and Development Center
Information Technology Lab, Building 8000
Cell 1-706-266-9335
Office 1-601-634-2419

**Comment by wsobel** [comment]
I'm still unclear what you are asking. I understand the need to install dependencies and the compiler for applications on *NIX; I build on Mac OS and Appveyor runs a full build/test on Ubuntu and Windows. We don't build *NIX binaries because of the number of variants and it's pretty easy to build at no additional cost. 

In Ubuntu, we use apt-get command to load the dependencies. I have not built on CentOS and I'm not sure of the equivalent CentOS yum packages. The agent doesn't depend on anything special, so it should be easy to get the system dependencies. 

please be more specific.

- W

**Comment by efreeman74** [comment]
William

I think the issue I’m having it permissions/access rights.

the Reame.md file under unix subdirectory, has the following command

 git clone git@github.com:mtconnect/cppagent_dev.git<mailto:git@github.com:mtconnect/cppagent_dev.git>



when I run the command, it finds the cppagent_dev but my error is in access rights?  Is it available to the public?







ITLELF-MN-1279G:unix rditlelf$ git clone git@github.com:mtconnect/cppagent_dev.git

Cloning into 'cppagent_dev'...

Permission denied (publickey).

fatal: Could not read from remote repository.



Please make sure you have the correct access rights

and the repository exists.

ITLELF-MN-1279G:unix rditlelf$




Can you give me a call at 1-706-266-9335 ?

Elton L. Freeman
Research Physicists
Engineering Research and Development Center
Information Technology Lab, Building 8000
Cell 1-706-266-9335
Office 1-601-634-2419

**Comment by wsobel** [comment]
There is no mailto. also, use the public version with http:

    git clone https://github.com/mtconnect/cppagent.git

**Comment by efreeman74** [comment]
William

Good news, I did get mtconnect v1.6 to compile and build on Ubuntu 18.04 LTS, using CMAKE v3.17.3 and GCC 7.5, along with the other suggested installs from the instructions.  I wrote a medium length script (bash) now that builds everything for me…

I may also try to get this going on my CentOS 7 compute node as well, I’ll let you know how this turns out.

I used the cppagent as you mentioned to from previous reply, and I used the following commands to check the status, I did need to start the agent first before doing the probe and current or

Sudo agent

sudo curl -v http://localhost:5000/probe

sudo curl -v http://localhost:5000/current



and I got a lot of data that appears to be passed in communication, see below,



Case solved, thanks for you’re help






elton@samsonite:~/Documents/mtconnect_v1.6$ sudo curl -v http://localhost:5000/current
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /current HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.58.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Length: 8068
< Content-Type: text/xml
<
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/styles/Streams.xsl"?>
<MTConnectStreams xmlns:m="urn:mtconnect.org:MTConnectStreams:1.5" xmlns="urn:mtconnect.org:MTConnectStreams:1.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mtconnect.org:MTConnectStreams:1.5 /schemas/MTConnectStreams_1.5.xsd">
  <Header creationTime="2020-09-01T21:34:51Z" sender="samsonite" instanceId="1598996011" version="1.6.0.7" bufferSize="131072" nextSequence="17445" firstSequence="1" lastSequence="17444"/>
  <Streams>
    <DeviceStream name="VMC-3Axis" uuid="000">
      <ComponentStream component="Rotary" name="C" componentId="c1">
        <Samples>
          <SpindleSpeed dataItemId="c2" timestamp="2020-09-01T21:33:31.839129Z" name="Sspeed" sequence="13" subType="ACTUAL">UNAVAILABLE</SpindleSpeed>
          <SpindleSpeed dataItemId="c3" timestamp="2020-09-01T21:33:31.839129Z" name="Sovr" sequence="14" subType="OVERRIDE">UNAVAILABLE</SpindleSpeed>
          <Load dataItemId="cl3" timestamp="2020-09-01T21:33:31.839129Z" name="Cload" sequence="15">UNAVAILABLE</Load>
        </Samples>
        <Events>
          <RotaryMode dataItemId="cm" timestamp="2020-09-01T21:33:31.839129Z" name="Cmode" sequence="18">SPINDLE</RotaryMode>
        </Events>
        <Condition>
          <Unavailable dataItemId="Cloadc" timestamp="2020-09-01T21:33:31.839129Z" sequence="1" type="LOAD"/>
          <Unavailable dataItemId="Csystem" timestamp="2020-09-01T21:33:31.839129Z" sequence="2" type="SYSTEM"/>
        </Condition>
      </ComponentStream>
      <ComponentStream component="Controller" name="controller" componentId="cn1">
        <Events>
          <EmergencyStop dataItemId="estop" timestamp="2020-09-01T21:33:31.839129Z" sequence="29">UNAVAILABLE</EmergencyStop>
          <Message dataItemId="msg" timestamp="2020-09-01T21:33:31.839129Z" sequence="35">UNAVAILABLE</Message>
        </Events>
        <Condition>
          <Unavailable dataItemId="clp" timestamp="2020-09-01T21:33:31.839129Z" sequence="17" type="LOGIC_PROGRAM"/>
          <Unavailable dataItemId="motion" timestamp="2020-09-01T21:33:31.839129Z" sequence="34" type="MOTION_PROGRAM"/>
          <Unavailable dataItemId="system" timestamp="2020-09-01T21:33:31.839129Z" sequence="38" type="SYSTEM"/>
        </Condition>
      </ComponentStream>
      <ComponentStream component="Coolant" name="coolant" componentId="cool">
        <Condition>
          <Unavailable dataItemId="clow" timestamp="2020-09-01T21:33:31.839129Z" sequence="16" type="LEVEL"/>
          <Unavailable dataItemId="coolantmotor" timestamp="2020-09-01T21:33:31.839129Z" sequence="25" type="ACTUATOR"/>
          <Unavailable dataItemId="coolpres" timestamp="2020-09-01T21:33:31.839129Z" sequence="26" type="PRESSURE"/>
          <Unavailable dataItemId="filter" timestamp="2020-09-01T21:33:31.839129Z" sequence="30" type="x:FILTER"/>
        </Condition>
      </ComponentStream>
      <ComponentStream component="Device" name="VMC-3Axis" componentId="dev">
        <Events>
          <Availability dataItemId="avail" timestamp="2020-09-01T21:33:31.839129Z" sequence="12">UNAVAILABLE</Availability>
          <AssetChanged dataItemId="dev_asset_chg" timestamp="2020-09-01T21:33:31.839129Z" sequence="27" assetType="">UNAVAILABLE</AssetChanged>
          <AssetRemoved dataItemId="dev_asset_rem" timestamp="2020-09-01T21:33:31.839129Z" sequence="28" assetType="">UNAVAILABLE</AssetRemoved>
        </Events>
      </ComponentStream>
      <ComponentStream component="Electric" name="electric" componentId="el">
        <Events>
          <PowerState dataItemId="p2" timestamp="2020-09-01T21:33:31.839129Z" name="power" sequence="37">UNAVAILABLE</PowerState>
        </Events>
      </ComponentStream>
      <ComponentStream component="Hydraulic" name="hydrolic" componentId="hsys">
        <Condition>
          <Unavailable dataItemId="hlow" timestamp="2020-09-01T21:33:31.839129Z" sequence="31" type="LEVEL"/>
          <Unavailable dataItemId="hpres" timestamp="2020-09-01T21:33:31.839129Z" sequence="32" type="PRESSURE"/>
          <Unavailable dataItemId="htemp" timestamp="2020-09-01T21:33:31.839129Z" sequence="33" type="TEMPERATURE"/>
        </Condition>
      </ComponentStream>
      <ComponentStream component="Path" name="path" componentId="pth">
        <Samples>
          <PathFeedrate dataItemId="Fovr" timestamp="2020-09-01T21:33:31.839129Z" sequence="3">UNAVAILABLE</PathFeedrate>
          <PathFeedrate dataItemId="Frt" timestamp="2020-09-01T21:34:51.454497Z" sequence="17416">0.4</PathFeedrate>
          <PathPosition dataItemId="Ppos" timestamp="2020-09-01T21:33:31.839129Z" sequence="5" subType="ACTUAL">UNAVAILABLE</PathPosition>
        </Samples>
        <Events>
          <Block dataItemId="cn2" timestamp="2020-09-01T21:34:51.442137Z" name="block" sequence="17411">X-0.805956 Y0.114156</Block>
          <ControllerMode dataItemId="cn3" timestamp="2020-09-01T21:33:31.839129Z" name="mode" sequence="20">UNAVAILABLE</ControllerMode>
          <Line dataItemId="cn4" timestamp="2020-09-01T21:34:51.442137Z" name="line" sequence="17406">600</Line>
          <Program dataItemId="cn5" timestamp="2020-09-01T21:33:31.839129Z" name="program" sequence="22">UNAVAILABLE</Program>
          <Execution dataItemId="cn6" timestamp="2020-09-01T21:33:31.839129Z" name="execution" sequence="23">UNAVAILABLE</Execution>
          <ToolId dataItemId="cnt1" timestamp="2020-09-01T21:33:31.839129Z" name="tool_id" sequence="24">UNAVAILABLE</ToolId>
        </Events>
      </ComponentStream>
      <ComponentStream component="Linear" name="X" componentId="x1">
        <Samples>
          <Load dataItemId="n3" timestamp="2020-09-01T21:33:31.839129Z" name="Xload" sequence="36">UNAVAILABLE</Load>
          <Position dataItemId="x2" timestamp="2020-09-01T21:34:51.588979Z" name="Xact" sequence="17441" subType="ACTUAL">-0.8084387779</Position>
          <Position dataItemId="x3" timestamp="2020-09-01T21:34:51.588979Z" name="Xcom" sequence="17443" subType="COMMANDED">-0.8074731291</Position>
        </Samples>
        <Condition>
          <Unavailable dataItemId="Xloadc" timestamp="2020-09-01T21:33:31.839129Z" sequence="6" type="LOAD"/>
          <Unavailable dataItemId="Xsystem" timestamp="2020-09-01T21:33:31.839129Z" sequence="7" type="SYSTEM"/>
        </Condition>
      </ComponentStream>
      <ComponentStream component="Linear" name="Y" componentId="y1">
        <Samples>
          <Position dataItemId="y2" timestamp="2020-09-01T21:34:51.588979Z" name="Yact" sequence="17442" subType="ACTUAL">0.0927019939</Position>
          <Position dataItemId="y3" timestamp="2020-09-01T21:34:51.588979Z" name="Ycom" sequence="17444" subType="COMMANDED">0.1010463078</Position>
          <Load dataItemId="y4" timestamp="2020-09-01T21:33:31.839129Z" name="Yload" sequence="43">UNAVAILABLE</Load>
        </Samples>
        <Condition>
          <Unavailable dataItemId="Yloadc" timestamp="2020-09-01T21:33:31.839129Z" sequence="8" type="LOAD"/>
          <Unavailable dataItemId="Ysystem" timestamp="2020-09-01T21:33:31.839129Z" sequence="9" type="SYSTEM"/>
        </Condition>
      </ComponentStream>
      <ComponentStream component="Linear" name="Z" componentId="z1">
        <Samples>
          <Position dataItemId="z2" timestamp="2020-09-01T21:33:31.839129Z" name="Zact" sequence="44" subType="ACTUAL">UNAVAILABLE</Position>
          <Position dataItemId="z3" timestamp="2020-09-01T21:33:31.839129Z" name="Zcom" sequence="45" subType="COMMANDED">UNAVAILABLE</Position>
          <Load dataItemId="z4" timestamp="2020-09-01T21:33:31.839129Z" name="Zload" sequence="46">UNAVAILABLE</Load>
        </Samples>
        <Condition>
          <Unavailable dataItemId="Zloadc" timestamp="2020-09-01T21:33:31.839129Z" sequence="10" type="LOAD"/>
          <Unavailable dataItemId="Zsystem" timestamp="2020-09-01T21:33:31.839129Z" sequence="11" type="SYSTEM"/>
        </Condition>
      </ComponentStream>
    </DeviceStream>
  </Streams>
</MTConnectStreams>
* Closing connection 0




Elton L. Freeman
Research Physicists
Engineering Research and Development Center
Information Technology Lab, Building 8000
Cell 1-706-266-9335
Office 1-601-634-2419

**Comment by wsobel** [comment]
The ubuntu script should be very small, just a couple of cmake commands similar to what you see in the appveyor script. you do need to do a single apt-get to make sure you have the base build dependencies. 

Please send the scripts. We can merge them into the unix folder for others.

Best,
W

**Comment by efreeman74** [comment]
William

Sure, I should have my script ready for review, hopefully next week.

I did see one warning with compilation, so I’ll try to add some details about my compilation experience so other can benefit or some suggestions.


Cheers


Elton L. Freeman
Research Physicists
Engineering Research and Development Center
Information Technology Lab, Building 8000
Cell 1-706-266-9335
Office 1-601-634-2419

**Comment by skibum1869** [comment]
@efreeman74 if you need a reference file for how to compile in Linux or just want to run a docker container with the files see [https://github.com/skibum1869/MTConnect_Docker](https://github.com/skibum1869/MTConnect_Docker) and [https://hub.docker.com/r/skibum1869/mtconnect_docker_agent](https://hub.docker.com/r/skibum1869/mtconnect_docker_agent) or the docker agent @NeilDes is currently working on [https://hub.docker.com/r/mtcguru/mtcagent](https://hub.docker.com/r/mtcguru/mtcagent)
