### ISSUE TITLE
setting the logger to use cout does not work

### ISSUE THREAD

**Issue by dwcanillas-pl** [mtconnect/cppagent#152]
If I specify this as my logger section in agent.cfg:
```
# Logger Configuration
logger_config
{
    logging_level = trace
    output = cout
}
```
The output is still directed to a log file:

![image](https://user-images.githubusercontent.com/70032400/90921090-22273c00-e3af-11ea-9598-f0080698ee30.png)

**Comment by wsobel** [comment]
Is this still an issue?

**Comment by wsobel** [comment]
Got no response, so closing the issue.
