### ISSUE TITLE
Sysinternals tools in repo have a different license to the Apache 2.0 license provided

### ISSUE THREAD

**Issue by JamesBroadberry** [mtconnect/cppagent#154]
In the folder [cppagent/install/Windows/src/x64/](https://github.com/mtconnect/cppagent/tree/master/install/Windows/src/x64) there's a Sysinternals tool called "Dbgview.exe"

As far as I'm aware, it's using the [Sysinternals license](https://docs.microsoft.com/en-us/sysinternals/license-terms).

Could this conflict with the Apache 2.0 license provided?
Could this cause legal issues with redistributing cppagent under the Apache 2.0 license?

Sorry if any of the terminology is wrong - I'm not that familiar with these types of licensing situations.

Thanks,
James

**Comment by SimonL101** [comment]
Hi there,
Same question from me. Can we redistribute as is? It does look like there is a conflict between the licenses.
Thanks

**Comment by wsobel** [comment]
I will take a look at it. This is an old installer and I have not supported it in a while.

My suggestion is to remove it. We can move it to another project if that makes redist easier. I do not bundle with the releases.

**Comment by SimonL101** [comment]
Hi Will,
Thanks for taking a look. We didn't realise it wasn't supported any more. Having an installer is convenient for distribution of the agent and the sysinternal tool didn't look like it was required and could likely be removed. If the answer is that there isn't a supported installer we'll look at building our own.

**Comment by wsobel** [comment]
I have created one in the past, but demand was not great enough. If you would be interested in contributing one, that would be great. 

(Sent from mobile)
