### ISSUE TITLE
Agent Timing Out On Adapter Connection

### ISSUE THREAD

**Issue by dkiktenko** [mtconnect/cppagent#155]
Noticing an issue where the Agent is dropping the connection on the Adapter. Looking at the Agent's log files, there are a lot of error-severity messages stating:

> Did not receive heartbeat for over: <timeout x 2>
> Connection exited with status: <status return value>

Yet, in many scenarios, the status return value is >0 (actual # of bytes returned by read method), because the Adapter is providing a return with a stream of data.

Wouldn't be so problematic if it happens once or twice, but this can happen back-to-back (i.e. Agent drops connection, reconnects, drops the connection again), resulting in the Agent's clients seeing none of the Adapter's data.

Is there any solution other than increasing the Adapter's timeout value?

**Comment by wsobel** [comment]
The agent expects to receive either a response to a periodic ping or some sign of life from the adapter.

This is usually because the heartbeat stops. 

Are you certain the adapter is sending data to the agent?

**Comment by dkiktenko** [comment]
Hi Will,

Yes - the Adapter is sending out data.

In one instance where I am looking at both the Adapter and Agent logs, I see that the Adapter sets the timeout to 20000 ms.
The Adapter takes 22 seconds to gather data and either provide a heartbeat or send changed data.

Looking at the Adapter log file, I highlight a snippet of events:

- 2020-09-23T14:29:15.895255Z - Adapter recognizes that there are no clients listening
- 2020-09-23T14:29:22.004658Z - Adapter accepts new client connection (port **52922**)
- 2020-09-23T14:29:22.004658Z - Adapter starts next scan cycle
- 2020-09-23T14:29:42.504732Z - Adapter finished scan cycle [and sends data to listening/previously listening Clients]
- 2020-09-23T14:29:42.504732Z - Adapter starts next scan cycle
- 2020-09-23T14:30:05.082937Z - Adapter finished scan cycle [and sends data to listening/previously listening Clients]
- 2020-09-23T14:30:06.098556Z - Adapter recognizes that there are no clients listening
- 2020-09-23T14:30:13.208000Z - Adapter accepts new client connection (port **53891**)
- 2020-09-23T14:30:13.208000Z - Adapter starts next scan cycle
- 2020-09-23T14:30:36.192411Z - Adapter finished scan cycle [and sends data to listening/previously listening Clients]
- 2020-09-23T14:30:36.192411Z - Adapter starts next scan cycle
- 2020-09-23T14:30:58.239392Z - Adapter finished scan cycle [and sends data to listening/previously listening Clients]
- 2020-09-23T14:30:59.254997Z - Adapter recognizes that there are no clients listening
- 2020-09-23T14:31:06.364552Z - Adapter accepts new client connection (port 54959)

Unfortunately, the attached Agent log file is only set to "info" logging severity, so the only messages available are regarding when the Agent drops the connection. But, matching to the timestamp of the Adapter, there are the following:

- 2020-09-23T14:30:02.0504Z: ERROR [2] input.connector: (Port:**52922**)connect: Did not receive heartbeat for over: 40000
- 2020-09-23T14:30:02.0504Z: ERROR [2] input.connector: (Port:52922)connect: Connection exited with status: -1
- 2020-09-23T14:30:56.0192Z: ERROR [2] input.connector: (Port:**53891**)connect: Did not receive heartbeat for over: 40000
- 2020-09-23T14:30:56.0192Z: ERROR [2] input.connector: (Port:53891)connect: Connection exited with status: -1

So... the 52922 is dropped at 14:30:02, even though the Adapter sent heartbeat/data at 14:29:42 - exactly 20 seconds after it has received data. Not 40 seconds, as the "heartbeat" timeout would indicate.

Same for the 53891 connection. It is dropped at 14:30:56, but the Adapter sent heartbeat/data at 14:30:36 - again, exactly 20 seconds after it received data.

Thus, the issue appears is that the Agent isn't waiting for [2 x timeout], but just the [timeout] value.

And, other instances, we have the Agent reporting the same, where status is >0:

- 2020-09-23T13:17:59.0581Z: ERROR [2] input.connector: (Port:65265)connect: Did not receive heartbeat for over: 40000
- 2020-09-23T13:17:59.0581Z: ERROR [2] input.connector: (Port:65265)connect: Connection exited with status: **13**
- 2020-09-23T13:19:10.0926Z: ERROR [2] input.connector: (Port:51426)connect: Did not receive heartbeat for over: 40000
- 2020-09-23T13:19:10.0926Z: ERROR [2] input.connector: (Port:51426)connect: Connection exited with status: **13**

But, when looking at the Adapter - it sent data < 20 seconds before the Agent's timeout.

Note: the >0 status value varies, it isn't always 13, just in this example.

[agent.log](https://github.com/mtconnect/cppagent/files/5305936/agent.log)

**Comment by wsobel** [comment]
The reason is it waited 22 seconds to respond to a 10 second heartbeat. It needs to respond within 20 seconds. If the adapter is properly following the protocol, it needs to respond in the allotted time, otherwise the agent will think it has died. This is to prevent adapters that hang or network disruptions from incorrectly reporting data that is stale. 

Why is the adapter not responding after it receives the heartbeat? It should respond with a * PONG 10000 immediately. 

(Sent from mobile)

**Comment by dkiktenko** [comment]
Does the Agent not adhere to the timeout value set by the Adapter, when the Agent initially connects to the Adapter, as described in [Protocol](https://github.com/mtconnect/cppagent#protocol)?

Because, in that scenario, timeout is set to 20000.

**Comment by wsobel** [comment]
Yes, the agent adheres to the adapter timeout.

Best,
W

**Comment by dkiktenko** [comment]
So - if the Agent adheres to the timeout value set by the Adapter, which in the current scenario is set to 20000 ms, and the Adapter provided a response in 22000 ms (which is less than 40000 ms that the Agent supposedly waits for before throwing the heartbeat timeout error), why did the Agent drop the Adapter connection at 20000 ms exactly?

Unless the Agent doesn't wait for (m_heartbeatFrequency * 2) as logged in lines 203-205 of [connector.cpp](https://github.com/mtconnect/cppagent/blob/e8f90e22ab26b45f46dd0d52044af6b2a379a5e5/src/connector.cpp), but only for m_heartbeatFrequency.

```
                     g_logger << LERROR << "(Port:" << m_localPort << ")"
                     << "connect: Did not receive heartbeat for over: "
                     << (m_heartbeatFrequency * 2).count();
```

And, from what I am seeing in connector.cpp, if the Agent gets a read from the Adapter connection that results in >0 status (i.e. the # of bytes returned, meaning the Adapter **is** responding), the socket's buffer is parsed (line #181), but unless the Agent needs to send a PING to break the loop (line #208), the connection errors out (line #225).

![10-12-2020 1-39-45 PM](https://user-images.githubusercontent.com/11392386/95780493-9c7a8b00-0c91-11eb-82f6-0b56f6006849.png)

**Comment by dkiktenko** [comment]
![10-12-2020 1-39-45 PM](https://user-images.githubusercontent.com/11392386/95782038-94701a80-0c94-11eb-8459-3f284f42206e.png)

**Comment by wsobel** [comment]
The default PONG response frequency is 10000 (10s) and the timeout becomes 20s which is correct. (10s * 2). The adapter is given PING * 2 to respond with something. The adapter is therefor non-responsive.

If the adapter response once with a PONG as a response to a PING m_heartbeats is set to true and the legacy timeout is not invoked. The assumption is the adapter responded with a PONG and gave the frequency it wants to be PINGed at. 

The adapter can response with 20000 which will allow for 40s timeout. But I would wonder why the adapter is so unresponsive. 

I don’t think there is an issue with the code. It appears to be doing the right thing–unless I’m missing something.

Do you have the code for the adapter? I can review and see if there is an issue.

Thanks,
W

**Comment by wsobel** [comment]
Ok, after re-reading I see your point. If we get some data, but the adapter has not responded to the PING, then we will still timeout even though the fact we got data is a sign of life. We could change this to set the last heartbeat time in parseBuffer to always set the last heartbeat regardless if some data is sent. 

The only caveat is if the timeout fires at freq*2, then we will receive a TIMEOUT error on the socket and the data will not be processed. This will handle the case where the adapter sends data before a PONG and then would send the PONG after the data within the timeout period closing the small window where the data comes just before the 20 second timeout and the PONG would come just after the 20 second timeout.

Is that what you were getting at? 

This does just fixes that one edge condition, something we have not run into since the idea is to get back in a few seconds.

**Comment by dkiktenko** [comment]
Yes - that is exactly it.
Would make the Agent more forgiving.

Thank you!

**Comment by wsobel** [comment]
I’m working on updates to the agent for the upcoming 1.7 release. I’ll add it to the development queue for the agent. If you are a member of the MTConnect institute (free) you can get a release of the agent as we develop the updates. The only requirement is the IP policy that means information will not be disclosed before it is public and reviewed copyright and patent issues. 

Best
W

(Sent from mobile)
