### ISSUE TITLE
Build error on Virtual Box

### ISSUE THREAD

**Issue by bankh** [mtconnect/cppagent#158]
The details in [this link](http://mtcup.org/wiki/Installing_C%2B%2B_Agent_on_Ubuntu) had an issue during the build, which uses this Github page as a code repository. The error was "libxml/tree.h: No such file or directory" and to fix that, I added the following line "find_package(LibXml2 REQUIRED)" before "#Add our dependency projects" in ../cppagent/CMakeList.txt. This fixed the issue for me.

Is this a problem for everyone? I experienced this on a virtual machine that has a fresh Installation of "2020-02-12-rpd-x86-buster". I opened this issue to make sure that others who would experience the same issue would quickly circumvent it. I checked former issues -including closed ones- and I couldn't find a solution.

**Comment by NeilDes** [comment]
I experienced this as well.

**Comment by wsobel** [comment]
What OS and version are you running in virtual box?

(Sent from mobile)

**Comment by bankh** [comment]
You can close the issue from my standpoint since I have a working solution. That would be nice to know if that works for others as well. I stated the issue since I didn't find a solution here and I hope my answer would work for others. OS is also provided in the text as [2020-02-12-rpd-x86-buster](https://www.raspberrypi.org/downloads/raspberry-pi-desktop/).

**Comment by eparks1860** [comment]
I ran into the same issue.  I am building the agent on a raspberry pi.  Raspbian GNU/Linux 10 (buster).  bankh's fix worked for me as well.

**Comment by wsobel** [comment]
The new agent requires gcc 8.5 and later since it uses C++ 17 conventions.
