### ISSUE TITLE
Agent not receiving PONG from simulator on Windows

### ISSUE THREAD

**Issue by waffleShirt** [mtconnect/cppagent#159]
I've been trying to get the simulator to run with the VMC-3Axis-Log.txt file using the latest Windows binary release in preparation for adding a feature to TrakHound. I'm running a Windows 10 64bit setup. 

I've launched the simulator with `run_scenario.rb VMC-3Axis-Log.txt` and then the agent with `agent.exe debug agent.cfg` in two Command Prompt windows 

The agent receives a connection from the simulator and sends the initial PING. The simulator receives the PING and responds with PONG. The PONG is seemingly never received by the agent as it goes silent and no more messages are displayed. Likewise the simulator never starts showing any output from the log file. 

I've checked my firewall settings and also disabled the Windows firewall just to be sure that nothing is getting stopped there. But as both the agent and the simulator do initially talk I don't imagine this to be the cause of the issue. 

I've also tried this on an older binary, cppagent-1.5.0.12-win64, and experience the same problem. 

Have I missed something when trying to run the simulator? Any help would be greatly appreciated.

**Comment by wsobel** [comment]
Use the -v argument on the run_scenario.rb to see the what's being sent and received by the script.

**Comment by waffleShirt** [comment]
I knew it'd be something simple. Thanks!
