### ISSUE TITLE
Error in the adapter test

### ISSUE THREAD

**Issue by Jpmiranda56439** [mtconnect/cppagent#161]
Hello, 
I'm following this tutorial (http://mtcup.org/wiki/Installing_C%2B%2B_Agent_on_Ubuntu) to implement this MTConnect agent in a Raspberry Pi. But when I execute the command "make" from the tutorial, it appears the following error:
![Error make](https://user-images.githubusercontent.com/78888332/107695011-07f35a00-6c7e-11eb-9b1e-83147abc048d.PNG)
Right now I'm not sure about how to fix this mistake.
Thank you for the attentiont and thank you for the help.

**Comment by wsobel** [comment]
What version of ubuntu and gcc are you using?

**Comment by Jpmiranda56439** [comment]
Hello, I work with a Raspberry PI with this:
![Version](https://user-images.githubusercontent.com/78888332/107707527-003cb100-6c90-11eb-89d2-59190c9754d0.PNG)

**Comment by wsobel** [comment]
What version of g++?

(Sent from mobile)

**Comment by Jpmiranda56439** [comment]
![G++](https://user-images.githubusercontent.com/78888332/107709686-9de5af80-6c93-11eb-871e-b61da8633f26.PNG)

**Comment by wsobel** [comment]
You may try upgrading to 9.0. Version 1.6 should build w/ 8.x. What is odd is it is failing in the link, not in the compile. 

Couple of thoughs, the pi does not have a lot of memory:
1. Have you tried dding swap?
2. Can you cross compile from another computer?

I will try to reproduce.

- W

**Comment by russwaddell** [comment]
You can try:

1. confirm your running cmake as sudo
2. check for a missing directory
3. confirm target directory for cmake has write access

**Comment by wsobel** [comment]
I am considering this solved since I have not seen another response.
