### ISSUE TITLE
MonitorConfigFiles not working

### ISSUE THREAD

**Issue by NeilDes** [mtconnect/cppagent#164]
Agent release v1.7.0.2

I changed a dataitemID in the devices file and the agent did not detect and restart.
I changed a setting in the agent.cfg file and it also did not detect it.

MonitorConfigFiles = true
MinimumConfigReloadAge = 15

Note the agent log...i made changes AFTER the agent could not resolve the device name and set the adapter to the default device.
[V1.7.zip](https://github.com/mtconnect/cppagent/files/6351963/V1.7.zip)

**Comment by hulinning2** [comment]
I reported back then 
https://github.com/mtconnect/cppagent/issues/138

It might not be fixed yet

**Comment by wsobel** [comment]
This is an issue right now with the new agent. The warm start requires some changes that are currently in progress. I needed to disable this feature until I have finished the next set of changes.

**Comment by wsobel** [comment]
Added the code back in and need to test. Currently in the 1.7.0.3 pull request.
