### ISSUE TITLE
Current Page Not Rendering Properly

### ISSUE THREAD

**Issue by dkiktenko** [mtconnect/cppagent#165]
Using x64 1.7.0.2 release, the /current page of the running Agent doesn't render properly on any common web browser.
Only items modified in the release files are within the Agent configuration file:
- Set service name
- Set Adapter host & port number
- Set port number

On Google Chrome (ver. 90.0.4430.93 64-bit):

![image](https://user-images.githubusercontent.com/11392386/116431496-753e7200-a80d-11eb-9b07-ad0ec14fe3e3.png)

On Mozilla Firefox (ver. 88.0 64-bit)

![image](https://user-images.githubusercontent.com/11392386/116431152-1ed13380-a80d-11eb-81cc-bfa52e1e2a02.png)

On Internet Explorer (ver. 20H2 - OS Build 19042.906):

![image](https://user-images.githubusercontent.com/11392386/116431413-62c43880-a80d-11eb-9116-b39266aec5ee.png)

On Microsoft Edge (ver. 90.0.818.49 64-bit):

![image](https://user-images.githubusercontent.com/11392386/116431638-969f5e00-a80d-11eb-9185-77c681ff8587.png)

**Comment by wsobel** [comment]
We need to make sure the XSLT files are in the correct place and referenced by the agent correctly.

I can check to make sure they are setup correctly. Did you start the default configuration from the bin directory?

The underlying XML should be correct.

**Comment by dkiktenko** [comment]
Correct- everything used the same as what is included in the x64 .zip of the release. The only changes were made were to the configuration file and they are standard changes.
File paths are correct. No errors installing the Agent service or during service startup.

If I inspect source of the Google Chrome page, the raw XML comes up without any problems.
Agent log file with trace severity is attached.
[agent.log](https://github.com/mtconnect/cppagent/files/6393159/agent.log)

**Comment by wsobel** [comment]
Looks like some of the static file resources are not being served up correctly. I’ll check into it.

Best,
W

**Comment by wsobel** [comment]
String method on path behaves differently in windows. Fixed path resolution for files cache. Changes in pull request.
