### ISSUE TITLE
Docker image of cppagent on Docker Hub

### ISSUE THREAD

**Issue by bburns** [mtconnect/cppagent#167]
We've added a multi-architecture (amd64, arm64, arm/v7) Docker image of the MTConnect agent to Docker Hub at https://hub.docker.com/repository/docker/ladder99/agent. It currently uses cppagent 1.7.0.3.

The Dockerfile is here - https://github.com/Ladder99/ladder99/blob/main/pipeline/agent/Dockerfile

By default the image will run the VMC simulation included with cppagent - 

    docker run -it --init --rm -p 5000:5000 ladder99/agent:latest

then visit http://localhost:5000 - or you can point it at your own configuration directory - 

    docker run -it --init --rm -p 5000:5000 \
        -v $(pwd)/setups/ccs-pa/volumes/agent:/data/agent \
        --workdir /data/agent \
        ladder99/agent:latest agent debug

![agent-html-1500x500](https://user-images.githubusercontent.com/415945/125329346-02706d80-e30b-11eb-9300-b9185449941c.jpg)

The XSL stylesheets are adapted from https://github.com/TrakHound/MTConnect-Agent-Stylesheet - we might extend them a bit - make the sections collapsible, add an xpath search box, etc.

We're building an open pipeline around the MTConnect agent. Documentation is here - https://ladder99.readthedocs.io. So far just the Agent is official - the rest is under development.

**Comment by wsobel** [comment]
Thanks! 

Looks great–reminds me we should create an mtconnect docker org to provide something like this. Want to make the adapter host/port configurable as well. Maybe have the config file and Device.xml on the shared volume.

Best,
W

**Comment by MRIIOT** [comment]
@wsobel I am open to integrating what we have done more into the MTC org.  There is no need to duplicate work if we're going to maintain the container anyway.  

@bburns bring this up during 7/14 Agent meeting to understand what is required.
