### ISSUE TITLE
shdr commands for v1.7 causing agent "unrecognized command'

### ISSUE THREAD

**Issue by NeilDes** [mtconnect/cppagent#173]
[V1.7.zip](https://github.com/mtconnect/cppagent/files/7101775/V1.7.zip)

* adapterversion: 1.7.0.0
* conversionrequired: no
* mtconnectversion: 1.7
* serialnumber: 196608
* shdrversion: 1
* realtime: no

putty log file attached of shdr

**Comment by NeilDes** [comment]
If I comment out two cmds, it gets by...

* conversionRequired
* shdrVersion:

**Comment by wsobel** [comment]
Made it case insensitive, but looks like there may be a second issue wrt the removal of specific items

**Comment by wsobel** [comment]
There was another issue with the variant type for shdrversion. Added more logging as well.
