### ISSUE TITLE
"deviceModelChangeTime" attribute missing from streams HEADER

### ISSUE THREAD

**Issue by NeilDes** [mtconnect/cppagent#175]

**Comment by wsobel** [comment]
The header attribute was: `deviceMetaDataChangeTime` and it is not added to the current XML document.

See: https://projects.mtconnect.org/issues/2192

**Comment by NeilDes** [comment]
So just a schema issue then requiring it?

**Comment by wsobel** [comment]
Agent was not generating. Need to fix
