### ISSUE TITLE
AGENT device AVAILABILITY tag always UNAVAILABLE

### ISSUE THREAD

**Issue by NeilDes** [mtconnect/cppagent#179]
v1.7.0.4

**Comment by wsobel** [comment]
Is this related to another issue? Will need more context.

**Comment by hulinning2** [comment]
It worked on 1.7.0.5

**Comment by wsobel** [comment]
Thanks Linh. Unless I hear back from Neil, I’ll close it.

-W

**Comment by NeilDes** [comment]
Goto online url
http://mtconnect.mazakcorp.com:5717/current

Agent 1.7.0.5
Device Agent
AVAILABILITY tag is always UNAAVAILABLE

<Availability dataItemId="agent_avail" sequence="2" timestamp="2021-09-21T22:18:45.205589Z">UNAVAILABLE</Availability>

Shouldn't it be AVAILABLE at some point?

**Comment by wsobel** [comment]
Is available coming through in the shdr?

(Sent from mobile)

**Comment by NeilDes** [comment]
It is for the machine / device.  But what is the AGENT AVAILABILITY supposed to represent?  I thought it was state of the agent .

**Comment by wsobel** [comment]
Ok. Missed that. I’ll review the current state. It should be available. 

(Sent from mobile)
