### ISSUE TITLE
XmlSpy fails to validate an Empty Assets

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#18]
<?xml version="1.0" encoding="UTF-8"?>
<MTConnectAssets xmlns:m="urn:mtconnect.org:MTConnectAssets:1.2" xmlns="urn:mtconnect.org:MTConnectAssets:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mtconnect.org:MTConnectAssets:1.2 /schemas/MTConnectAssets_1.2.xsd">
  <Header creationTime="2015-01-26T05:45:32Z" sender="OKUMAOK-VVEN0MK" instanceId="1422251112" version="1.3.0.9" assetBufferSize="1024" assetCount="0"/>
  <Assets/>
</MTConnectAssets>

**Comment by wsobel** [comment]
not sure what this means? the XML Schema allows for 0 assets, so I need more context.

**Comment by hulinning2** [comment]
Based on schema of Assets it requires at least 1 asset.  In this case asset count is zero therefore XmlSpy is failed

**Comment by wsobel** [comment]
Version 1.3:

<?xml version="1.0" encoding="UTF-8"?>
<MTConnectAssets xmlns="urn:mtconnect.org:MTConnectAssets:1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mtconnect.org:MTConnectAssets:1.3 MTConnectAssets_1.3.xsd">
	<Header version="" creationTime="" instanceId="" sender="" assetBufferSize="" assetCount=""/>
	<Assets/>
</MTConnectAssets>

Is valid using the schema files included in the 1.3 agent.

**Comment by hulinning2** [comment]
It fails in 1.2 schema using 1.3.0.9_1 agent
Devices = Devices.xml

SchemaVersion = 1.2
			# using schema version 1.2
Port=5000				# default port number for agent  
UpcaseDataItemValue=false

Adapters 

{ 
   
	OKUMA.Machine.Adapter		# for reference OKUMA machine adapter
   
	{
      
		Host = localhost
      
		Port = 7878 		# default port number for OKUMA MTConnect Adapter
   
	}

}

**Comment by wsobel** [comment]
Ok… not sure if I updated the legacy schema… I can check it out. I will also need to check the 1.2 docs.

- W

**Comment by wsobel** [comment]
Update schema file from 1.2 branch.

https://github.com/mtconnect/cppagent/blob/master/schemas/MTConnectAssets_1.2.xsd

Commit: 929cfef41ff08a52e9e0b817cc8a5eb4a2e07797
