### ISSUE TITLE
Not compatible with schema 1.3 for Tool Assets

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#182]
I got tool assets when using agent 1.3.0.7
when I try the agent version number 1.7.0.5 with schema 1.3 (nothing change) I got nothing in the Assets command output.

I think this is a bug.

thanks

**Comment by wsobel** [comment]
I’ll check it out. The agent disables features depending on version. Tools should be in 1.3. 

(Sent from mobile)

**Comment by hulinning2** [comment]
Fixed in version 1.7.0.7.
