### ISSUE TITLE
<Agent> device in Device file preventing agent from starting

### ISSUE THREAD

**Issue by NeilDes** [mtconnect/cppagent#185]
Traditionally, the agent ignores the HEADER info in a device file when it starts.  But the agent will not start if the ```<Agent/>``` device is included in the device file.   No  trace logging as to why.  Once removed, the agent starts ok.

Validation fails if ```<Agent/>``` device is not in the device file.  So, we need the agent to ignore the ```<Agent/>``` device at startup just like it ignores the header info.

**Comment by wsobel** [comment]
I'll check this out. The agent is automatically generated by the Agent when it starts. It is an internal device and theoretically should never appear in the Device file. It should have logged an error saying duplicate device. I'll improve the logging.

**Comment by wsobel** [comment]
I believe this was fixed in the latest version.
