### ISSUE TITLE
PathPosition coordinates for Y and Z are cut off

### ISSUE THREAD

**Issue by dr-mitutoyo** [mtconnect/cppagent#191]
We have a data item defined with the type PATH_POSITION defined as sample. We are using the dotnet adapter sdk that we have adapted for our needs (migrated to .Net Core, packaged as a NuGet package,... ). Since version 1.7 the data that is sent is not handled correctly. The MTConnect agent shows only the X coordinate as a floating point value but the Y and Z coordinate are cut off. We have checked with earlier versions (1.6) and there the problem seems not to be present.

**Comment by wsobel** [comment]
Can you attach  the adapter data in a file and then configuration files? I will need to check this out to see what is happening. 

(Sent from mobile)

**Comment by dr-mitutoyo** [comment]
Thanks for the fast reply. I attached a zip file with the information. We are using the [dotnet sdk](https://github.com/mtconnect/dot_net_sdk) with an adapted MTCAdapter that I included in the zip file. I also included an Adapter.cs file that contains the code using the sdk that i stripped down to the minimum for clarity. Furthermore I included the agent config file and the Devices.xml file. If you need more information, please let me know.

[issue191.zip](https://github.com/mtconnect/cppagent/files/7609126/issue191.zip)

**Comment by wsobel** [comment]
Thanks, I’m off today for the thanksgiving holiday. But should get to it over the next few days. - W

(Sent from mobile)

**Comment by wsobel** [comment]
The issue is you forgot to put the units on the sample type: `units="MILLIMETER_3D"` 

```xml
        <DataItem category="SAMPLE" id="WORKOFFSET_XYZ_AXIS" name="current position" type="PATH_POSITION" units="MILLIMETER_3D"/>
        <Dataitem category="SAMPLE" id="TEMPERATURE" name="current part temparature" type="PART_TEMPERATURE" units="CELSIUS" />
```

The agent checks for 3D types and does the parses the values, otherwise it treats it like a scaler value. The standard says that all Sample category data items require units. i will be enforcing this in the next version of the agent since it has a lot more checks in place.

One other point. For work offsets, path position is not the correct data item type. We have Work Offsets for that purpose. The poth position is for the control point of the control path.

**Comment by dr-mitutoyo** [comment]
Thanks for the fast response. Indeed this solved the issue.
Concerning the work offset I think the data type is correct but the id has a misleading name. It is used to show the current position of the tactile probe tip. Unfortunately the name was given some time ago and once it has been released it is not easy to change the name when there might be customers actively using the value.

**Comment by wsobel** [comment]
Sounds good, your use is correct. Best, - W

(Sent from mobile)
