### ISSUE TITLE
Values of data items of category Event type Message shown as unavailable

### ISSUE THREAD

**Issue by markjmorrison** [mtconnect/cppagent#193]
In all versions of 1.7, when queried, the agent returns the value of UNAVAILABLE for all data items of category Event and type Message. Versions 1.6 and earlier return the current correct values. The adapter sending the information to the agent uses Schema 1.3

**Comment by wsobel** [comment]
The values will be unavailable until set. I need more information to be able to diagnose.

**Comment by markjmorrison** [comment]
The adapter sends all data item values to the agent on startup. Versions 1.6 and earlier work properly when queried.

For example, the adapter sends this information to the agent for data item Laserdyne_795_9999progChksum:
2021-12-23T20:48:56.200000Z|Laserdyne_795_9999progChksum|D9E64907

When queried, the version 1.6 agent responds with this xml line for the data item:
<Message dataItemId="Laserdyne_795_9999progChksum" timestamp="2021-12-23T20:48:56.200000Z" name="ProgramChecksum" sequence="215" nativeCode="D9E64907">D9E64907</Message>

When queried, the version 1.7 agent responds with this xml line for the data item:
<Message dataItemId="Laserdyne_795_9999progChksum" name="ProgramChecksum" sequence="61" timestamp="2021-12-23T20:55:35.537997Z">UNAVAILABLE</Message>

The device xml file is contained in this link:
[Laserdyne_795_9999.txt](https://github.com/mtconnect/cppagent/files/7771304/Laserdyne_795_9999.txt)

Thanks
Mark

**Comment by wsobel** [comment]
The link did not work. 

Please attach the device xml, the adapter output, and the agent logs. 

The new agent is doing more validation of data. You should see it in the logs.

**Comment by wsobel** [comment]
Never got supporting files.
