### ISSUE TITLE
Input Connector Socket Exception

### ISSUE THREAD

**Issue by Raiu1994** [mtconnect/cppagent#195]
Two of my machines are repeating the following warning, and I've found no documentation as to it's cause. The last report for both machines was the 17th, though they have not been continously reporting, but rather sending out roughly 75 documents every two weeks or so.

WARN [2] input.connector: (Port:3452816845)connect: Socket exception: unable to connect to 'localhost:7878'

input.adapter then waits 10000 milliseconds before attempting to reconnect again.

I've also received the following error, but it also appears on the machine which is reporting correctly.

ERROR [400] dlib.server_http: Error processing request from: 10.100.100.46 - HTTP field from client terminated incorrectly

I do know the IP addresses of the two machines were changed, but that was before the 17th. I'm not certain how to go about fixing this issue.

**Comment by wsobel** [comment]
Is this a client application connecting via http to the agent or the agent connecting to the adapter?

**Comment by wsobel** [comment]
I'm also confused by what you mean regarding 75 documents every 2 weeks. Please provide more info to help me understand what is happening.

**Comment by Raiu1994** [comment]
The warning and error came from the agent log of the machine, so I believe it's the agent connecting to the adapter.  Let me explain the process I have.

I am gathering machine logs (event changes, machine state, ect) from my Mazak machines using MTConnect and gathering them on one computer. I then use dataminer in order to convert the data into JSONs so I can feed them into ELK.

The 75 documents, like the one below, is what I see in ELK. From somewhere between two days to four weeks, I receive nothing from those two machines. Then, suddenly, I received many documents with the same timestamp, down to the millisecond. After that single burst, I receive nothing until the next burst sometime between two days to four weeks later. 

`deviceName.keyword:VCN510-09-3 @timestamp:Dec 17, 2021 @ 08:21:11.885 @version:1 @version.keyword:1 componentId:c componentId.keyword:c dataItemId:rf dataItemId.keyword:rf deviceName:VCN510-09-3 deviceUUID:VCN510-09-3 deviceUUID.keyword:VCN510-09-3 Events.RotaryMode.@@data:UNAVAILABLE Events.RotaryMode.@@data.keyword:UNAVAILABLE Events.RotaryMode.name:crfunc Events.RotaryMode.name.keyword:crfunc host:MEHRANBOXX-PC host.keyword:MEHRANBOXX-PC lastEvent:UNAVAILABLE lastEvent.keyword:UNAVAILABLE path:C:/mtdataminer/logs/MTConnect-VCN510-09-3-VCN510-09-3-20211217-082103.log path.keyword:C:/mtdataminer/logs/MTConnect-VCN510-09-3-VCN510-09-3-20211217-082103.log sequence:46 Time:Dec 17, 2021 @ 08:21:11.885 timestamp:Dec 17, 2021 @ 06:59:25.802 type:json type.keyword:json
`

In this case, I think the issue is more in the connection than the HTTP error.

**Comment by Raiu1994** [comment]
The socket exception error was caused by the main software of the machines being out of date. Having updated the main software, the machines are now communicating.
