### ISSUE TITLE
Translation (Configuration) is being stripped by Agent

### ISSUE THREAD

**Issue by NeilDes** [mtconnect/cppagent#198]
Translation (Configuration) is being stripped by Agent and causeing validation failure

From device file
```xml
      <Configuration>
        <CoordinateSystems>
          <CoordinateSystem id="machcoord" type="MACHINE">
            <Transformation>
              <Translaton>0 0 0</Translaton>
              <Rotation>0 0 0</Rotation>
            </Transformation>
          </CoordinateSystem>
          <CoordinateSystem id="workcoord" type="OBJECT" parentIdRef="machcoord">
            <Transformation>
              <Translaton>0 0 0</Translaton>
              <Rotation>0 0 0</Rotation>
            </Transformation>
          </CoordinateSystem>
        </CoordinateSystems>
      </Configuration>
````
From agent output on probe command

```xml
<Configuration>
<CoordinateSystems>
<CoordinateSystem id="machcoord" type="MACHINE">
<Transformation>
<Rotation>0 0 0</Rotation>
</Transformation>
</CoordinateSystem>
<CoordinateSystem id="workcoord" parentIdRef="machcoord" type="OBJECT">
<Transformation>
<Rotation>0 0 0</Rotation>
</Transformation>
</CoordinateSystem>
</CoordinateSystems>
</Configuration>
```

**Comment by wsobel** [comment]
Translation is missing an i: 

In device file: “Translaton” vs 

Should be: “Translation” 

This should have been logged. Check the agent.log and see if there wasn’t a warning.

**Comment by NeilDes** [comment]
Ok.  Fixed typo.  But now doesnt validate to the schema online.  Looks like a typo there as well.

From XMLSpy....
Element <Translation> is not allowed under element <Transformation>.
Reason: The following elements are expected at this location (see below)
'Translaton'
'Rotation'

**Comment by wsobel** [comment]
Must be a schema issue. What version of the schema?

**Comment by NeilDes** [comment]
V1.7

**Comment by wsobel** [comment]
Fixed in schemas.MTConnect.org

Will fix in next build. 

(Sent from mobile)
