### ISSUE TITLE
observationrate tag

### ISSUE THREAD

**Issue by NeilDes** [mtconnect/cppagent#199]
observationrate tag is output even if "schemaversion=1.3" is set in cfg file.

although it gets ignored, it also generates an error in log file.   Customer assumes something is wrong.

**Comment by wsobel** [comment]
Thanks, I’ll take a look. Versioning is complex for model support.

**Comment by wsobel** [comment]
Where is observation rate occurring? I don't see it in the code. I'm probably missing something. Pls provide more context.

**Comment by wsobel** [comment]
Please comment if this is still an issue. Otherwise I will close it.
