### ISSUE TITLE
Not compatible with schema 1.2 for current stream with agent version 1.8.0.2 - Pallet ID is not valid

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#201]
Failed to validate the current stream output as shown below. The current stream is using MTConnect Schema version 1.2. spec - Pallet ID is not valid

File http://localhost:5000/current is not valid.
	Element <PalletId> is not allowed under element <Events>.
		Reason: The following elements are expected at this location (see below)
			'Event'
			'Code'
			'Block'
			'Line'
			'PowerStatus'
			'PowerState'
			'PartCount'
			'Direction'
			'Program'
			'Execution'
			'ControllerMode'
			'ToolAssetId'
			'ToolId'
			'ToolNumber'
			'PartId'
			'DoorState'
			'WorkholdingId'
			'RotaryMode'
			'ActiveAxes'
			'CoupledAxes'
			'AxesCoupling'
			'Message'
			'EmergencyStop'
			'Availability'
			'ActuatorState'
			'PathMode'
			'LinePowerState'
			'ControlPowerState'
			'AssetChanged'
			'Alarm'
		Annotations of element 'Events' (see below)
			A collection of events
		Annotations of type 'EventsType' (see below)
			A collection of events and alarms for this component
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Events / PalletId
		Details
			cvc-complex-type.1.4: Element <PalletId> unexpected by type 'EventsType' of element <Events>.
			cvc-type.3.2: Element <Events> is not valid with respect to type definition 'EventsType'.
			cvc-elt.5.2.1: The element <Events> is not valid with respect to the actual type definition 'EventsType'.
![image](https://user-images.githubusercontent.com/4930742/150601863-4a9d2014-b66e-4579-860c-dde043576339.png)

**Comment by wsobel** [comment]
I’ll check into this. Looks like something may be missing. - W

**Comment by wsobel** [comment]
Check with the current set of schemas. We will be generating the schemas from the model for each version. This should work since we have annotated everything with version #s.

**Comment by hulinning2** [comment]
using latest version of MTConnect
