### ISSUE TITLE
Cutting tools not validating / tools not loaded

### ISSUE THREAD

**Issue by NeilDes** [mtconnect/cppagent#205]
I get different results with different version agents.   Cutting tool assets not loading into agent from shdr. (see attached shdr)
Also, validation varies by schema version. 

On one agent a range of tools doesnt get loaded.   On a different version agent, a diferent range gets exculed.

[AssetErrors.log](https://github.com/mtconnect/cppagent/files/7954204/AssetErrors.log)

**Comment by wsobel** [comment]
The new agent is stricter for asset validation, before it did almost nothing. I'll check in the latest (1.7/1.8) versions as well as 2.0. If there is an error, it should be logged as well.

**Comment by wsobel** [comment]
I'll check the log file tomorrow.
