### ISSUE TITLE
Missing assetType attribute in AssetChanged and AssetRemoved of MTConnectStreams

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#206]
It fails to validate with schema 1.6, 1.5, 1.4, 1.3, and 1.2

![image](https://user-images.githubusercontent.com/4930742/151561526-02853e8b-5612-4494-bfae-c65ca5af2f75.png)

I notice that if there is no tool in the assets then assetType is missing from both AssetChanged and AssetRemoved.
When there are tools in the system and tools have been removed then assetType is available.

So the problem is only when no tools in the system. 

![image](https://user-images.githubusercontent.com/4930742/151566864-c293e82d-6575-4836-aa0d-ec9be1151f63.png)

**Comment by hulinning2** [comment]
I think MTConnect Agent 1.8.x.x does not raise the Asset change/remove correctly. 
I test by changing tools but nothing happening or no asset change/remove shown in the current or sample data
and that cause the error in validation

**Comment by wsobel** [comment]
This is fixed on master. I will create a new release with new xsds. 

(Sent from mobile)

**Comment by wsobel** [comment]
This is fixed in the schemas
