### ISSUE TITLE
Rendering mtconnect pages issue: Styles.xsl:182

### ISSUE THREAD

**Issue by Icydeath** [mtconnect/cppagent#207]
This is a fresh download of 1.8.0.2 from the releases page.

The MTConnect Agent is working fine, but the pages fail to render and are blank.

![image](https://user-images.githubusercontent.com/6233937/160973170-37fbfcad-35b5-452c-bc44-e826498b9dc3.png)

![mtconnect-styles-issue-v1 8 0 2](https://user-images.githubusercontent.com/6233937/160972914-f00c48c3-2069-4a85-8ad7-a4f8512139a7.png)

Any help would be appreciated. Thanks

**Comment by vococo-ndoell** [comment]
I'm seeing the same issue.

**Comment by wsobel** [comment]
Please upload your agent.cfg. The directories need to be referenced and the style sheets configured. 

(Sent from mobile)

**Comment by Icydeath** [comment]
I haven't made any changes to to the cfg or the folder structure. Plus, the agent in debug mode is not throwing any errors/warnings & browser dev tools is not throwing any 400 errors.
Did you still want me to upload it?

**Comment by wsobel** [comment]
I would need to verify the configuration and directory structure first to be able to advise and reproduce the issue. 

(Sent from mobile)

**Comment by Icydeath** [comment]
All you have to do to reproduce the issue is:
1. Download [cppagent-1.8.0.2-win64.zip](https://github.com/mtconnect/cppagent/releases/download/v1.8.0.2/cppagent-1.8.0.2-win64.zip) from releases.
2. Unzip to a folder
3. Open command prompt and run "agent.exe debug agent.cfg"
4. Open a browser and go to http://localhost:5000
And you'll notice the issue we are having.

Regardless here is the untouched config (had to zip it up because github doesn't allow for .cfg uploads)
[agent.zip](https://github.com/mtconnect/cppagent/files/8402721/agent.zip)

Here is the folder structure:
![image](https://user-images.githubusercontent.com/6233937/161388092-e6d3a87d-a6d8-402a-96f3-23d23252a369.png)

**Comment by wsobel** [comment]
Thanks for the info. I’ll test it on my side. 

(Sent from mobile)

**Comment by bburns** [comment]
I'll try it on Windows this morning - maybe something changed in the compilation step from 1.7?

We've been using the 1.7.0.3 agent with Docker from here - https://hub.docker.com/repository/docker/ladder99/agent - compiled on Ubuntu as here - 

https://github.com/Ladder99/ladder99-ce/blob/main/services/mtconnect-agent/Dockerfile

and here - 

https://github.com/Ladder99/ladder99-ce/blob/main/services/agent/Dockerfile

**Comment by bburns** [comment]
Yeah, it happens for me on Windows - the only thing I can think is that for some reason it doesn't like the `xsl:include` statements - I can replace those with the file contents and see if it still happens. Will try later today/tonight. 

https://github.com/mtconnect/cppagent/blob/40810309090ffb509d8fbe962a146aeadd4862fd/styles/styles.xsl#L178

**Comment by Icydeath** [comment]
Awesome, Thanks @bburns

**Comment by Icydeath** [comment]
Oops didn't mean to close it haha

**Comment by bburns** [comment]
I've been trying to get the xsl and images to work on the Windows agent and found these issues -

- the windows agent doesn't handle the xsl:include statements in the styles.xsl file correctly - it adds extra text at the end of the xsl document. but i can substitute the xsl in place of the xsl:include statements and it works okay. 

- the windows agent doesn't serve the png files correctly - they come up blank in windows chrome, and on windows firefox they say "the image cannot be displayed because it contains errors". the styles xsl uses pngs for the mtconnect logo and the small button icons. 

- the windows agent does serve jpg and ico files okay though.

So there's something weird with the windows agent's server. 

I dug around a bit but couldn't find anything - eg this uses dlib for serving the data - https://github.com/mtconnect/cppagent/blob/a6c47791655bf35bff82cf0023e509bfca481ab8/src/http_server/server.hpp

Do you know where the problem might be, Will?

If not I'll just fix the xsl and convert the pngs to jpgs and submit a PR.

**Comment by wsobel** [comment]
Not sure. 

I have been putting most of my time into the new version of the agent, 2.0, that uses boost beast and has a completely new file management system. I have tested it with multiple file types and the https://demo.mtconnect.org is being served by the agent. It also supports tls and a bunch of other capabilities. 

If you would like to check it out and see if it solves the problem, i can give you access.  It does require you join the MTConnect institute, which is free. 

Best
W

(Sent from mobile)

**Comment by Icydeath** [comment]
I think the PR @bburns is suggesting is a good idea just to have a working version of 1.8.
@wsobel , I would be very interested in testing 2.0 if you don't mind sharing

**Comment by hulinning2** [comment]
Will,
Can you share how to support this demo https://demo.mtconnect.org/?
Thanks

**Comment by wsobel** [comment]
The demo required the new develoment agent. I will write up the instructions. We should discuss soon.

**Comment by bburns** [comment]
For 1.8, the quickest fix is to use this styles.xsl in place of the existing one - it merges in the included stylesheets and comments out the .png references. 

Just unzip this and put `styles.xsl` in the cppagent `styles` folder -

[styles.zip](https://github.com/mtconnect/cppagent/files/8495671/styles.zip)

and I'll work on a PR.
