### ISSUE TITLE
mruby dependancy issue

### ISSUE THREAD

**Issue by skibum1869** [mtconnect/cppagent#217]
mruby is not compiling as rake is not found. 

``` bash
mruby/3.1.0: Configuring sources in /root/.conan/data/mruby/3.1.0/_/_/source
mruby/3.1.0: Copying sources to build folder
mruby/3.1.0: Building your package in /root/.conan/data/mruby/3.1.0/_/_/build/abd3ca9581f5ec3d6672fa2ee8818b1f09dbb082
mruby/3.1.0: Generator txt created conanbuildinfo.txt
mruby/3.1.0: Calling generate()
mruby/3.1.0: Aggregating env generators
mruby/3.1.0: Calling build()
/bin/sh: 1: rake: not found
mruby/3.1.0: 
mruby/3.1.0: ERROR: Package 'abd3ca9581f5ec3d6672fa2ee8818b1f09dbb082' build failed
mruby/3.1.0: WARN: Build folder /root/.conan/data/mruby/3.1.0/_/_/build/abd3ca9581f5ec3d6672fa2ee8818b1f09dbb082
ERROR: mruby/3.1.0: Error in build() method, line 76
	self.run("rake MRUBY_CONFIG=%s" % self.build_config,
	ConanException: Error 127 while executing rake MRUBY_CONFIG=/root/.conan/data/mruby/3.1.0/_/_/build/abd3ca9581f5ec3d6672fa2ee8818b1f09dbb082/mruby_source/build_config/mtconnect.rb
```

**Comment by skibum1869** [comment]
https://github.com/skibum1869/MTConnect_Docker/runs/6611876960?check_suite_focus=true

link to the full compile log for Ubuntu docker

**Comment by skibum1869** [comment]
https://github.com/skibum1869/Alpine_MTConnect_Agent/runs/6612417373?check_suite_focus=true

link to the full compile log for alpine docker

**Comment by bburns** [comment]
This hasn't been updated yet to reflect the transition to the public repo, but it built the agent okay last week - maybe it would help?

https://github.com/mtconnect/cppagent/blob/master/Dockerfile

The github workflow uses buildx to build an amd64 + arm64 image - 

https://github.com/mtconnect/cppagent/blob/master/.github/workflows/build-docker-image.yml

Hosted here, until there's an MTConnect hub to publish to - 

https://hub.docker.com/repository/docker/ladder99/agent2

**Comment by wsobel** [comment]
The issue is we need ruby to bootstrap. We need to install as a dependency.

**Comment by wsobel** [comment]
Can I close the issue? It looks like the docker file has the apt get for ruby and rake?

**Comment by skibum1869** [comment]
I added the apt get for ubuntu but I haven't been able to find an apk add for alpine. Suggestions? So far it has successfully compiled in ubuntu but it is failing in alpine due to rake being missing. No issue closeing, we probably need to update the readme with the additional requirements of rake.

**Comment by wsobel** [comment]
I’ll fire up my alpine instance and see what needs to happen. I know it’s available, just need to find it. 

(Sent from mobile)

**Comment by wsobel** [comment]
I just updated the build instructions for alpine, you needed to install ruby and rake:


```sh
# As root
apt add ruby
gem install rake
```

**Comment by skibum1869** [comment]
Thanks
