### ISSUE TITLE
AssetChanged and AssetRemoved are Not compatible with MTConnect spec 1.4

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#224]
AssetChanged and AssetRemoved are not compatible in MTAgent 2.0.0.5

![image](https://user-images.githubusercontent.com/4930742/171040538-cfa424b4-596f-4d7a-86c3-4d51c2b6b587.png)

**Comment by wsobel** [comment]
Added a change to the agent to always have a value for the attribute since it is required in the std. We will fix the model for 2.1, but for now this should resolve the problem.
