### ISSUE TITLE
Still some references to cppagent_dev in some files

### ISSUE THREAD

**Issue by bburns** [mtconnect/cppagent#227]
![image](https://user-images.githubusercontent.com/415945/171284936-7fe13bdd-e902-417d-b044-930d0440dab4.png)

**Comment by wsobel** [comment]
Hey Brian, can you remove references and push the changes to a branch? Will need to handle the diffs between dev and public.

**Comment by bburns** [comment]
Okay, looks like you had fixed some already  - #229
