### ISSUE TITLE
Logging level not working

### ISSUE THREAD

**Issue by NeilDes** [mtconnect/cppagent#233]
V2.007 Agent
Setting logging level in agent.cfg is not changing the level of outpu
[agent_log.txt](https://github.com/mtconnect/cppagent/files/8835503/agent_log.txt)

# Logger Configuration
logger_config
{
  logging_level = warn
  max_index = 1
  max_size = 1M
  output = file agent_log.log
}

**Comment by wsobel** [comment]
I'll check it out. Finishing up the file monitoring right now–adding some tests.

I'll queue it up.

**Comment by wsobel** [comment]
Issue is logging_level changed to level. I added logging_level to provide backward compatibility.
