### ISSUE TITLE
ASSETS - REMOVE_ALL_ASSETS

### ISSUE THREAD

**Issue by NeilDes** [mtconnect/cppagent#236]
All assets being removed from ASSESTS buffer even if TYPE is specified in SHDR.

|@REMOVE_ALL_ASSETS@|File

|@REMOVE_ALL_ASSETS@|CuttingTool

**Comment by wsobel** [comment]
Will check it out. Thanks - W

(Sent from mobile)

**Comment by NeilDes** [comment]
Here is a putty capture to load up the assets buffer as well as my agent.cfg.  seems like tools get deleted when Files get loaded.

[agent.txt](https://github.com/mtconnect/cppagent/files/8894505/agent.txt)
[putty.log](https://github.com/mtconnect/cppagent/files/8894507/putty.log)

**Comment by NeilDes** [comment]
Problem Resolved....

assetCount="470"
By default, you only get **100** assets just like SAMPLE command.  Need to set **count=1000** param on query...

http://localhost:5000/assets?count=1000

Now I see the rest of the assets.  Both CuttingTools and Files.
