### ISSUE TITLE
File scheme for 2.0 spec?

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#240]
Will,
Why do you have different file name scheme from the public schema?

Public schema: 
MTConnectStreams_2.0_1.0.xsd

Cppagent: 
MTConnectStreams_2.0.0_1.0.xsd

**Comment by wsobel** [comment]
Should be the same. May need to remove the old files

**Comment by wsobel** [comment]
Updated zip files with new schema files added and old removed. commit mistake.

**Comment by shaurabhsingh** [comment]
This issue has been addressed. New schemas are reflected in the cppagent repo as well.
