### ISSUE TITLE
attribute count is missing from element AssetCountDataSet in schema 2.0 and agent.exe version 2.0.0.8

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#241]
![image](https://user-images.githubusercontent.com/4930742/175960523-e7852876-bfd4-40be-936e-7637bc3eb314.png)

**Comment by shaurabhsingh** [comment]
@wsobel The standard requires `count` to be provided always. I think this needs to be taken care of in the Agent.

**Comment by wsobel** [comment]
Count is not generated when unavailable. If it is required I can fix it. 

(Sent from mobile)

**Comment by shaurabhsingh** [comment]
It is `required` in the standard.

**Comment by shaurabhsingh** [comment]
Although does not have a default value.

**Comment by wsobel** [comment]
Yup. I’ll fix the agent. Thanks Linh for catching and Shaurabh for pointing out the mistake. 

(Sent from mobile)

**Comment by wsobel** [comment]
Have fix in the pull request associated to the issue.
