### ISSUE TITLE
Not compatible with MTConnect spec 1.2 - Pallet ID; Agent and schema files from version 2.0.0.8

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#243]
![image](https://user-images.githubusercontent.com/4930742/175970852-7f293d6a-1bde-4ce8-ace2-138c45ea0ec9.png)

**Comment by shaurabhsingh** [comment]
Updated the schemas in the `schema` directory. Some types were missing.

**Comment by hulinning2** [comment]
resolved with latest release
