### ISSUE TITLE
Not compatible with MTConnect spec 1.4 in Probe command; Agent and schema files from version 2.0.0.8

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#246]
Latest schema files 1.4

![image](https://user-images.githubusercontent.com/4930742/176959448-c267989e-b101-448d-b196-8a9544563168.png)

**Comment by hulinning2** [comment]
still fail in the release 2.0.0.9
![image](https://user-images.githubusercontent.com/4930742/177860764-dbfe007a-b5f5-4e64-a74a-c148486af457.png)

**Comment by wsobel** [comment]
this looks like a schema issue

**Comment by hulinning2** [comment]
still not fixed yet in 2.0.0.10

**Comment by wsobel** [comment]
Linh, is this still an issue?
