### ISSUE TITLE
Agent cannot detect that the devices.xml/agent.cfg have been changed to reload  - Latest Agent version 2.0.0.8

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#247]
MonitorConfigFiles=true			# True = reload devices.xml and agent.cfg if they are changed
MinimumConfigReloadAge = 1		# Number of seconds agent service will wait before performing reload config files

**Comment by wsobel** [comment]
There is a WIP branch on the dev repo that is addressing this. There is an issue on the windows build that is giving me trouble. 

Currently the device xml does a no-restart update of the device xml. 

(Sent from mobile)

**Comment by hulinning2** [comment]
Fixed in RC25
