### ISSUE TITLE
Agent is not responding to simulator.

### ISSUE THREAD

**Issue by Ghost-script** [mtconnect/cppagent#25]
Running Agent version 1.3.0.14
`[subho@localhost] agent $ (master) ./agent`
`MTConnect Agent Version 1.3.0.14 - built on Wed Apr  1 19:47:51 2015`

Running simulator,
`[subho@localhost] simulator $ (master) ruby run_scenario.rb -l -p 7878 --scenario -v simple_scenario_1.txt`
`run_scenario.rb:41: warning: toplevel constant String referenced by OptionParser::String`
`Waiting on 0.0.0.0 7878`

The simulator keeps waiting for the agent.
The same simulator works fine with Agent version 1.3.0.13.

**Comment by Ghost-script** [comment]
While looking at the changes in commits, in commit 7499611f06e6c295741dd9df96ba5b66e78a676c the `host` was changed in agent.cfg which caused this issue.

**Comment by wsobel** [comment]
Thanks, that was a mistake. - W

**Comment by wsobel** [comment]
Updated latest cfg file.
