### ISSUE TITLE
Package the release

### ISSUE THREAD

**Issue by sdstncl** [mtconnect/cppagent#255]
After lots of personal integration hell, I finally managed to "build" the agent with conan. By this, I mean I was finally able to write _conan build . -bf build_ in the command prompt and not get any errors. I believe the next step would be to "Package the Release" as it says further down which tells you to type _cpack -G ZIP_ in order to create a ZIP file of the build. However, every time I attempt to do this, I keep getting CPack Error: CPack Project name not specified. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\pcadm\MTC_Sam\cppagent>cpack -G ZIP
CPack Error: CPack project name not specified
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
My idea was to also attatch _-P_ with a random project name to fix it, but then it asks me specify the version too, which I also don't know
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\pcadm\MTC_Sam\cppagent>cpack -G ZIP -P cppagent
CPack Error: CPack project version not specified
Specify CPACK_PACKAGE_VERSION, or CPACK_PACKAGE_VERSION_MAJOR, CPACK_PACKAGE_VERSION_MINOR, and CPACK_PACKAGE_VERSION_PATCH.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Help would be greatly appreciated, as additionally I'm not entirely sure what the process for creating this C++ adapter is after this step. Thanks!

**Comment by sdstncl** [comment]
I think I figured this out. Before you can package the release of the build, you have to first cd to the build file that it created. 
~~~~~~~~~~~~~~~~~~~~~~~~~
cd build 
cpack -G ZIP 
~~~~~~~~~~~~~~~~~~~~~~~~~
Hopefully, this is what you're supposed to do. If not, please let me know

**Comment by wsobel** [comment]
You are correct, you need to run cpack from the build directory. We can fix the docs. - W
