### ISSUE TITLE
v2.0 - Valid dataitem value documentation

### ISSUE THREAD

**Issue by robot-ranger** [mtconnect/cppagent#259]
I know this is less of an issue and more of a question, but I dont know where else to get an answer. I am sure I am simply not looking in the right place.

Back on v1.8 the PDF standards docs had a table in part 2 - section 8.2 that detailed all of the Event data items and most importantly listed the valid data values for each.

For example, here is CONTROLLER_MODE from v1.8 Part 2 Pg 128:
![image](https://user-images.githubusercontent.com/93950632/193350570-bcd21470-d422-4d92-b330-0407d972819b.png)
As you can see - it lists the valid data values automatic, manual, etc

The new 2.0 docs list the event dataitems, but do not list the valid data values. Here is the description of CONTROLLER_MODE from v2.0 Part 2 Pg 78:
![image](https://user-images.githubusercontent.com/93950632/193350863-f29e8458-dcd3-44ab-9b46-d63f275c6993.png)

 
I have tried looking through the mtc model browser, but I cant find what I am looking for.

Was data value validation abandoned in v2.0?
Where can I find valid data values listed for event dataitems for v2.0?

Edit:
Further - there is another section in the 2.0 PDF standards that lists all "subTypes" but doesnt associate them with their parent dataitem. hard to know which subTypes associate with which dataitems

**Comment by wsobel** [comment]
In the model, look in the ControllerMode observation: https://model.mtconnect.org/#Structure__1f286c18-8e5b-4f1b-befd-61c04529ab6cLook at the result property, and it references the ControllerModeEnum: https://model.mtconnect.org/#Enumeration___19_0_3_45f01b9_1580378417660_348819_2874Every observation type of an event category with a controlled vocabulary has an enumeration for the result. All events are here: https://model.mtconnect.org/#Package__fa50649f-b8eb-4e82-a8ae-a83716fb3243Hope this helps. BestW(Sent from mobile)On Sep 30, 2022, at 13:32, robot-ranger ***@***.***> wrote:﻿
I know this is less of an issue and more of a question, but I dont know where else to get an answer. I am sure I am simply not looking in the right place.
Back on v1.8 the PDF standards docs had a table in part 2 - section 8.2 that detailed all of the Event data items and most importantly listed the valid data values for each.
For example, here is CONTROLLER_MODE from v1.8 Part 2 Pg 128:

As you can see - it lists the valid data values automatic, manual, etc
The new 2.0 docs list the event dataitems, but do not list the valid data values. Here is the description of CONTROLLER_MODE from v2.0 Part 2 Pg 78:

I have tried looking through the mtc model browser, but I cant find what I am looking for.
Was data value validation abandoned in v2.0?
Where can I find valid data values listed for event dataitems for v2.0?

**Comment by robot-ranger** [comment]
Yes - TY!!!!
