### ISSUE TITLE
Sending a second asset crashes the agent

### ISSUE THREAD

**Issue by jhitchens-juxtum** [mtconnect/cppagent#260]
I waited a few moments before trying to send each asset to the agent. 

Sent using Postman to agent 2.0.0.11 release: 

First assets sends and can be queried with a get and AssetID or DeviceUUID

```xml<CuttingTool serialNumber="0" toolId="0" timestamp="2022-10-06T18:18:39.816703Z" deviceUuid="a48e527b-e411-2c41-cd73-0f6c524ffa26" assetId="M80104K162N1.17">
  <CuttingToolLifeCycle>
    <CutterStatus>
      <Status>USED</Status>
    </CutterStatus>
    <Location negativeOverlap="0" positiveOverlap="0" type="POT">17</Location>
    <CuttingItems count="1">
      <CuttingItem indices="1">
        <Description>END MILL</Description>
        <ItemLife countDirection="UP" initial="0" limit="0" type="MINUTES" warning="80">155.75</ItemLife>
        <ItemLife countDirection="UP" initial="0" limit="0" type="PART_COUNT" warning="80">0</ItemLife>
        <CutterStatus><Status>USED</Status><Status>AVAILABLE</Status><Status>ALLOCATED</Status></CutterStatus>
        <ProgramToolGroup>0</ProgramToolGroup>
        <Measurements>
          <CuttingDiameter nominal="63">63.344</CuttingDiameter>
          <FunctionalLength>226.975</FunctionalLength>
        </Measurements>
      </CuttingItem>
    </CuttingItems>
  </CuttingToolLifeCycle>
</CuttingTool>
```
After sending the second asset the agent just crashes

```xml<CuttingTool serialNumber="0" toolId="3020000" timestamp="2022-10-06T17:14:39.799743Z" deviceUuid="a48e527b-e411-2c41-cd73-0f6c524ffa26" assetId="M80104K162N1.67">
  <CuttingToolLifeCycle>
    <CutterStatus>
      <Status>USED</Status>
    </CutterStatus>
    <Location negativeOverlap="0" positiveOverlap="0" type="POT">67</Location>
    <CuttingItems count="2">
      <CuttingItem indices="1">
        <Description>BACK SPOT FACE</Description>
        <ItemLife countDirection="UP" initial="0" limit="0" type="MINUTES" warning="80">1758.133</ItemLife>
        <ItemLife countDirection="UP" initial="0" limit="0" type="PART_COUNT" warning="80">62</ItemLife>
        <CutterStatus><Status>USED</Status><Status>AVAILABLE</Status><Status>ALLOCATED</Status></CutterStatus>
        <ProgramToolGroup>3020000</ProgramToolGroup>
        <Measurements>
          <CuttingDiameter nominal="20">20</CuttingDiameter>
          <FunctionalLength>366.38</FunctionalLength>
        </Measurements>
      </CuttingItem>
      <CuttingItem indices="2">
        <Description>BACK SPOT FACE</Description>
        <ItemLife countDirection="UP" initial="0" limit="0" type="MINUTES" warning="80">2734</ItemLife>
        <ItemLife countDirection="UP" initial="0" limit="0" type="PART_COUNT" warning="80">204</ItemLife>
        <CutterStatus><Status>USED</Status><Status>AVAILABLE</Status><Status>ALLOCATED</Status></CutterStatus>
        <ProgramToolGroup>0</ProgramToolGroup>
        <Measurements>
          <CuttingDiameter nominal="20">20</CuttingDiameter>
          <FunctionalLength>366.505</FunctionalLength>
        </Measurements>
      </CuttingItem>
    </CuttingItems>
  </CuttingToolLifeCycle>
</CuttingTool>
```
[agent.log](https://github.com/mtconnect/cppagent/files/9974252/agent.log)

**Comment by wsobel** [comment]
Can you attach the XML for the tools you sent to the agent? It will be easier to find the problem. Thx - W

**Comment by jhitchens-juxtum** [comment]
Sorry didn't realize they blocked the xml in the comment
[assets.zip](https://github.com/mtconnect/cppagent/files/9974632/assets.zip)

**Comment by wsobel** [comment]
Did you retest with the latest build? I could not repeat the issue.

**Comment by jhitchens-juxtum** [comment]
I'm unable to run a post or put, and it returns cannot find handler for POST or PUT. I downloaded from here to get the latest: https://github.com/mtconnect/cppagent/releases/download/v2.0.0.12/cppagent-2.0.0.12-win64.zip

![image](https://user-images.githubusercontent.com/117857591/205699926-32ec62eb-b28e-4e09-9d51-b107dc825be9.png)

**Comment by wsobel** [comment]
Can you upload your agent.cfg?

**Comment by jhitchens-juxtum** [comment]
[agent.txt](https://github.com/mtconnect/cppagent/files/10156668/agent.txt)

**Comment by wsobel** [comment]
I think I see the issue. Currently, the type is required by the rest interface. I can create a new RC without the type since it is optional at the higher-level API (derived from the Asset. 

FYI, you can also pass the asset directly through the SHDR socket connection, you do not need to post.

What is the complete URI you are using for the post?

**Comment by wsobel** [comment]
These are the current handlers: 

```
          m_server->addRouting({t, "/asset/{uuid}?device={string}&type={string}", putHandler});
          m_server->addRouting({t, "/asset?device={string}&type={string}", putHandler});
          m_server->addRouting({t, "/{device}/asset/{uuid}?type={string}", putHandler});
          m_server->addRouting({t, "/{device}/asset?type={string}", putHandler});
```

**Comment by wsobel** [comment]
One last question, are you posting more than one asset?

**Comment by jhitchens-juxtum** [comment]
I'm sending one asset at a time. 

http://127.0.0.1:5050/assets/M80104K162N1.32 is the URI. So ip:port/assets/assetID. Then in the body I used the assets above. The previous version allowed one and it showed up in the get query iirc. This version I'm not able to even send the one.

**Comment by wsobel** [comment]
Try it with the following 

http://127.0.0.1:5050/asset/M80104K162N1.32 <http://127.0.0.1:5050/assets/M80104K162N1.32>

Change assets to asset and see if it works. If so, I can add the assets alias. It was to say we are posting an asset at a time, not multiple.

- W

**Comment by jhitchens-juxtum** [comment]
Switching to "asset" with the body as text and then again with body as XML just causes a crash without a response. 

Used both of the following to add: 
http://127.0.0.1:5050/asset/M80104K162N1.114
http://127.0.0.1:5050/asset?type="CuttingTool"

As an aside, I would think you could just use the URI http://ip:port/asset and send an asset then it adds the asset if the asset_id doesn't exist. If it does exist it should fail and require you to use PUT to update an asset, imo. 

![image](https://user-images.githubusercontent.com/117857591/205720583-1b4104ef-d210-474d-bdda-405519360e51.png)

**Comment by wsobel** [comment]
That's how it is designed to work. The uuid and type are optional. If they are not provided, they should come form the asset body.

I have reviewed the code and may have found an issue. I will be creating a build today in the cppagent_dev repo to see if that fixes that problem.

**Comment by jhitchens-juxtum** [comment]
Okay, thank you!

**Comment by wsobel** [comment]
Just uploaded the new build for version 2.0.0.13 RC1 for the cppagent_dev repo. Tell me if you don't have access.

**Comment by wsobel** [comment]
I'm going to close this issue
