### ISSUE TITLE
Build Fails on friendlyCore (custom ubuntu Core for nanoPi R5S)

### ISSUE THREAD

**Issue by robot-ranger** [mtconnect/cppagent#261]
I am trying to build cpp agent on a nanoPi R5S. It has the mfge's custom Ubuntu Core 20.04 on it:

/home/pi/cppagent/agent/cppagent.cpp:28:17: error: ‘mtconnect’ is not a namespace-name
   28 | using namespace mtconnect;
            |                 ^~~~~~~~~
/home/pi/cppagent/agent/cppagent.cpp: In function ‘int main(int, const char**)’:
/home/pi/cppagent/agent/cppagent.cpp:32:3: error: ‘NAMED_SCOPE’ was not declared in this scope
   32 |   NAMED_SCOPE("MAIN");
      |   ^~~~~~~~~~~
/home/pi/cppagent/agent/cppagent.cpp:34:3: error: ‘configuration’ has not been declared
   34 |   configuration::AgentConfiguration config;
      |   ^~~~~~~~~~~~~
/home/pi/cppagent/agent/cppagent.cpp:36:13: error: ‘config’ was not declared in this scope
   36 |   int ret = config.main(aArgc, aArgv);
      |             ^~~~~~
make[2]: *** [agent/CMakeFiles/agent.dir/build.make:66: agent/CMakeFiles/agent.dir/cppagent.cpp.o] Error 1
make[2]: Leaving directory '/home/pi/cppagent/build'
make[1]: *** [CMakeFiles/Makefile2:166: agent/CMakeFiles/agent.dir/all] Error 2
make[1]: Leaving directory '/home/pi/cppagent/build'
make: *** [Makefile:166: all] Error 2
ERROR: conanfile.py (mtconnect_cppagent/2.0): Error in build() method, line 110
        cmake.build()
        ConanException: Error 2 while executing cmake --build '/home/pi/cppagent/build' '--' '-j4'

**Comment by wsobel** [comment]
Can you build on another machine with the nano pi toolchain. This is a pretty basic failure, looks like it can’t include files. I have no way of reproducing this unless I can get the hardware and the Ubuntu core RS5. If you have some ideas I could take a look. (Sent from mobile)On Nov 16, 2022, at 00:38, robot-ranger ***@***.***> wrote:﻿
I am trying to build cpp agent on a nanoPi R5S. It has the mfge's custom Ubuntu Core 20.04 on it:
/home/pi/cppagent/agent/cppagent.cpp:28:17: error: ‘mtconnect’ is not a namespace-name
28 | using namespace mtconnect;
|                 ^~~~~~~~~
/home/pi/cppagent/agent/cppagent.cpp: In function ‘int main(int, const char**)’:
/home/pi/cppagent/agent/cppagent.cpp:32:3: error: ‘NAMED_SCOPE’ was not declared in this scope
32 |   NAMED_SCOPE("MAIN");
|   ^~~~~~~~~~~
/home/pi/cppagent/agent/cppagent.cpp:34:3: error: ‘configuration’ has not been declared
34 |   configuration::AgentConfiguration config;
|   ^~~~~~~~~~~~~
/home/pi/cppagent/agent/cppagent.cpp:36:13: error: ‘config’ was not declared in this scope
36 |   int ret = config.main(aArgc, aArgv);
|             ^~~~~~
make[2]: *** [agent/CMakeFiles/agent.dir/build.make:66: agent/CMakeFiles/agent.dir/cppagent.cpp.o] Error 1
make[2]: Leaving directory '/home/pi/cppagent/build'
make[1]: *** [CMakeFiles/Makefile2:166: agent/CMakeFiles/agent.dir/all] Error 2
make[1]: Leaving directory '/home/pi/cppagent/build'
make: *** [Makefile:166: all] Error 2
ERROR: conanfile.py (mtconnect_cppagent/2.0): Error in build() method, line 110
cmake.build()
ConanException: Error 2 while executing cmake --build '/home/pi/cppagent/build' '--' '-j4'

**Comment by robot-ranger** [comment]
That is a little beyond my knowledge level, I will have to ask our external computer wizard dude for some help. The errors seemed oddly basic...

Unfortunately it now seems to be locking up and killing my ssh session ~7% in. Still seems to be running, but cannot re-connect until I reboot.

How 'portable' is the resulting compiled file? Is it specific to hardware? Or could i build on another Ubuntu machine and copy it over? I dont know how to replicate the nanoPi toolchain specifically

**Comment by robot-ranger** [comment]
we have adopted docker and are successfully building the agent using a tweaked Dockerfile from main. 

So unfortunately, I do not have any specific solutions to the above issue we have gone a different direction.
