### ISSUE TITLE
Choose Agent UUID / id / Name

### ISSUE THREAD

**Issue by rwuthric** [mtconnect/cppagent#262]
Hello

I was wondering if there is a way to force the Agent (version 2) to set a specific Agent UUID / id / name ?

Currently the created agent device chooses itself some uuid / id / name
(e.g. uuid = 0b49a3a0-18ca-0139-8748-2cde48001122, id = agent_2cde48001122, name = Agent)

I could not find any info in README.md and was not able to understand from the source code how uuid / id are generated.

Thank you very much

**Comment by wsobel** [comment]
The current agent uuid is a hash of the host and port for the rest interface. It could be possible to add it as a configuration option where you manually create it. The idea is that each agent should have a unique identifier.

**Comment by rwuthric** [comment]
Thank you for the answer. I understand now how the UUID is made in the cppagent and I understand that it is defined in a deterministic way.

What I could not figure out is how to add the configuration option to manually create the agent (and adapter(s)) UUID. In our use-case we have our own nomenclature to attribute UUIDs to agents and adapters. It would be helpful if these could be set manually.

I played with the options `PreserveUUID' and 'UUID' in the cppagent configuration file (top-level and on adapter level) but neither the adapter nor the agent UUID defined in the XML device information model seem to be taken into account by cppagent. Neither can I impose the UUID from the cppagent configuration file. Obviously I must do something wrong.

I am using cppagent 2.0

**Comment by wsobel** [comment]
Is this still a desired feature? We could configure the agent with a specific uuid if there is general consensus this is desired. Otherwise I will close it.

**Comment by rwuthric** [comment]
For our application that would be useful. Currently we use a workaround by overwriting the auto generated UUIDs by the agent.
With this feature we could remove our "hack".

**Comment by rwuthric** [comment]
Looking forward to it. Thank you for amazing work. Your agent implementation saves us really huge amount of work for our applications.
