### ISSUE TITLE
Pages not rendering - Styles problem (v1.8.0.x)

### ISSUE THREAD

**Issue by ag-ctlg** [mtconnect/cppagent#263]
Tested only with versions **1.8.0.2** and **1.8.0.3**

This appears to be a similar problem to #165 

Running on Windows 11, directly from the extracted win64 Agent ZIP. No files changed.
Pages not rendering in any browser.

The console shows the following:
![grafik](https://user-images.githubusercontent.com/99892060/204539096-5023acdc-d55b-4927-aa26-43b3a85ce48c.png)

Is the parameter to the `FileCache::registerFile` incomplete? I suppose the required file is `../styles/old/Streams.xsl`.

**Comment by ag-ctlg** [comment]
I've managed to compile the sources for v1.8.0.3 (commit: 766cbacb80ce40c21eb1e09485bfa8060a41144a)

I had to debug into the XML printer to get the response document for the `/probe` route, then I compared this output to the one produced by v1.7.0.7 and noticed a difference at the top of the response file:

![grafik](https://user-images.githubusercontent.com/99892060/204566625-cfc7b510-06db-4320-9cd9-3df8e5b6f3fa.png)

I commented out the lines 1017 through 1022 in the source file `xml_printer.cpp` (agent_lib)

![grafik](https://user-images.githubusercontent.com/99892060/204567760-32b81607-5b50-4341-a98e-a7812f546964.png)

 and the response rendered correctly in both Edge and Firefox. Even the `/current` route renders error-free in Firefox (which it doesn't with v1.7.0.7).

But of course, all the response pages are rendered as bare XML.

**Comment by wsobel** [comment]
That will remove the process line, but the process line should resolve to a valid file. Can you access /styles/styles.xsl from the browser?

Also, can you attach you configuration directory zipped up?

**Comment by ag-ctlg** [comment]
This is what I used: https://github.com/mtconnect/cppagent/releases/tag/v1.8.0.3

This is what I get when I open up the `/styles/styles.xsl` route:

![Screenshot_20221202_055404](https://user-images.githubusercontent.com/99892060/205312108-948057ed-6143-4a0c-b177-a19451de2072.png)

When I open the developer tools in the browser I can see additional information:
![Screenshot_20221202_055513](https://user-images.githubusercontent.com/99892060/205312282-b4550122-825f-4e91-b210-fe545ccee0e6.png)

Here's a funny thing: I opened the `/styles/styles.xsl` file in Notepad++ with the XMLTools plugin installed and I just clicked on the "Pretty print XML" and saved the file.
![Screenshot_20221202_060430](https://user-images.githubusercontent.com/99892060/205312637-107ce28d-97d3-4da5-a166-6972b877e7bc.png)

I restarted the agent and opened up the root route `localhost:5000` and this time this came out:
![Screenshot_20221202_060119](https://user-images.githubusercontent.com/99892060/205312794-a78494cb-605d-4c8f-80ec-c871fe117c2e.png)


![Screenshot_20221202_060318](https://user-images.githubusercontent.com/99892060/205312818-332d4afe-cb07-46ea-a8bf-85588b4558d0.png)

As you can see the output looks a bit better but still some resources are missing even thought on the Network tab I can see all have been found.

Maybe there is a problem with the Agent's own http server or whatever's serving these files up to the browser?
Btw. we've upgraded directly to the latest Agent version (2.0.0.12) where this problem doesn't occur and the pages are displayed correctly.

**Comment by MRIIOT** [comment]
https://github.com/mtconnect/cppagent/pull/188#issuecomment-1052976423

**Comment by wsobel** [comment]
I’m going to close this as I think it is addressed.
