### ISSUE TITLE
Version 2.0.0.12 - cppagent-2.0.0.12-win32 - Is not a valid Win32

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#264]
I tried to run this version on Windows XP SP3 and Windows XP reports it is not a valid Win32.
It can run on Windows 7/10 x86 without a problem

Thanks

**Comment by wsobel** [comment]
I don't think I build for XP, I think I just built for legacy 32 bit. That would require the 141_xp toolchain and it may be difficult to support since Windows and the compiler has dropped support for XP. I'll need to see if it will still build.

**Comment by hulinning2** [comment]
For Windows XP I use VS2010 to build the application and installer.  Of course, I can still use VS2019 to open the solution created with VS2010.
Thanks

**Comment by wsobel** [comment]
I’m going to close this as I think the question is answered.
