### ISSUE TITLE
Need examples for MQTT configuration

### ISSUE THREAD

**Issue by hobbes1069** [mtconnect/cppagent#265]
The options are listed in the readme but there is insufficient documentation / examples in order to actually implement it.

I would much prefer to publish to a broker rather than poll with KepserverEX.

**Comment by neildes2** [comment]
I have been successful to push device and observation topics upstream using MQTT.  I have a need to use the Agents internal MQTT broker for ingress.   Currently using this and works good with no security.  I've been looking for INGRESS examples with no luck.

Sinks{

	MqttService{
		MqttHost = 127.0.0.1
		MqttPort = 1883
		DeviceTopic = /device/#
		ObservationTopic = /sample/#
		
	}
}

**Comment by neildes2** [comment]
I picked this up in the chatter for implementing with security....

Sinks{

	MqttService{
		MqttHost = 10.100.249.133
		MqttPort = 1883
		DeviceTopic = /device/#
		ObservationTopic = /sample/#
		
		#MqttTls = true
		#MqttCaCert = ca.pem
		#MqttCert = device.crt
		#MqttPrivateKey = device.key
		#MqttClientId = ThingId

		
	}
}

**Comment by hobbes1069** [comment]
That helped a lot. I got it publishing (unsecured) and was even able to map it into KepserverEX, but when I try to use the tags in Tulip they're grayed out and unselectable. Not sure why.

When I try to use Kepserver's MTConnect driver it can't scan the tags. It doesn't like the DTD. Not sure if I'm not properly configuring the path to `MTConnectDevice_1.0.xsd` or not.

**Comment by hobbes1069** [comment]
It seems that two of my agents are using the same client ID for MQTT connections. Shouldn't this be randomly generated? It's causing continuous reconnects.

For now I assume I can update agent.cfg to include a unique `MqttClientId`?

**Comment by wsobel** [comment]
We could generate a random uuid. Currently it is a configuration item. The the following change work:Generate a unique uuid for the client id if not specified. I could use a hash of the IP address of the machine and the port, similar to how I generate the agent uuid for the agent device?(Sent from mobile)On Jan 17, 2023, at 09:25, Richard ***@***.***> wrote:﻿
It seems that two of my agents are using the same client ID for MQTT connections. Shouldn't this be randomly generated? It's causing continuous reconnects.
For now I assume I can update agent.cfg to include a unique MqttClientId?

**Comment by hobbes1069** [comment]
That would be fine. I was thinking something like `cppagent-<HASH>` would be good so I would immediately know which agent is being used. Honestly I wouldn't care if the actual IP address was used. One of the down sides to a MQTT broker is you don't have visibility to where the messages are coming from without examining the log.

**Comment by wsobel** [comment]
I’ll make the changes in the next few days and we can decided what seems the best course of action. I can do this in the dev repo mtconnect/cppagent_dev and we can get see what everyone things is the best course of action. I’ll be cutting a new release soon with changes to support using the agent as a shared library for embedding and easier creation of plugins.
