### ISSUE TITLE
Publish massages into MQTT Broker fails

### ISSUE THREAD

**Issue by benaish** [mtconnect/cppagent#267]
Hi,

I'm trying to configure the agent (2.0.0.12 _RC22) to publish massages into a Greengrass MQTT broker (see configuration below).
The Greengrass MQTT broker expects a ca.pem, certificate and a key in order to accept connections.
I tried to configure the CA and the client certificate (see sinks below), but didn't see an option to configure the key. I think that the connection is refused due to that.

Agent's config in use:

```
AllowPut = true
SchemaVersion = 1.5
Pretty = true
Port = 5222

Adapters {
   F900 {
      SourceDevice = F900
      Url = http://mtconnect:1234/
	 # UsePolling = true

   }
}
   
Sinks {
    MqttService {
       MqttPort = 8883
       MqttHost = MqttServer
	MqttCaCert=ca.pem
	MqttTls=device.crt
	}
}
```

**Comment by benaish** [comment]
Used the following properties to solve the problem:
        MqttPort = 8883
        MqttHost = MqttServer
        MqttTls = true
        MqttCaCert = ca.pem
        MqttCert = device.crt
        MqttPrivateKey = device.key
	MqttClientId = ThingId

As far as i know, currently MqttClientId property is only available in the dev branch

**Comment by wsobel** [comment]
I will be merging the dev and public repos today and create a new build. (Sent from mobile)On Jan 4, 2023, at 00:46, benaish ***@***.***> wrote:﻿
Used the following properties to solve the problem:
MqttPort = 8883
MqttHost = MqttServer
MqttTls = true
MqttCaCert = ca.pem
MqttCert = device.crt
MqttPrivateKey = device.key
MqttClientId = ThingId
As far as i know, currently MqttClientId property is only available in the dev branch
