### ISSUE TITLE
timestamp with HTTP Post

### ISSUE THREAD

**Issue by AndrewDugenske** [mtconnect/cppagent#27]
Seems the Agent doesn't accept timestamp via an HTTP POST.

If this is POSTed to the agent:
http://example.com:5000/VMC-3Axis/sample?Sspeed=15.1&timestamp=2015-12-06T19:51:45.737194Z
the agent clock on receipt is logged by the agent (which is nice when no timestamp is present) vs the uri  parameter

**Comment by wsobel** [comment]
Looks like it. It's easy to add. Please add an issue in the github site and
I'll get it in there this week.

On Monday, December 7, 2015, Andrew Dugenske <notifications@github.com>
wrote:

> Seems the Agent doesn't accept timestamp via an HTTP POST.
>
> If this is POSTed to the agent:
>
> http://example.com:5000/VMC-3Axis/sample?Sspeed=15.1&timestamp=2015-12-06T19:51:45.737194Z
> the agent clock on receipt is logged by the agent (which is nice when no
> timestamp is present) vs the uri parameter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtconnect/cppagent/issues/27>.
>


-- 

Best Regards,
Will Sobel
Chief Strategy Officer/Co-Founder
System Insights, Inc.
2550 9th Street, Suite 102
Berkeley, CA 94710
Direct: 510-684-6400
Tel: +1-855-846-2100 x101
Fax: +1-855-734-3360
http://www.systeminsights.com/
http://www.mtconnect.org/
http://projects.mtconnect.org/

Read our blog "Manufacturing Big Data" at: http://www.systeminsights.com/


The information contained in this electronic mail message and any
attachments hereto is privileged and confidential information intended only
for the use of the individual or entity named above or their designee. If
the reader of this message is not the intended recipient, you are hereby
notified that any dissemination, distribution or copy of this communication
is strictly prohibited. If you have received this communication in error,
please immediately notify us by return message or by telephone, and delete
the original message from your mail system.

**Comment by AndrewDugenske** [comment]
The e-mail came from github :).

**Comment by wsobel** [comment]
Looks like a good idea. Will be in the next version.

**Comment by memelet** [comment]
I see 1.3.0.17 accepting 'timestamp'. Should this be closed?

**Comment by wsobel** [comment]
The time parameter will set the timestamp.

**Comment by memelet** [comment]
Ah, yes, I meant `time` not `timestamp`.
