### ISSUE TITLE
Issue with data stream having **START in MTConnect Agent version 2.1.0.1

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#272]
I sent the following data to MTConnect Tag Application:

**Tag:**
`<DataItem category="EVENT" id="AppAll" name="ApplicationAll" subType="ALL" type="APPLICATION"/>`

**Data:**
_{CAS = ;CAS Model Data = ;Custom API = LCAPI-003P;Easy Modeling = SOECA329U;Excel = ;IT Plaza Application Common = ;Manufacturer = OKUMA;NC Alarm Help = GPA-100E-ENG;NC Control = GNC-101C-P300A;NC Control Message = GNC-101C-ENG-P300A;NC Installer = INST107D;NC Manual = GPM-100B-ENG;Comment = ;Note 1 = ;Special Spec = ;OSP System DVD Version = 01;OSP Type = OSP-P300G;One Touch IGF = [N/A];One Touch IGF Message = [N/A];One Touch IGF Machine Type = ;One-Touch Spreadsheet File Controller = ;One-Touch Spreadsheet File Controller Message = ;One-Touch Spreadsheet File Controller Pre-install Contents = ;One-Touch SpreadSheet Sample Contents = ;P100 Tool = UTY-005B;PLC Control = GA3-Z001A;PLC System  = PLCS300D;PLC System Message = [N/A];Real-time OS = VSYS300M;RealTime OS Driver = VDRV202A

**START;Serial Number = P192431;S/W Production Date = 2015-11-16T15:00:00.0000000Z;S/W Production Number = ;Vertical Function Key = SVFKA403C;Vertical Function Key 2 = ;Vertical Function Key Message = GVFKA404A;Windows System = 6.0.1.P;Windows System DVD Version = 01;}_

**Error:**
It seems that MTConnect Agent is processing the **START data as a command 
2023-01-07T01:41:49.187500Z (0x00001368) [warning] Connector::reader->Connector:
:parseSocketBuffer->Connector::processLine->ShdrAdapter::protocolCommand: Unknow
n command '*start;serial number = p192431;s/w production date = 2015-11-16t15' f
or device 'OKUMA

**Issue:**
However, all tags cannot be reported once this data is sent to MTConnect Agent.
As soon as I stop sending these data or there is **START in the data stream then MTConnect Agent can run as normal.
However, this data is only sent for 1 time and is never changed unless Adapter is started again.  
As a result, all Event and Sample tags become UNAVAILABLE.

 Thanks

**Comment by wsobel** [comment]
Can you attach the data captured from the adapter in a file so I can replay it and determine what is wrong?I need to see exactly what is being sent. ThanksW(Sent from mobile)On Jan 7, 2023, at 09:04, Linh Huynh ***@***.***> wrote:﻿
I sent the following data to MTConnect Tag Application:
Tag:
<DataItem category="EVENT" id="AppAll" name="ApplicationAll" subType="ALL" type="APPLICATION"/>
Data:
_{CAS = ;CAS Model Data = ;Custom API = LCAPI-003P;Easy Modeling = SOECA329U;Excel = ;IT Plaza Application Common = ;Manufacturer = OKUMA;NC Alarm Help = GPA-100E-ENG;NC Control = GNC-101C-P300A;NC Control Message = GNC-101C-ENG-P300A;NC Installer = INST107D;NC Manual = GPM-100B-ENG;Comment = ;Note 1 = ;Special Spec = ;OSP System DVD Version = 01;OSP Type = OSP-P300G;One Touch IGF = [N/A];One Touch IGF Message = [N/A];One Touch IGF Machine Type = ;One-Touch Spreadsheet File Controller = ;One-Touch Spreadsheet File Controller Message = ;One-Touch Spreadsheet File Controller Pre-install Contents = ;One-Touch SpreadSheet Sample Contents = ;P100 Tool = UTY-005B;PLC Control = GA3-Z001A;PLC System  = PLCS300D;PLC System Message = [N/A];Real-time OS = VSYS300M;RealTime OS Driver = VDRV202A
**START;Serial Number = P192431;S/W Production Date = 2015-11-16T15:00:00.0000000Z;S/W Production Number = ;Vertical Function Key = SVFKA403C;Vertical Function Key 2 = ;Vertical Function Key Message = GVFKA404A;Windows System = 6.0.1.P;Windows System DVD Version = 01;}_
Error:
It seems that MTConnect Agent is processing the **START data as a command
2023-01-07T01:41:49.187500Z (0x00001368) [warning] Connector::reader->Connector:
:parseSocketBuffer->Connector::processLine->ShdrAdapter::protocolCommand: Unknow
n command '*start;serial number = p192431;s/w production date = 2015-11-16t15' f
or device 'OKUMA
Issue:
However, all tags cannot be reported once this data is sent to MTConnect Agent.
As soon as I stop sending these data or there is **START in the data stream then MTConnect Agent can run as normal.
However, this data is only sent for 1 time and is never changed unless Adapter is started again.
As a result, all Event and Sample tags become UNAVAILABLE.
Thanks

**Comment by hulinning2** [comment]
Will,
Here is the log file.
[MTConnect.log](https://github.com/mtconnect/cppagent/files/10366972/MTConnect.log)

I notice that the data stream for Application tag is truncated after RealTime OS Driver = VDRV202A
`<Application dataItemId="AppAll" name="ApplicationAll" sequence="155" subType="ALL" timestamp="2023-01-07T18:32:26.030398Z">{CAS = ;CAS Model Data = ;Custom API = LCAPI-003P;Easy Modeling = SOECA329U;Excel = ;IT Plaza Application Common = ;Manufacturer = OKUMA;NC Alarm Help = GPA-100E-ENG;NC Control = GNC-101C-P300A;NC Control Message = GNC-101C-ENG-P300A;NC Installer = INST107D;NC Manual = GPM-100B-ENG;Comment = ;Note 1 = ;Special Spec = ;OSP System DVD Version = 01;OSP Type = OSP-P300G;One Touch IGF = [N/A];One Touch IGF Message = [N/A];One Touch IGF Machine Type = ;One-Touch Spreadsheet File Controller = ;One-Touch Spreadsheet File Controller Message = ;One-Touch Spreadsheet File Controller Pre-install Contents = ;One-Touch SpreadSheet Sample Contents = ;P100 Tool = UTY-005B;PLC Control = GA3-Z001A;PLC System = PLCS300D;PLC System Message = [N/A];Real-time OS = VSYS300M;RealTime OS Driver = VDRV202A</Application>`

However, full data is: 
{CAS = ;CAS Model Data = ;Custom API = LCAPI-003P;Easy Modeling = SOECA329U;Excel = ;IT Plaza Application Common = ;Manufacturer = OKUMA;NC Alarm Help = GPA-100E-ENG;NC Control = GNC-101C-P300A;NC Control Message = GNC-101C-ENG-P300A;NC Installer = INST107D;NC Manual = GPM-100B-ENG;Comment = ;Note 1 = ;Special Spec = ;OSP System DVD Version = 01;OSP Type = OSP-P300G;One Touch IGF = [N/A];One Touch IGF Message = [N/A];One Touch IGF Machine Type = ;One-Touch Spreadsheet File Controller = ;One-Touch Spreadsheet File Controller Message = ;One-Touch Spreadsheet File Controller Pre-install Contents = ;One-Touch SpreadSheet Sample Contents = ;P100 Tool = UTY-005B;PLC Control = GA3-Z001A;PLC System  = PLCS300D;PLC System Message = [N/A];Real-time OS = VSYS300M;RealTime OS Driver = VDRV202A

**START;Serial Number = P192431;S/W Production Date = 2015-11-16T15:00:00.0000000Z;S/W Production Number = ;Vertical Function Key = SVFKA403C;Vertical Function Key 2 = ;Vertical Function Key Message = GVFKA404A;Windows System = 6.0.1.P;Windows System DVD Version = 01;}

Thanks

**Comment by wsobel** [comment]
The issue is this sequence:

```
2023-01-07T18:32:16.0539484Z|ApplicationAll|{CAS = ;CAS Model Data = ;Custom API = LCAPI-003P;Easy Modeling = SOECA329U;Excel = ;IT Plaza Application Common = ;Manufacturer = OKUMA;NC Alarm Help = GPA-100E-ENG;NC Control = GNC-101C-P300A;NC Control Message = GNC-101C-ENG-P300A;NC Installer = INST107D;NC Manual = GPM-100B-ENG;Comment = ;Note 1 = ;Special Spec = ;OSP System DVD Version = 01;OSP Type = OSP-P300G;One Touch IGF = [N/A];One Touch IGF Message = [N/A];One Touch IGF Machine Type = ;One-Touch Spreadsheet File Controller = ;One-Touch Spreadsheet File Controller Message = ;One-Touch Spreadsheet File Controller Pre-install Contents = ;One-Touch SpreadSheet Sample Contents = ;P100 Tool = UTY-005B;PLC Control = GA3-Z001A;PLC System  = PLCS300D;PLC System Message = [N/A];Real-time OS = VSYS300M;RealTime OS Driver = VDRV202A

**START;Serial Number = P192431;S/W Production Date = 2015-11-16T15:00:00.0000000Z;S/W Production Number = ;Vertical Function Key = SVFKA403C;Vertical Function Key 2 = ;Vertical Function Key Message = GVFKA404A;Windows System = 6.0.1.P;Windows System DVD Version = 01;}
```

```
0013660        O   S       D   r   i   v   e   r       =       V   D   R
0013700    V   2   0   2   A  \r  \n  \r  \n   *   *   S   T   A   R   T
0013720    ;   S   e   r   i   a   l       N   u   m   b   e   r       =
0013740        P   1   9   2   4   3   1   ;   S   /   W       P   r   o
```

There is a `<CR><NL><CR><NL>` sequence before the `**START` that would cause the tokenizer issues since the line is split by `<NL>` and the sequence has no terminating `}` on the first line.

 It will read this as: 

Line 1:
```
{CAS = ;CAS Model Data = ;Custom API = LCAPI-003P;Easy Modeling = SOECA329U;Excel = ;IT Plaza Application Common = ;Manufacturer = OKUMA;NC Alarm Help = GPA-100E-ENG;NC Control = GNC-101C-P300A;NC Control Message = GNC-101C-ENG-P300A;NC Installer = INST107D;NC Manual = GPM-100B-ENG;Comment = ;Note 1 = ;Special Spec = ;OSP System DVD Version = 01;OSP Type = OSP-P300G;One Touch IGF = [N/A];One Touch IGF Message = [N/A];One Touch IGF Machine Type = ;One-Touch Spreadsheet File Controller = ;One-Touch Spreadsheet File Controller Message = ;One-Touch Spreadsheet File Controller Pre-install Contents = ;One-Touch SpreadSheet Sample Contents = ;P100 Tool = UTY-005B;PLC Control = GA3-Z001A;PLC System  = PLCS300D;PLC System Message = [N/A];Real-time OS = VSYS300M;RealTime OS Driver = VDRV202A
```

Line 2:
```

```

Line 3:
```
**START;Serial Number = P192431;S/W Production Date = 2015-11-16T15:00:00.0000000Z;S/W Production Number = ;Vertical Function Key = SVFKA403C;Vertical Function Key 2 = ;Vertical Function Key Message = GVFKA404A;Windows System = 6.0.1.P;Windows System DVD Version = 01;}
```

Can you suppress the sequence before the `**START`?

**Comment by hulinning2** [comment]
That works
Thanks
