### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#273]
a few of our v2.1 agents failed to start.  Generating error "Loading configuration from:"/MTC_Agent/agent.cfg"Segmentation fault (core dumped)"

Everything points to cfg file.  but when I run locally, the agent runs.

[agent.cfg.txt](https://github.com/mtconnect/cppagent/files/10701823/agent.cfg.txt)

**Comment by wsobel** [comment]
Can you pls upload the other files as well. The device xml and the other directories. I want to make sure it was not some other content that could have caused the issue. 

Thanks
W

**Comment by neildes2** [comment]
[Uploading V2.0.0.11 - Copy.zip…]()

**Comment by wsobel** [comment]
The zip file doesn't seem to link to anything. Please upload again. - W

**Comment by neildes2** [comment]
[V2.0.0.11 - Copy.zip](https://github.com/mtconnect/cppagent/files/10710963/V2.0.0.11.-.Copy.zip)

**Comment by wsobel** [comment]
Thanks, got it. - W

**Comment by wsobel** [comment]
i'm trying to reproduce, but it works fine. I assume the diff is the ruby script. 

Can you send me that? it is probably something in the initialization.

**Comment by neildes2** [comment]
Issue resolved.   Agent.cfg file corrupted.  I opened and saved in notepad++.  agent started.

**Comment by neildes2** [comment]
Issue resolved
