### ISSUE TITLE
JSON MTConnectStreams response document does not include device attributes.

### ISSUE THREAD

**Issue by scottmwyant** [mtconnect/cppagent#274]
Agent v2.0.0.12, which I realize is not the latest.

The MTConnectDevices response document includes multiple devices, as expected:

![image](https://user-images.githubusercontent.com/29161635/219623770-15e7bef0-5e75-4def-b807-5c1f209e3123.png)

The MTConnectStreams response document does include multiple objects in the `DeviceStream` array but, those objects each only contain a single key, `ComponentStream`.

I expect each object in the `DeviceStream` array to contain three keys: `name`, `uuid`, and `ComponentStream`.

![image](https://user-images.githubusercontent.com/29161635/219624543-960bb367-486d-4434-a369-bd85fdab0d92.png)

I did a `ctrl+f` search to find the device uuid and they are not in the document.

I also noticed that the JSON response does not include the `DeviceStream` named "Agent", as the XML response does.  Didn't notice that right away, as I'm used to looking at the [2] CNCs.  Maybe that would pop in if I requested more of the buffer.

**Comment by wsobel** [comment]
This may be a bug. I’ll check it out. ThanksW(Sent from mobile)On Feb 17, 2023, at 16:32, Scott M. Wyant ***@***.***> wrote:﻿
Agent v2.0.0.12, which I realize is not the latest.
The MTConnectDevices response document includes multiple devices, as expected:

The MTConnectStreams response document does include multiple objects in the DeviceStream array but, those objects each only contain a single key, ComponentStream.
I expect each object in the DeviceStream array to contain three keys: name, uuid, and ComponentStream.

I did a ctrl+f search to find the device uuid and they are not in the document.

**Comment by wsobel** [comment]
Fixed in release 2.1.0.5
