### ISSUE TITLE
JSON MTConnectStreams response inconsistent use of array

### ISSUE THREAD

**Issue by scottmwyant** [mtconnect/cppagent#275]
Agent v2.0.0.12

This is probably more of a question initially, a bug only if this is not the intended behavior.

The `ToolNumber` shown here is a key in an `Events` object (within a ComponentStream).  Usually, an event type will be associated with multiple observations, so naturally, we get an array.  I'm questioning the behavior when there is only one observation; the observation is returned as a scalar, but I would expect a single-element array.

Actual:

```json
"ToolNumber": {
    "dataItemId": "cnc2_p7_tool_num",
    "sequence": 2747897,
    "timestamp": "2023-02-17T04:32:48.035Z",
    "value": "1"
},
```

Expected:

```json
"ToolNumber": [
    {
        "dataItemId": "cnc2_p7_tool_num",
        "sequence": 2747897,
        "timestamp": "2023-02-17T04:32:48.035Z",
        "value": "1"
    }
],
```

**Comment by wsobel** [comment]
Did you check the latest version?(Sent from mobile)On Feb 17, 2023, at 18:05, Scott M. Wyant ***@***.***> wrote:﻿
Agent v2.0.0.12
This is probably more of a question initially, a bug only if this is not the intended behavior.
The ToolNumber shown here is a key in an Events object (within a ComponentStream).  Usually, an event type will be associated with multiple observations, so the observations appear in an array.  It appears when there is only one observation, it's not in a 1-element array.
Actual:
"ToolNumber": {
    "dataItemId": "cnc2_p7_tool_num",
    "sequence": 2747897,
    "timestamp": "2023-02-17T04:32:48.035Z",
    "value": "1"
},
Expected:
"ToolNumber": [
    {
        "dataItemId": "cnc2_p7_tool_num",
        "sequence": 2747897,
        "timestamp": "2023-02-17T04:32:48.035Z",
        "value": "1"
    }
],

**Comment by scottmwyant** [comment]
I'm seeing the same behavior on the latest version.  I used Postman to query the v2.0.1.1 agent in the Mazak test bed.

---

I started by looking at the Events in the buffer:

```
http://mtconnect.mazakcorp.com:5719/sample?path=//DataItem[@category="EVENT"]&count=4096
```

and found only 1 event being reported: 

```xml
<DataItem category="EVENT" id="maintcheck" representation="TABLE" type="MAINTENANCE_LIST" />
```

Sent a few requests  using 'From' parameter with a value of the 'lastSequence'.  Got a few empty documents, as expected, then I got a response with a single observation and the observation is presented as a scalar value.

```
http://mtconnect.mazakcorp.com:5719/sample?path=//DataItem[@category="EVENT"]&count=4096&from=1694286
```

```javascript
        "Streams": {
            "DeviceStream": {
                "ComponentStream": {
                    "Events": {
                        // I think this next line should be an array not an object.  Even when there 
                        // happens to be a single observation of the 'MaintenanceListTable' type.  
                        "MaintenanceListTable": {
                            "count": 28,
                            "dataItemId": "maintcheck",
                            "sequence": 1694440,
                            "timestamp": "2023-02-17T15:16:53.742393Z",
                            "value": { 
```

I suppose if you use the id directly, you could also query for a single observation:
```
http://mtconnect.mazakcorp.com:5719/sample?path=//DataItem[@id="maintcheck"]&count=1
```

**Comment by scottmwyant** [comment]
@wsobel is this a bug or the intended behavior?

**Comment by wsobel** [comment]
I’m a bit confused about what behavior you’re asking about. There are multiple questions in the post.

* Version 2 of the json representation use arrays when more than one item and an object when there is only one.
* Depending on how many events have been posted after the last sequence, you may only get one. Would need to see the rest of the data to say if this is correct.

**Comment by scottmwyant** [comment]
You've answered my question.

> _Version 2 of the json representation use arrays when more than one item and an object when there is only one._

Since we've established the intent, this "issue" is no longer a question, and isn't a bug report either but, I suppose a very minor feature request (preference).

It's awkward to me that the json representation could be either an object or an array.  I expected it to always be an array, if there is one item then it's an array with length of 1... but as you've clarified, that's not actually how it works.

I realize this is more of a stylistic choice than anything else. Simple enough to code around now that I understand the output type.

I'm good to close this.

**Comment by wsobel** [comment]
Version 1.0 had an array and repeated the object inside the array. The current was to reduce the repetition.

We could always use an array, regardless of 1 or more objects. This would need to be checked with the SC.

**Comment by wsobel** [comment]
Please consider participating with the SC to give you opinions.

**Comment by wsobel** [comment]
Please get back if this is still and issue. If not, I will close.
