### ISSUE TITLE
Windows x64 build issue - 'gzip' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mnoomnoo** [mtconnect/cppagent#276]
I'm attempting to build cppagent on 64 bit Windows, but during execution of conan install I get the error 'gzip' is not recognized as an internal or external command.
I installed git, cmake, conan, and ruby on my machine

Here are the steps im using to produce the issue

1. python -m pip install --upgrade pip
2. python -m pip install conan
3. I clone the cppagent repo into a folder under Documents
4. I CD into the cppagent repo folder
5. conan export conan\mqtt_cpp
6. conan export conan\mruby
7. I launch a developer PowerShell for VS2022 and navigate to the cppagent repo folder
8.  conan install . -if build -s build_type=Release --build=missing -pr conan/profiles/vs64
After running conan install it starts installing dependencies until it fails with the message:  

> extracting onigmo-6.2.0
'gzip' is not recognized as an internal or external command,
operable program or batch file.
rake aborted!
cmd /c "copy /Y win32 > NUL" failed
C:/Users/UserName/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/repos/host/mruby-onig-regexp/mrbgem.rake:47:in `run_command'
C:/Users/UserName/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/repos/host/mruby-onig-regexp/mrbgem.rake:72:in `block (2 levels) in bundle_onigmo'
C:/Users/UserName/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/repos/host/mruby-onig-regexp/mrbgem.rake:56:in `chdir'
C:/Users/UserName/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/repos/host/mruby-onig-regexp/mrbgem.rake:56:in `block in bundle_onigmo'
Tasks: TOP => default => all => gensym => C:/Users/UserName/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/host/presym => C:/Users/UserName/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/host/mrbgems/mruby-onig-regexp/src/mruby_onig_regexp.pi => C:/Users/UserName/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/repos/host/mruby-onig-regexp/src/mruby_onig_regexp.c => C:/Users/UserName/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/host/mrbgems/mruby-onig-regexp/onigmo-6.2.0/build_x64/onigmo_s.lib
(See full trace by running task with --trace)
mruby/3.1.0:
mruby/3.1.0: ERROR: Package '871c6303207aa1b539e682559d0b5180e15f0c30' build failed
mruby/3.1.0: WARN: Build folder C:\Users\UserName\.conan\data\mruby\3.1.0\_\_\build\871c6303207aa1b539e682559d0b5180e15f0c30
ERROR: mruby/3.1.0: Error in build() method, line 129
cwd=self._mruby_source)
ConanException: Error 1 while executing rake MRUBY_CONFIG=C:\Users\UserName\.conan\data\mruby\3.1.0\_\_\build\871c6303207aa1b539e682559d0b5180e15f0c30\mruby_source\build_config\mtconnect.rb

I tried the conan install command again but with the -o with_ruby=False flag. I get the same error. I looked for gzip installer for Windows but didn't find much

Here is my version info:
Python 3.11.0
cmake version 3.25.1
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x64-mingw-ucrt]
Conan version 1.59.0

Thanks,
Let me know if I can provide anymore information

**Comment by wsobel** [comment]
Thanks for the report. I will check if it needs to be added as a tool required. I believe zlib installs it for other builds. I’m not sure what has changed. If you want, you can download the prebuilt version for now.BestW(Sent from mobile)On Feb 20, 2023, at 01:46, O B ***@***.***> wrote:﻿
I'm attempting to build cppagent on 64 bit Windows, but during execution of conan install I get the error 'gzip' is not recognized as an internal or external command.
I installed git, cmake, conan, and ruby on my machine
Here are the steps im using to produce the issue

python -m pip install --upgrade pip
python -m pip install conan
I clone the cppagent repo into a folder under Documents
I CD into the cppagent repo folder
conan export conan\mqtt_cpp
conan export conan\mruby
I launch a developer PowerShell for VS2022 and navigate to the cppagent repo folder
conan install . -if build -s build_type=Release --build=missing -pr conan/profiles/vs64
After running conan install it starts installing dependencies until it fails with the message:


extracting onigmo-6.2.0
'gzip' is not recognized as an internal or external command,
operable program or batch file.
rake aborted!
cmd /c "copy /Y win32 > NUL" failed
C:/Users/UserName/.conan/data/mruby/3.1.0///build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/repos/host/mruby-onig-regexp/mrbgem.rake:47:in run_command' C:/Users/UserName/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/repos/host/mruby-onig-regexp/mrbgem.rake:72:in block (2 levels) in bundle_onigmo'
C:/Users/UserName/.conan/data/mruby/3.1.0///build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/repos/host/mruby-onig-regexp/mrbgem.rake:56:in chdir' C:/Users/UserName/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/repos/host/mruby-onig-regexp/mrbgem.rake:56:in block in bundle_onigmo'
Tasks: TOP => default => all => gensym => C:/Users/UserName/.conan/data/mruby/3.1.0///build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/host/presym => C:/Users/UserName/.conan/data/mruby/3.1.0///build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/host/mrbgems/mruby-onig-regexp/src/mruby_onig_regexp.pi => C:/Users/UserName/.conan/data/mruby/3.1.0///build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/repos/host/mruby-onig-regexp/src/mruby_onig_regexp.c => C:/Users/UserName/.conan/data/mruby/3.1.0///build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/host/mrbgems/mruby-onig-regexp/onigmo-6.2.0/build_x64/onigmo_s.lib
(See full trace by running task with --trace)
mruby/3.1.0:
mruby/3.1.0: ERROR: Package '871c6303207aa1b539e682559d0b5180e15f0c30' build failed
mruby/3.1.0: WARN: Build folder C:\Users\UserName.conan\data\mruby\3.1.0__\build\871c6303207aa1b539e682559d0b5180e15f0c30
ERROR: mruby/3.1.0: Error in build() method, line 129
cwd=self._mruby_source)
ConanException: Error 1 while executing rake MRUBY_CONFIG=C:\Users\UserName.conan\data\mruby\3.1.0__\build\871c6303207aa1b539e682559d0b5180e15f0c30\mruby_source\build_config\mtconnect.rb

I tried the conan install command again but with the -o with_ruby=False flag. I get the same error. I looked for gzip installer for Windows but didn't find much
Here is my version info:
Python 3.11.0
cmake version 3.25.1
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x64-mingw-ucrt]
Conan version 1.59.0
Thanks,
Let me know if I can provide anymore information

**Comment by mnoomnoo** [comment]
I was working on trying to build cppagent over the weekend and discovered a few things related to this issue.
The flag `-o with_ruby=False` was the issue, I had to use `-o without_ruby=True` for the conan install command to work.

**Comment by wsobel** [comment]
Gzip is required for onigarumi unpack. I think it is part of the normal git bash install, so it’s interesting that it is not present on the machine. (Sent from mobile)On Feb 27, 2023, at 20:31, O B ***@***.***> wrote:﻿
I was working on trying to build cppagent over the weekend and discovered a few things related to this issue.
The flag -o with_ruby=False was the issue, I had to use -o without_ruby=True for the conan install command to work.

**Comment by wsobel** [comment]
I'm going to address this during the upgrade to conan version 2.0 since it has a new way of handling build requirements. It should be done this week.

**Comment by wsobel** [comment]
I'm installing and testing on a clean Windows 10 VM. Will see what is required to support gzip dependency.

**Comment by wsobel** [comment]
Did you install Ruby using the ruby intaller? As part of the installation process it installs msys64 and gzip is located in the following directory:

```
c:\msys64\usr\bin\gzip.exe
```

**Comment by mnoomnoo** [comment]
> Did you install Ruby using the ruby installer? As part of the installation process, it installs msys64, and gzip is located in the following directory:
> 
> ```
> c:\msys64\usr\bin\gzip.exe
> ```

I installed Ruby using the Ruby Installer from link in the cppagent documentation: https://rubyinstaller.org/
I ran the Ruby Installer again and checked the option to install the MSYS2 toolchain and I now have gzip.exe at: `C:\Ruby32-x64\msys64\usr\bin`
I ran: `conan install . -if build -s build_type=Release --build=missing -pr conan/profiles/vs64` and get the same error: 

> extracting onigmo-6.2.0
'gzip' is not recognized as an internal or external command,
operable program or batch file.
rake aborted!

**Comment by wsobel** [comment]
Try adding `c:\msys64\usr\bin` to your path(Sent from mobile)On Mar 4, 2023, at 09:10, O B ***@***.***> wrote:﻿

Did you install Ruby using the ruby installer? As part of the installation process, it installs msys64, and gzip is located in the following directory:
c:\msys64\usr\bin\gzip.exe


I installed Ruby using the Ruby Installer from link in the cppagent documentation: https://rubyinstaller.org/
I ran the Ruby Installer again and checked the option to install the MSYS2 toolchain and I now have gzip.exe at: C:\Ruby32-x64\msys64\usr\bin
I ran: conan install . -if build -s build_type=Release --build=missing -pr conan/profiles/vs64 and get the same error:

extracting onigmo-6.2.0
'gzip' is not recognized as an internal or external command,
operable program or batch file.
rake aborted!

**Comment by mnoomnoo** [comment]
Adding `C:\Ruby32-x64\msys64\usr\bin` to my PATH environment variable got me past the gzip issue.
After running the conan install command I get a series of LNK2019: unresolved external symbol errors:

> LD    build/host/bin/mruby.exe
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_error_code_to_str referenced in function onig_match_common
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_new referenced in function onig_regexp_initialize
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_free referenced in function onig_regexp_free
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_search referenced in function onig_match_common
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_region_new referenced in function create_onig_region
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_region_free referenced in function match_data_free
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_region_copy referenced in function match_data_copy
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_name_to_backref_number referenced in function append_replace_str
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_get_encoding referenced in function onig_regexp_inspect
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_get_options referenced in function onig_regexp_casefold_p
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_version referenced in function onig_regexp_version
libmruby.lib(mruby_onig_regexp.obj) : error LNK2001: unresolved external symbol OnigEncodingASCII
libmruby.lib(mruby_onig_regexp.obj) : error LNK2001: unresolved external symbol OnigEncodingUTF_8
libmruby.lib(mruby_onig_regexp.obj) : error LNK2001: unresolved external symbol OnigSyntaxRuby
libmruby.lib(mruby_onig_regexp.obj) : error LNK2001: unresolved external symbol OnigDefaultSyntax
C:\Users\Desky2\.conan\data\mruby\3.1.0\_\_\build\871c6303207aa1b539e682559d0b5180e15f0c30\mruby_source\build\host\bin\mruby.exe : fatal error LNK1120: 15 unresolved externals
rake aborted!
Command failed with status (96): [link.exe /NOLOGO /DEBUG /INCREMENTAL:NO /O...]
C:/Users/Desky2/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/lib/mruby/build/command.rb:37:in `_run'
C:/Users/Desky2/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/lib/mruby/build/command.rb:217:in `run'
C:/Users/Desky2/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/tasks/bin.rake:17:in `block (4 levels) in <top (required)>'
C:/Users/Desky2/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/Rakefile:42:in `block in <top (required)>'
Tasks: TOP => build => C:/Users/Desky2/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/bin/mruby.exe => C:/Users/Desky2/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/host/bin/mruby.exe
(See full trace by running task with --trace)
mruby/3.1.0:
mruby/3.1.0: ERROR: Package '871c6303207aa1b539e682559d0b5180e15f0c30' build failed
mruby/3.1.0: WARN: Build folder C:\Users\Desky2\.conan\data\mruby\3.1.0\_\_\build\871c6303207aa1b539e682559d0b5180e15f0c30
ERROR: mruby/3.1.0: Error in build() method, line 128
        self.run("rake MRUBY_CONFIG=%s" % self.build_config,
        ConanException: Error 1 while executing rake MRUBY_CONFIG=C:\Users\Desky2\.conan\data\mruby\3.1.0\_\_\build\871c6303207aa1b539e682559d0b5180e15f0c30\mruby_source\build_config\mtconnect.rb

**Comment by wsobel** [comment]
You may need to force rebuilding of the mruby package. (Sent from mobile)On Mar 4, 2023, at 11:18, O B ***@***.***> wrote:﻿
Adding C:\Ruby32-x64\msys64\usr\bin to my PATH environment variable got me past the gzip issue.
After running the conan install command I get a series of LNK2019: unresolved external symbol errors:

LD    build/host/bin/mruby.exe
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_error_code_to_str referenced in function onig_match_common
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_new referenced in function onig_regexp_initialize
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_free referenced in function onig_regexp_free
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_search referenced in function onig_match_common
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_region_new referenced in function create_onig_region
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_region_free referenced in function match_data_free
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_region_copy referenced in function match_data_copy
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_name_to_backref_number referenced in function append_replace_str
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_get_encoding referenced in function onig_regexp_inspect
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_get_options referenced in function onig_regexp_casefold_p
libmruby.lib(mruby_onig_regexp.obj) : error LNK2019: unresolved external symbol onig_version referenced in function onig_regexp_version
libmruby.lib(mruby_onig_regexp.obj) : error LNK2001: unresolved external symbol OnigEncodingASCII
libmruby.lib(mruby_onig_regexp.obj) : error LNK2001: unresolved external symbol OnigEncodingUTF_8
libmruby.lib(mruby_onig_regexp.obj) : error LNK2001: unresolved external symbol OnigSyntaxRuby
libmruby.lib(mruby_onig_regexp.obj) : error LNK2001: unresolved external symbol OnigDefaultSyntax
C:\Users\Desky2.conan\data\mruby\3.1.0__\build\871c6303207aa1b539e682559d0b5180e15f0c30\mruby_source\build\host\bin\mruby.exe : fatal error LNK1120: 15 unresolved externals
rake aborted!
Command failed with status (96): [link.exe /NOLOGO /DEBUG /INCREMENTAL:NO /O...]
C:/Users/Desky2/.conan/data/mruby/3.1.0///build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/lib/mruby/build/command.rb:37:in _run' C:/Users/Desky2/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/lib/mruby/build/command.rb:217:in run'
C:/Users/Desky2/.conan/data/mruby/3.1.0///build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/tasks/bin.rake:17:in block (4 levels) in <top (required)>' C:/Users/Desky2/.conan/data/mruby/3.1.0/_/_/build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/Rakefile:42:in block in <top (required)>'
Tasks: TOP => build => C:/Users/Desky2/.conan/data/mruby/3.1.0///build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/bin/mruby.exe => C:/Users/Desky2/.conan/data/mruby/3.1.0///build/871c6303207aa1b539e682559d0b5180e15f0c30/mruby_source/build/host/bin/mruby.exe
(See full trace by running task with --trace)
mruby/3.1.0:
mruby/3.1.0: ERROR: Package '871c6303207aa1b539e682559d0b5180e15f0c30' build failed
mruby/3.1.0: WARN: Build folder C:\Users\Desky2.conan\data\mruby\3.1.0__\build\871c6303207aa1b539e682559d0b5180e15f0c30
ERROR: mruby/3.1.0: Error in build() method, line 128
self.run("rake MRUBY_CONFIG=%s" % self.build_config,
ConanException: Error 1 while executing rake MRUBY_CONFIG=C:\Users\Desky2.conan\data\mruby\3.1.0__\build\871c6303207aa1b539e682559d0b5180e15f0c30\mruby_source\build_config\mtconnect.rb

**Comment by mnoomnoo** [comment]
I deleted all the folders and files in `C:\Users\UserName\.conan\data` which contains the mruby sources and libraries and ran the command: `conan install . -if build -s build_type=Release --build=missing -pr conan/profiles/vs64` and got the same LNK2019: unresolved external symbol errors.

I also tried the following conan install command to try and force all the dependecies to build from sources:
`conan install . -if build -s build_type=Release --build -pr conan/profiles/vs64` and got the same LNK2019: unresolved external symbol errors.

**Comment by wsobel** [comment]
Can you upload your build logs?

**Comment by mnoomnoo** [comment]
The attached file is the output from the conan install command from cppagent documentation: `conan install . -if build -s build_type=Release --build=missing -pr conan/profiles/vs64`

[install_command_from_docs.txt](https://github.com/mtconnect/cppagent/files/10926862/install_command_from_docs.txt)

**Comment by wsobel** [comment]
I'll try to reproduce this on a clean build environment.

**Comment by wsobel** [comment]
Expanded archive for onigmo-6.2.0 so gzip and tar are not required for build. Includes configure scripts and changed gem build to copy files instead of expanding.

**Comment by wsobel** [comment]
Has this issue been resolved. Since expanding the archive, I think it is fixed. Please get back if this is still a problem, otherwise I will close.

**Comment by mnoomnoo** [comment]
I haven't had a chance to take another look with the most recent commits. I'll test it ASAP and let you know.

**Comment by mnoomnoo** [comment]
I tried the most recent version of the master branch and followed the build instructions from the README.md and I'm getting linking errors. I had to specify conan version 1.59 to get past the `conan export` commands.

Here is the log from the conan install command: `conan install . -if build -s build_type=Release --build=missing -pr conan/profiles/vs64`

[Conan-159-Install.txt](https://github.com/mtconnect/cppagent/files/11327257/Conan-159-Install.txt)

**Comment by mnoomnoo** [comment]
This can be closed. I figured out what I was doing wrong.
I've been using Windows Terminal with the default `Developer Powershell for VS2022` profile for building cppagent and that hasn't been working correctly. I tired the `x64 Native Tools Command Prompt for VS 2022` from the windows start menu and used that cmd prompt to build cppagent and it worked. 

Looks like the Windows Terminal application's default `Developer Powershell for VS2022` profile doesn't do something that the `x64 Native Tools Command Prompt for VS 2022` from the Windows start menu does.
