### ISSUE TITLE
[question] how to leverage the agent arch

### ISSUE THREAD

**Issue by emaxerrno** [mtconnect/cppagent#277]
hi 👋  everyone. 

i read the c++ code which seems relatively straight forward to understand. as someone entirely new to all of machining was hoping to understand the architecture of the code and things you can teach the engine. 

from the diagrams online you have a [device] <--> [agent] --> [downstream systems like elk]
(pointers to docs, or parts of the code would be great too. also, feel free to close the tix if this is the wrong forum)

I was reading the haas language and wondered if there was a python or some rust way to build a simulator so i could play around with some ideas (never owned a haas machine) for what programming in that environment would feel like and this repo is as close as i found. 

1. can you control a haas machine from a computer remotely and push code to the machine itself via this agent? i.e.: instead of collecting (reading) can you send a program to a haas machine (write) and have it automatically start. What part of the code base or what protocol can i read to figure that out? pointers would be fine.  

2. can one write a program and have it spec'ed in a universal language like python and have it translate to the multiple flavors like fanuc or haas or X so that one could write programs and reason through them with higher level tooling. 

3. in physical world, how is this agent connected to these cnc machines? do the machines connect to the wifi and you just simply go and read a socket with a protocol specific to each vendor or do you plug them to the network with some ethernet chord, how does this work in the physical world? (sorry, new to machining, and looking to learn)

thanks!

**Comment by emaxerrno** [comment]
ah i see. so the haas machines already listen on a few tcp ports. https://www.haascnc.com/service/troubleshooting-and-how-to/how-to/machine-data-collection---ngc.html

and the protocol is a simple plain text format, so you send a \r\n on either Q or E commands and you get the xml body you can parse w/ the data.

 but doesn't look like I can send** it G,M,T commands. looks like you program it via filenames (long functions become filenames - subprograms) if anyone reversed engineered some of this and figured out a way to send it, would love a link to read. I'll close the ticket.

**Comment by wsobel** [comment]
In general there would be an adapter that uses the Q commands to send requests to the controller. The adapter parses the responses and then formats the data by converting units and controlled vocabularies for states. 

That is the primary set of concerns. The agent reads data from a socket and then formats response docs when REST requests are made.

**Comment by wsobel** [comment]
If there is no further discussion on this issue, I can close it.

**Comment by wsobel** [comment]
This appears to be closed.
