### ISSUE TITLE
[Issue] Conan Build Issue For MacOS

### ISSUE THREAD

**Issue by FullStackPhysics** [mtconnect/cppagent#278]
Hi,

I have discovered a bug in the process of building the agent on MacOS. When trying to export conan/mqtt_cpp I was faced with the error below. I wanted to leave this here in case anybody else runs into this issue in the future.

**Problem**

`ERROR: Error loading conanfile at '/<path>/<to>/<cppagent>conan/mqtt_cpp/conanfile.py': Unable to load conanfile in /<path>/<to>/<cppagent>/conan/mqtt_cpp/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/<path>/<to>/<cppagent>/conan/mqtt_cpp/conanfile.py", line 1, in <module>
    from conans import ConanFile, tools
ImportError: cannot import name 'ConanFile' from 'conans' (/usr/local/lib/python3.11/site-packages/conans/__init__.py)`

Steps to reproduce:
1. Install Brew and Xcode (if not already installed)
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
xcode-select —install`
2. Setup the build
`brew install git
brew install cmake
pip3 install conan`
3. Download Source
`git clone https://github.com/mtconnect/cppagent.git`
4. Install dependencies
`conan export conan/mqtt_cpp`

A similar error occurs in the next step of `conan export conan/cruby` seen below:

`ERROR: Error loading conanfile at '/<path>/<to>/<cppagent>/conan/mruby/conanfile.py': Unable to load conanfile in /<path>/<to>/<cppagent>/conan/mruby/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/<path>/<to>/<cppagent>/conan/mruby/conanfile.py", line 1, in <module>
    from conans import ConanFile, CMake, tools
ImportError: cannot import name 'ConanFile' from 'conans' (/usr/local/lib/python3.11/site-packages/conans/__init__.py)`

**Solution:**

Per [this comment](https://github.com/audacity/audacity/issues/4360#issuecomment-1445366169) do not use the latest version of conan to build the package as the "-if" statement is not functional yet in 2.0. Stick to 1.59.0

Hope this helps someone!

**Comment by wsobel** [comment]
The issue is with conan and the release of version 2.0 before all the packages have been update. 

Version 2.0 is a breaking change and I am working on updating the conan build system to support what we need. I'll should be done soon, there are major changes required.

The way solution for now is as follows:

```
pip install --force-reinstall -v "conan==1.59.0"
```

This will reinstall conan with version 1.59.0 and the build will work as before. I will update the documentation of I cannot fix the build system in the next few days.
