### ISSUE TITLE
RFE: Include client IP Address in MQTT payload

### ISSUE THREAD

**Issue by hobbes1069** [mtconnect/cppagent#279]
The great thing about MQTT is I don't have to care what the IP address of the device is, at least when everything is working, but it would be very nice if this information was published along with the other datas. It can be helpful for troubleshooting. 

Currently I'm underscore "encoding" it in the MQTT client name, but this is less than ideal for DHCP clients.

I'm open as to where exactly this would go.

**Comment by wsobel** [comment]
I'd be happy to discuss this in the MTConnect Agent WG. Are you a member of the MTConnect SC?

**Comment by hobbes1069** [comment]
Not as of yet, but more than happy to be.

**Comment by wsobel** [comment]
It's free; just go to the [Register](https://projects.mtconnect.org/account/register) link on the projects site. It requires you to agree to the IP policy as an individual or a company. The IP policy states that you won't contribute anything you have copyrighted or patented.

That's it.

**Comment by robot-ranger** [comment]
@wsobel - I know github issues arent exactly the correct forum, but the topic of mtc WG is relevant:

We are members of the SC, but we would like to join the robotics WG. I have emailed info@mtconnect a few times - is there a better channel to get involved in robotics WG?

**Comment by wsobel** [comment]
Send me a direct message at will@metalogi.io and I'll get you connected with the correct people.
