### ISSUE TITLE
Alternative POST Error Message

### ISSUE THREAD

**Issue by AndrewDugenske** [mtconnect/cppagent#28]
If data is posted to the agent, and AllowPut = yes is not included in the config file, the following error is returned:
<Error errorCode="UNSUPPORTED">Only the HTTP GET request is supported</Error>

Recommend an error message something like this:
“This agent is not configured to accept HTTP POST requests.”
to better guide users.

**Comment by wsobel** [comment]
The error handling has been addressed.
