### ISSUE TITLE
Public Release MTConnect Agent 2.1.0.6 - Invalid Barfeeder system in MTConnect spec 1.4 

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#288]
Cannot detect BarFeeder in spec 1.4

Error:
File http://localhost:5000/probe is not valid.
	Element <BarFeeder id="MBarFeederSystem1"> is not allowed under element <Components>.
		Reason: The following elements are expected at this location (see below)
			'Component'
			'CommonComponent'
			'Device'
			'Controller'
			'Power'
			'Sensor'
			'Path'
			'Actuator'
			'Door'
			'Auxiliaries'
			'Loader'
			'WasteDisposal'
			'ToolingDelivery'
			'Axes'
			'Axis'
			'Linear'
			'Rotary'
			'Spindle'
			'Systems'
			'System'
			'Pneumatic'
			'Hydraulic'
			'Lubrication'
			'Coolant'
			'Electric'
			'Interfaces'
			'Interface'
			'BarFeederInterface'
			'MaterialHandlerInterface'
			'DoorInterface'
			'ChuckInterface'
		Annotations of element 'Components' (see below)
			The sub components
		Annotations of type 'ComponentsType' (see below)
			A list of generic components
		Error location: MTConnectDevices / Devices / Device / Components / Auxiliaries / Components / BarFeeder
		Details
			cvc-complex-type.1.4: Element <BarFeeder id="MBarFeederSystem1"> unexpected by type 'ComponentsType' of element <Components>.
			cvc-type.3.2: Element <Components> is not valid with respect to type definition 'ComponentsType'.
			cvc-elt.5.2.1: The element <Components> is not valid with respect to the actual type definition 'ComponentsType'.
	Element <Resources id="resources"> is not allowed under element <Components>.
		Reason: The following elements are expected at this location (see below)
			'Component'
			'CommonComponent'
			'Device'
			'Controller'
			'Power'
			'Sensor'
			'Path'
			'Actuator'
			'Door'
			'Auxiliaries'
			'Loader'
			'WasteDisposal'
			'ToolingDelivery'
			'Axes'
			'Axis'
			'Linear'
			'Rotary'
			'Spindle'
			'Systems'
			'System'
			'Pneumatic'
			'Hydraulic'
			'Lubrication'
			'Coolant'
			'Electric'
			'Interfaces'
			'Interface'
			'BarFeederInterface'
			'MaterialHandlerInterface'
			'DoorInterface'
			'ChuckInterface'
		Annotations of element 'Components' (see below)
			The sub components
		Annotations of type 'ComponentsType' (see below)
			A list of generic components
		Error location: MTConnectDevices / Devices / Device / Components / Resources
		Details
			cvc-complex-type.1.4: Element <Resources id="resources"> unexpected by type 'ComponentsType' of element <Components>.
			cvc-type.3.2: Element <Components> is not valid with respect to type definition 'ComponentsType'.
			cvc-elt.5.2.1: The element <Components> is not valid with respect to the actual type definition 'ComponentsType'.

[Devices.zip](https://github.com/mtconnect/cppagent/files/11424929/Devices.zip)

**Comment by wsobel** [comment]
This may be a schema version issue. Can you post on MTConnect projects site?
