### ISSUE TITLE
Error Handling HTTP POST Path

### ISSUE THREAD

**Issue by AndrewDugenske** [mtconnect/cppagent#29]
If data is posted to the agent using something like this:
http://agent1.example.com:5000/deviceName/path?tool=EN001

The agent will accept many strings for the path. Example:
http://agent1.example.com:5000/deviceName/foobar?tool=EN001

Recommend that the agent provide feedback about the path. Example:
<Error errorCode="BAD_STRUCTURE">Don't include a path with HTTP POST method.</Error>

**Comment by wsobel** [comment]
No longer relevant for the new agent
