### ISSUE TITLE
Agents alternating between value and unavailable

### ISSUE THREAD

**Issue by zm-wilcox** [mtconnect/cppagent#297]
I recently started collecting data from about twenty agents and noticed that four of them will just alternate between a value and unavailable.  Here's an example of a condition

![image](https://github.com/mtconnect/cppagent/assets/141073998/7ad21170-9e5f-43b3-b21f-1505b5aa334c)

and here's an event

![image](https://github.com/mtconnect/cppagent/assets/141073998/97e553aa-feab-4bd8-9764-643cf6977047)

My first assumption was that something was wrong with the adapters but I've watched the shdr streams all day and I'm not seeing any out of the ordinary. I've never worked with C++ before and I have no idea where or how to start troubleshooting this issue so any advice would be greatly appreciated.

**Comment by wsobel** [comment]
It looks like it may be connecting and disconnecting from the adapter. Check the agent log file and see if you have messages when the agent disconnected. That would be my guess. It may be a heartbeat issue or something else.

Can you attach the log file?

Thanks,
W

**Comment by zm-wilcox** [comment]
[VCN-6.log](https://github.com/mtconnect/cppagent/files/12222489/VCN-6.log)

Looks like it keeps disconnecting

**Comment by wsobel** [comment]
I’m in France right now. I’ll check it out tomorrow. Best - W(Sent from mobile)On Jul 31, 2023, at 23:46, zm-wilcox ***@***.***> wrote:﻿
VCN-6.log
Looks like it keeps disconnecting

**Comment by zm-wilcox** [comment]
I restarted the adapters on the machines that were giving me trouble and everything seems to be working correctly now. Thanks for the help!

**Comment by wsobel** [comment]
Sure. Glad to have given a hint. Best - W(Sent from mobile)On Aug 1, 2023, at 20:10, zm-wilcox ***@***.***> wrote:﻿
I restarted the adapters on the machines that were giving me trouble and everything seems to be working correctly now. Thanks for the help!
