### ISSUE TITLE
2.1.0.6 Docker MQTT Sink - Condition payload does not contain value/type of NORMAL, WARNING, or FAULT

### ISSUE THREAD

**Issue by MRIIOT** [mtconnect/cppagent#298]
I am not sending SHDR,  I am using HTTP POST dataitem_id=FAULT.  I'll have to check if  I'm doing something wrong.

![image](https://github.com/mtconnect/cppagent/assets/48079336/5d53126c-f806-4f41-a04b-97dcbb5c670e)

![image](https://github.com/mtconnect/cppagent/assets/48079336/f1ab59b2-2872-4c20-b8c9-e1a65429fb7d)

```
Conditions
--- Normal
     ---  array of conditions
```

**Comment by wsobel** [comment]
I’ll take a look. We will be migrating to another MQTT sink soon, so hopefully this will go away.

Best,
W

**Comment by wsobel** [comment]
The json will need to change in this case since it is usually embodied in the parent entity.
