### ISSUE TITLE
2.1.0.6 Docker MQTT Sink - Event and Sample TYPE missing from output.

### ISSUE THREAD

**Issue by MRIIOT** [mtconnect/cppagent#299]
The topic is built from `TYPE.SUBTYPE`.  `Subtype` appears in the payload, I would expect `type` to appear as well.
![image](https://github.com/mtconnect/cppagent/assets/48079336/661887ca-f40e-4d35-aea5-799b11d54cf5)

**Comment by wsobel** [comment]
The type is usually embodied in the name of the entity in JSON and  XML. it is only the fact that the topic is named with both that is different than usual. We chose that to make it distinct. The type is included in the topic and the subtype is superfluous. 

I think we may want to have a minimal observation payload in this case. Something to consider.

**Comment by wsobel** [comment]
Is there any follow-up on this topic? Otherwise I will close it. The Mqtt2Service adheres to the common JSON with a combined payload.
