### ISSUE TITLE
mRealTime does not work on adapter.

### ISSUE THREAD

**Issue by sydongda** [mtconnect/cppagent#30]
I find that, mRealTime always is false when call function connect(connector.cpp file). And after receive protocol command (realtime = true), the value only works when next connect to adapter again, right?

**Comment by wsobel** [comment]
If you set RealTime in the configuration for the adapter in the cfg file it will occur on the first connection. Sending it as a command was not really the intention. It was supposed to be a configuration option.

**Comment by sydongda** [comment]
get it, thanks.
