### ISSUE TITLE
Using MTConnect with LinuxCNC/MachineKit

### ISSUE THREAD

**Issue by AtinAngrish** [mtconnect/cppagent#31]
Hi all!

I am working on a project where I need to connect LinuxCNC with MTConnect. I was able to build the agent with the help of the documentation on mtcup.org on my BeagleBone running linux. The beaglebone is running machinekit, which as far as I know is a fork of linuxCNC. 

I found an adapter for EMC2 online here: https://github.com/athulan/adapter 

However, I have the following 3 questions/problems/issues: 

1. I don't know how to connect an adapter with an agent? I see a lot of adapters with .cpp and .hpp files but I have no idea on how to use them. This is more of a generic problem. I have a computer with the build agent on it. Where should the adapter reside? Should it be in the computer running the CNC machine? Or should it be on my computer which has the agent? And how do I connect both of them? I am unable to find any detailed instructions on doing so. 

2. I tried the "make" command after navigating to the folder containing the adapter for EMC in my Beaglebone and it threw a "fatal error" saying a file called rcs.hh was missing. Can anyone help out with this?

3. Is it even possible to run MTConnect on machinekit? 

I am not a programmer ,unfortunately. Any help would be appreciated. 

Thanks a lot for your time.

**Comment by russwaddell** [comment]
The Linux build on MTCUP doesn't actually include an adapter. It uses a text file of stored data and a script to loop through it. The agent sees that that as an "adapter".

I can't write a BeagleBone adapter for you, but there are others who have expressed an interest in doing so.

**Comment by AtinAngrish** [comment]
Thanks for your reply. 

Is MTCUP not the correct way to install the agent? If not, how do I put another adapter into place? Is there a link I could refer to ? I have looked around online but couldn't find anything.

I will eventually be using a linux system running LinuxCNC to control a CNC machine where I want to use MTConnect. My problem is essentially to get MTConnect running on LinuxCNC. Does the beaglebone play a role in the running of the MTConnect?

Thanks a lot for your time and replies. 

Atin.

**Comment by russwaddell** [comment]
The agent and adapter are usually separate pieces. For a late-model,
MTConnect-enabled machine tool, you'd have a manufacturer-supplied adapter
that's built in or optional running on the CNC control. This MTConnect
adapter is software, not hardware, and is similar to a printer or camera
driver you'd get with any kind of computer peripheral or accessory. For
more on adapters you can read this old but still accurate article:
http://www.mmsonline.com/articles/understanding-mtconnect-agents-and-adapters


I don't totally understand how LinuxCNC and BeagleBone relate to each other
in this case. Is LinuxCNC running on the BeagleBone? What does the
BeagleBone do, or what do you want it to do? There's not really a right or
wrong answer here; you just have to pick based on available software
support and the specifics of your implementation.

An adapter for LinuxCNC or for BeagleBone could work, but as far as I know
neither of these adapters exist. You'd be looking for something comparable
to the Fanuc adapter (https://github.com/mtconnect/adapter/tree/master/fanuc)
or the MakerBot adapter/agent (https://github.com/mtconnect/makerbot_agent).

**Comment by AtinAngrish** [comment]
Thank you so much for your patience. 

The LinuxCNC is running on a BeagleBone. The BeagleBone is being used to drive a small 3D printer. 

I think I might not have worded my issue clearly: There are primarily a couple of problems I am facing right now, and I think you have answered at least one of them for me. 

Issue #1: I have the agent running on a computer. I also have the adapter files. Say I use the "make" command for building my adapter. Now how am I supposed to connect the adapter and the agent? I mean how does the agent know if there is an adapter for a particular machine/system? Don't I have to specify it somewhere? Or do I simply run the adapter in one terminal window and have the agent running in the other window? For example, I was able to build the Makerbot adaptor-agent, but I don't know what to do after that? Do I simply connect my laptop to the makerbot via a USB and run the machine,the agent and the adapter?

In your previous reply, you said that the MTCUP sees a text file with stored data as an adapter. How do I get it to work with, say an adapter for a specific machine. 

Issue #2: You said that an adapter for LinuxCNC doesn't exist. Can't I use this adapter ( https://github.com/athulan/adapter ) for LinuxCNC since LinuxCNC is simply renamed version of EMC2? Even when I try using it, it gives me errors. So maybe I am missing something there. 

Also, in case I want to build an adapter for LinuxCNC, what do  I need to know? I saw a couple of video tutorials on Youtube by Mr. Sobel. Would they be helpful?

I know there are a lot of questions here and I am so very thankful for you to answer my queries. I have looked a lot online and there is little to no documentation on connecting LinuxCNC with MTConnect except for the link I shared with you in Issue #2 above. 

Thanks a lot, Russ!

**Comment by wsobel** [comment]
When i have a minute. I'll point you at an adapter written in python that may work well with LinuxCNC. I can also help with some of your questions. I'll get to it later today...

Best
Will 

(Sent from mobile)

**Comment by AtinAngrish** [comment]
Thanks Mr. Sobel. Looking forward to your reply!

**Comment by wsobel** [comment]
The Python adapter work was done as part of the ROS/MTConnect interface project a few years ago. The code can be found here: [Python MTConnect Adapter Source](https://github.com/mtconnect/ros_bridge/tree/master/mtconnect/mtconnect_ros_bridge/scripts/src). 

It should be pretty straight forward to create a python adapter for LinuxCNC – so if you need some help, I can advise. The agent should be pretty much a drop in, so all you need to do is build it on Linux. See [Building MTConnect Agent](http://mtcup.org/wiki/C%2B%2B_Agent#Installing_C.2B.2B_Agent_on_Raspberry_Pi) Instructions for more details.

This should hopefully get you started. Tell me if you get stuck with the adapter – I've done dozens of these and can point you in the right direction. 

Hopefully this helps!
- W

**Comment by AtinAngrish** [comment]
Thanks Mr. Sobel. I shall try it out and get back with more questions. Really appreciate your help.

**Comment by egroegkm** [comment]
AtinAngrish, curious if you were able to get the adapter for LinuxCNC working. Thinking of installing it on a router I have. Please let me know if you got yours working.
