### ISSUE TITLE
Agent MQTT SINK missing tags

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#317]
Adapter 'Observation rate' and 'connection status' tags are not being output to MQTT topic

![image](https://github.com/mtconnect/cppagent/assets/113067605/e9332e91-2080-4d7f-afdd-07cb2b4ad748)

**Comment by neildes2** [comment]
Is this by design?  Or typo?

**Comment by wsobel** [comment]
Been at meetings. Will need to evaluate. BestW(Sent from mobile)On Aug 31, 2023, at 10:57, neildes2 ***@***.***> wrote:﻿
Is this by design?  Or typo?

**Comment by wsobel** [comment]
We have a new version of the mqtt service that should solve many issues. It will be released in 2.2.0.7

**Comment by wsobel** [comment]
@neildes2 , is this still an issue? Have you tried the other service?

**Comment by neildes2** [comment]
I will be testing the agent again this coming week.

**Comment by neildes2** [comment]
I have not tried 'the other service'  How to set its use?  Currently I use in cfg....

Sinks {

	MqttService {

**Comment by neildes2** [comment]
resolved
