### ISSUE TITLE
Agent MQTT output changes Agent Device UUID

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#318]
Why does it change when agent restarts (seems to be like InstanceID)  
Whan mapping tags in broker, this seems to pose a problem.

![image](https://github.com/mtconnect/cppagent/assets/113067605/e807cbd4-4192-4bf1-b5b4-9015bf077fae)

**Comment by wsobel** [comment]
The agent uuid is derived from the ip address of the primary NIC. What is most likely happening is the IP address is changing each time the container is started. 

The solution is to use the new `AgentDeviceUUID` configuration in the docker branch. I'll be pushing this soon. The config setting overrides the generated value. 

For docker you can also pass it in as an environment variable using the new environment variable expansion in config files.
