### ISSUE TITLE
Can't build my MTConnect agent

### ISSUE THREAD

**Issue by SergeStMartin** [mtconnect/cppagent#32]
Hi,

I'm not a regular programmer. I tried to set up the MTConnect agent on my PC (Win7 SP1) but it bugged at the building process (Visual Studio 2010). Below is an excerpt of the output (in french).

Am I missing something ?

Serge

1>------ Début de la génération : Projet : ZERO_CHECK, Configuration : Release Win32 ------
1>La génération a démarré 2016-02-23 09:46:10.
1>PrepareForBuild:
1>  Création du répertoire "C:\cppagent\build\Release\".
1>InitializeBuildStatus:
1>  Création de "Win32\Release\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
1>CustomBuild:
1>  Checking Build System
1>  CMake does not need to re-run because C:/cppagent/build/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/cppagent/build/agent/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/cppagent/build/test/CMakeFiles/generate.stamp is up-to-date.
1>FinalizeBuildStatus:
1>  Suppression du fichier "Win32\Release\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild".
1>  Mise à jour de l'horodatage "Win32\Release\ZERO_CHECK\ZERO_CHECK.lastbuildstate".
1>
1>La génération a réussi.
1>
1>Temps écoulé 00:00:00.06
2>------ Début de la génération : Projet : UPDATE_VERSION, Configuration : Release Win32 ------
3>------ Génération ignorée : Projet : agent_test, Configuration : Release Win32 ------
3>Projet non sélectionné dans le cadre d'une génération pour cette configuration de solution 
4>------ Génération ignorée : Projet : cov, Configuration : Release Win32 ------
4>Projet non sélectionné dans le cadre d'une génération pour cette configuration de solution 
2>La génération a démarré 2016-02-23 09:46:11.
2>InitializeBuildStatus:
2>  Création de "Win32\Release\UPDATE_VERSION\UPDATE_VERSION.unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
2>CustomBuild:
2>  Building Custom Rule C:/cppagent/agent/CMakeLists.txt
2>  CMake does not need to re-run because C:\cppagent\build\agent\CMakeFiles\generate.stamp is up-to-date.
2>FinalizeBuildStatus:
2>  Suppression du fichier "Win32\Release\UPDATE_VERSION\UPDATE_VERSION.unsuccessfulbuild".
2>  Mise à jour de l'horodatage "Win32\Release\UPDATE_VERSION\UPDATE_VERSION.lastbuildstate".
2>
2>La génération a réussi.
2>
2>Temps écoulé 00:00:00.06
5>------ Début de la génération : Projet : agent, Configuration : Release Win32 ------
5>La génération a démarré 2016-02-23 09:46:11.
5>PrepareForBuild:
5>  Création du répertoire "C:\cppagent\build\agent\Release\".
5>InitializeBuildStatus:
5>  Création de "agent.dir\Release\agent.unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
5>CustomBuild:
5>  Building Custom Rule C:/cppagent/agent/CMakeLists.txt
5>  CMake does not need to re-run because C:\cppagent\build\agent\CMakeFiles\generate.stamp is up-to-date.
5>ClCompile:
5>  cppagent.cpp
5>  adapter.cpp
5>  asset.cpp
5>  agent.cpp
5>  checkpoint.cpp
5>  component.cpp
5>  component_event.cpp
5>  change_observer.cpp
5>  connector.cpp
5>  cutting_tool.cpp
5>  data_item.cpp
5>  device.cpp
5>  globals.cpp
5>  options.cpp
5>  service.cpp
5>..\..\agent\service.cpp(83): warning C4995: 'gets' : le nom a été marqué comme #pragma deprecated
5>..\..\agent\service.cpp(437): warning C4995: '_snprintf' : le nom a été marqué comme #pragma deprecated
5>  config.cpp
5>  ref_counted.cpp
5>  version.cpp
5>  xml_parser.cpp
5>  xml_printer.cpp
5>  Génération de code en cours...
5>  Compilation en cours...
5>  rolling_file_logger.cpp
5>  Génération de code en cours...
5>xml_parser.obj : warning LNK4217: symbole défini localement _xmlFree importé dans la fonction "public: void __thiscall XmlParser::getDataItems(class std::set<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct _xmlNode *)" (?getDataItems@XmlParser@@QAEXAAV?$set@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@PAU_xmlNode@@@Z)
5>xml_printer.obj : warning LNK4049: symbole défini localement _xmlFree importé
5>libxml2_a_v120_32.lib(nanoftp.obj) : error LNK2001: symbole externe non résolu ___report_rangecheckfailure
5>libxml2_a_v120_32.lib(xmlschemas.obj) : error LNK2001: symbole externe non résolu ___report_rangecheckfailure
5>libxml2_a_v120_32.lib(HTMLparser.obj) : error LNK2001: symbole externe non résolu ___report_rangecheckfailure
5>libxml2_a_v120_32.lib(encoding.obj) : error LNK2001: symbole externe non résolu ___report_rangecheckfailure
5>libxml2_a_v120_32.lib(catalog.obj) : error LNK2001: symbole externe non résolu ___report_rangecheckfailure
5>libxml2_a_v120_32.lib(debugXML.obj) : error LNK2019: symbole externe non résolu ___report_rangecheckfailure référencé dans la fonction _xmlCtxtDumpAttrDecl
5>libxml2_a_v120_32.lib(tree.obj) : error LNK2001: symbole externe non résolu ___report_rangecheckfailure
5>libxml2_a_v120_32.lib(parser.obj) : error LNK2001: symbole externe non résolu ___report_rangecheckfailure
5>libxml2_a_v120_32.lib(error.obj) : error LNK2001: symbole externe non résolu ___report_rangecheckfailure
5>libxml2_a_v120_32.lib(xpath.obj) : error LNK2001: symbole externe non résolu ___report_rangecheckfailure
5>libxml2_a_v120_32.lib(xpath.obj) : error LNK2019: symbole externe non résolu __dclass référencé dans la fonction _trio_fpclassify_and_signbit
5>libxml2_a_v120_32.lib(xpath.obj) : error LNK2019: symbole externe non résolu __dsign référencé dans la fonction _trio_fpclassify_and_signbit
5>libxml2_a_v120_32.lib(xpath.obj) : error LNK2019: symbole externe non résolu __libm_sse2_log10_precise référencé dans la fonction _xmlXPathFormatNumber
5>libxml2_a_v120_32.lib(xpath.obj) : error LNK2019: symbole externe non résolu __libm_sse2_pow_precise référencé dans la fonction _xmlXPathCompNumber
5>libxml2_a_v120_32.lib(xmlschemastypes.obj) : error LNK2019: symbole externe non résolu __dtoui3 référencé dans la fonction __xmlSchemaDateAdd
5>C:\cppagent\build\agent\Release\agent.exe : fatal error LNK1120: 6 externes non résolus
5>
5>ÉCHEC de la build.
5>
5>Temps écoulé 00:00:32.61
6>------ Début de la génération : Projet : ALL_BUILD, Configuration : Release Win32 ------
6>La génération a démarré 2016-02-23 09:46:43.
6>InitializeBuildStatus:
6>  Création de "Win32\Release\ALL_BUILD\ALL_BUILD.unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
6>CustomBuild:
6>  Building Custom Rule C:/cppagent/CMakeLists.txt
6>  CMake does not need to re-run because C:\cppagent\build\CMakeFiles\generate.stamp is up-to-date.
6>FinalizeBuildStatus:
6>  Suppression du fichier "Win32\Release\ALL_BUILD\ALL_BUILD.unsuccessfulbuild".
6>  Mise à jour de l'horodatage "Win32\Release\ALL_BUILD\ALL_BUILD.lastbuildstate".
6>
6>La génération a réussi.
6>
6>Temps écoulé 00:00:00.07
7>------ Génération ignorée : Projet : INSTALL, Configuration : Release Win32 ------
7>Projet non sélectionné dans le cadre d'une génération pour cette configuration de solution 
========== Génération : 3 a réussi, 1 a échoué, 0 mis à jour, 3 a été ignoré ==========

**Comment by johnmichaloski** [comment]
My French is bad, but I had a similar problem (I’m assuming), the windows MTConnect agent compilation code depends on libraries from Visual Studio 2013. You would have to port these libraries back to 2010. (I did this, but it was a while back, and not a trivial exercise.) Visual C++ is fussy on syncing up the dependent libraries.

I too use Visual Studio 2010, since it still has installation integrated into the IDE. I suggest upgrading to 2013 (not sure what visual studio version the current MTConnect agent code is compiled against.) I can hunt around for my port of backport of libxml(?) library to 2010 (as I recall needed to backport a bunch of other libraries too.)

**Comment by wsobel** [comment]
The French is fine. Did you use your own build of libxml2? There is a lib that comes with the project that should work. If you did build your own libxml2 library, check if the function call is using the correct calling convention. cdecl vs stdcall. I'm traveling at this moment, but will check a little later when I get in.

Best,
W

**Comment by SergeStMartin** [comment]
Hi W,

I use the lib included in the cppagent-master zipped file.

Before trying to set up the agent, I did install an adapter from the adapter-master zipped file.
The adapter runs properly.

Serge

**Comment by wsobel** [comment]
I'll take a look. I'm using vs 2015 now, but it shouldn't make a
difference.

On Tuesday, February 23, 2016, SergeStMartin <notifications@github.com>
wrote:

> Hi W,
>
> I use the lib included in the cppagent-master zipped file.
>
> Before trying to set up the agent, I did install an adapter from the
> adapter-master zipped file.
> The adapter runs properly.
>
> Serge
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtconnect/cppagent/issues/32#issuecomment-187829731>.
>


-- 
- Will

Sent from mobile

**Comment by johnmichaloski** [comment]
I tried vs 2010 for the 1.3  mtconnect C++ agent (at the time it was compiled against vs 2013) - You will need to recompile libxml2 and recompile a dependent lib (libiconv) – something changed. I forget what, but it isn’t trivial. (The headers might have changed too). Thus, I stick with 1.2 agent.

I don’t know what version the C++ agent is now.

I could upload the code to my github site, but not sure this is the best way to proceed.

**Comment by wsobel** [comment]
Didn’t know it. I’ll set up a clean machine build using VS 2010 (is that the version of choice? VS is already at 2015…)

Best Regards,
Will Sobel

**Comment by johnmichaloski** [comment]
VS 2010 can produce simple msi installers – which works for mtconnect.

After VS 2010 you need to use installshield light (which is provided and wasn’t too hot in vs 2010)  or buy install shield  or learn wix,  or nsis, etc.  Not motivated enough. (VS 2010 msi  is especially good at handling the C++ and other runtime library installations.)

Hence,  I use 1.2 and vs 2010. But if/when you go to c++11, that will blow things up, since vs 2010 does not support It. Guess I’ll be forced to use NSIS installations, although the uninstalls are perfect.

I would suggest users download and install the 2013/2015 studio express version (unless they absolutely require MFC/ATL).  Not worth time to insure the backwards compatibility.

**Comment by wsobel** [comment]
I’ve been playing with NSIS for other projects and so far it’s the best I’ve found. I can create a little installer with NSIS fairly easily (CMake supports it as one of the INSTALL targets.)

I don’t want to be bound to 2010 forever – 2015 is much more capable and implements all the new C++ semantics. 

Best Regards,
Will Sobel

**Comment by johnmichaloski** [comment]
Sound good. People love a good installation script.

I would suggest users download and install the 2013/2015 studio express version.

Although now the call it visual studio  express 2015 “community”.

https://www.visualstudio.com/en-us/products/visual-studio-express-vs.aspx

Express did not support MFC or ATL, but MTConnect does not use either. Have not tried it recently.

**Comment by SergeStMartin** [comment]
Thank you guys !

I used the 1.2 agent. Works great !

Serge

**Comment by johnmichaloski** [comment]
Serge,

Just in case, you need to compile the agent for a 64-bit machine if you are running on one.

I spent some time figuring out what was wrong when I ran a 32-bit agent on a 64 bit PC.

John

**Comment by wsobel** [comment]
Good to hear. I'm still trying to reproduce the issues. Will get back once i have had a chance to test. Thanks John!

(Sent from mobile)

**Comment by wsobel** [comment]
I have changed the latest build to no longer have dependencies on the libraries. I have added submodules from the repos for libxml2 and cppunit to get around the VS versioning hell. Please get back if this works.

**Comment by SergeStMartin** [comment]
Hi W. Something seems wrong. I get the following message in the CMake comment window : "You have called ADD_LIBRARY for library cppunit without any source files. This typically indicates a problem with your CMakeLists.txt file"
