### ISSUE TITLE
Public Release MTConnect Agent 2.2.0.6 - Invalid CutterStatus in MTConnect spec 1.2 and 1.3

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#323]
I am using the latest schema 

Element <CutterStatus> is not allowed under element <CuttingItem>.
	Reason: The following elements are expected at this location (see below)
		'Description'
		'Locus'
		'ItemLife'
		'Measurements'
		'{##any except urn:mtconnect.org:MTConnectAssets:1.3}'
	Annotations of element 'CuttingItem' (see below)
		An edge
	Annotations of type 'CuttingItemType' (see below)
		An edge into a tool assembly
	Error location: MTConnectAssets / Assets / CuttingTool / CuttingToolLifeCycle / CuttingItems / CuttingItem / CutterStatus
	Details
		cvc-complex-type.1.4: Element <CutterStatus> unexpected by type 'CuttingItemType' of element <CuttingItem>.
		cvc-type.3.2: Element <CuttingItem> is not valid with respect to type definition 'CuttingItemType'.
		cvc-elt.5.2.1: The element <CuttingItem> is not valid with respect to the actual type definition 'CuttingItemType'.

[Devices.zip](https://github.com/mtconnect/cppagent/files/12586823/Devices.zip)

**Comment by scottmwyant** [comment]
Thanks for getting this in @hulinning2. Looking forward to seeing v2 agents come in.  Let me know if there's anything I can do to support.

**Comment by wsobel** [comment]
Assigning to Shaurabh to check the schema.

**Comment by shaurabhsingh** [comment]
@hulinning2 Hi Lynh. Could you also share the "/assets" XML response document? I want to check the error on my end against the MTConnectAssets schema. 

>  On the other hand, more of an "FYI", the device file that has been shared validates just fine against the MTConnectDevices schema. << which I don't think the issue at hand is.

**Comment by hulinning2** [comment]
Hi Shaurabhsingh, 
Here is the assets output for spec 1.3
Thanks

[assets.zip](https://github.com/mtconnect/cppagent/files/12700867/assets.zip)

**Comment by shaurabhsingh** [comment]
This one refers to an Okuma schema. Could you share that as well?

**Comment by hulinning2** [comment]
Here is the Okuma schema for Tool Assets
[OkumaToolAssets_1.3.xsd.zip](https://github.com/mtconnect/cppagent/files/12701411/OkumaToolAssets_1.3.xsd.zip)
Thanks

**Comment by shaurabhsingh** [comment]
I am not able to replicate the error. See the image attached.

Could you confirm if the path on your end is correct and you have the latest 1.2/1.3 schemas?

![image](https://github.com/mtconnect/cppagent/assets/33585615/60882faf-f23b-4822-bc5d-c39ef8ccd7a8)

**Comment by hulinning2** [comment]
Please use this output since this one has CutterStatus in CuttingItem

![image](https://github.com/mtconnect/cppagent/assets/4930742/7b95c7be-a75f-4ca0-ba49-796f0aa6683e)


[assets.zip](https://github.com/mtconnect/cppagent/files/12707503/assets.zip)

**Comment by shaurabhsingh** [comment]
Added missing CutterStatus element in 1.2 and 1.3 schemas. Find the latest here: https://github.com/mtconnect/schema

**Comment by hulinning2** [comment]
Fixed after updating latest schema files
