### ISSUE TITLE
PERIOD filter not working as expected

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#324]
I have an issue where FILTERS doesn’t seem to work as I expected.   I’m using   <Filter type="PERIOD">2</Filter>    to get an observation every two seconds, but I’m getting duplicates / multiple OBS with the same timestamp.  I thought that PERIOD would get ONE OBS every interval of the time period.

The timestamp issue seems to be from the network latency and the agent assigning multiple obs with the same timestamp.  But I assumed that PERIOD would fix this.  Especially at a value of 2 seconds.  This is causing an issue at the historian with dup alarms.

![image](https://github.com/mtconnect/cppagent/assets/113067605/025bda96-54fa-4b69-9397-7e010d11cd6e)

![image](https://github.com/mtconnect/cppagent/assets/113067605/85cabd92-f4d4-4ebb-99b8-13f057b5789d)

![image](https://github.com/mtconnect/cppagent/assets/113067605/ca78a2f7-cfb5-4c7a-9ae2-3219befd1be0)

**Comment by neildes2** [comment]
Cannot provide due to ITAR

**Comment by wsobel** [comment]
How about if you provided just the load data stripped out of the stream? Would that be possible?

**Comment by neildes2** [comment]
Not able.  so I created a test shdr (attached).  i was able to duplicate the issue once on my desktop.  I know its not apples to apples, but the PERIOD filter added 3 observations in the same PERIOD.

![image](https://github.com/mtconnect/cppagent/assets/113067605/8a9185d1-306a-458e-90b7-a72533d0cd57)

![image](https://github.com/mtconnect/cppagent/assets/113067605/6dcdd720-3da1-4e1d-afff-37bb1f2a63fc)


[shdr.txt](https://github.com/mtconnect/cppagent/files/12649986/shdr.txt)

Agent ver 2.2.0.6

**Comment by wsobel** [comment]
Thanks a lot. I’m @ EMO and will get to it asap.(Sent from mobile)On Sep 18, 2023, at 17:33, neildes2 ***@***.***> wrote:﻿
Not able.  so I created a test shdr (attached).  i was able to duplicate the issue once on my desktop.  I know its not apples to apples, but the PERIOD filter added 3 observations in the same PERIOD.


shdr.txt
Agent ver 2.2.0.6

**Comment by wsobel** [comment]
Found an issue, need to work out the solution. There is an edge condition where the arrivals fall on a boundary point and it sends the last from the previous period and the next observation immediately. 

Will have a fix in version 2.2.0.7

**Comment by wsobel** [comment]
Found an issue, need to work out the solution. There is an edge condition where the arrivals fall on a boundary point and it sends the last from the previous period and the next observation immediately. 

Will have a fix in version 2.2.0.7

**Comment by neildes2** [comment]
This issue is not fixed.  same test with same files returns TWO observations.   v2.2.0.7

**Comment by wsobel** [comment]
I’ll take a look again. It’s pretty complex. (Sent from mobile)On Oct 5, 2023, at 18:42, neildes2 ***@***.***> wrote:﻿
This issue is not fixed.  same test with same files returns TWO observations.   v2.2.0.7

**Comment by wsobel** [comment]
Do you have any more info? What is the update rate? Fast or slow? I have tried to reproduce and cannot.

Any additional info would be helpful to try to reproduce.

**Comment by wsobel** [comment]
Also, please upload the sample of the data. There can be two observations that can occur within a second if the following observation exceeds the period. It's filling each n second slot with at most one observation. 

Please upload sample

**Comment by wsobel** [comment]
For example, this sequence:

```
          <Angle dataItemId="NL257200426_20" name="Cact" sequence="453" subType="ACTUAL" timestamp="2023-10-05T20:39:06.998112Z">999.999</Angle>
          <Angle dataItemId="NL257200426_20" name="Cact" sequence="454" subType="ACTUAL" timestamp="2023-10-05T20:39:10.638141Z">111.111</Angle>
          <Angle dataItemId="NL257200426_20" name="Cact" sequence="455" subType="ACTUAL" timestamp="2023-10-05T20:39:10.662854Z">333.333</Angle>
          <Angle dataItemId="NL257200426_20" name="Cact" sequence="456" subType="ACTUAL" timestamp="2023-10-05T20:39:14.014906Z">444.444</Angle>
```

`20:39:10.638141Z` and `20:39:06.998112Z` are less than 2 seconds apart because the second one fills the slot before `20:39:14.014906Z`. So we flush the previous value after two seconds at `~20:39:12.00`

Just want to make sure what's happening.

**Comment by neildes2** [comment]
If you push the obs at 10msec,  the agent gives the same timestamp to TWO obs.  The issue I think is that the filter is not taking ONE obs at the interval
[shdr.txt](https://github.com/mtconnect/cppagent/files/12823254/shdr.txt)

**Comment by wsobel** [comment]
Ok. I’ll try that tomorrow. I tried with different intervals and did not see it. I’ll try with a 10 ms interval. (Sent from mobile)On Oct 5, 2023, at 23:02, neildes2 ***@***.***> wrote:﻿
If you push the obs at 10msec,  the agent gives the same timestamp to TWO obs.  The issue I think is that the filter is not taking ONE obs at the interval
shdr.txt

**Comment by wsobel** [comment]
Been trying to reproduce with no luck. Found one issue when the initial data is streamed out where the first buffer repeats some overlapping observations.

**Comment by NeilDes** [comment]
I think that might be it because I only see the duplicates at initial start
up. I haven't seen any later in the stream. So far.

**Comment by wsobel** [comment]
Ok. Let me push the current changes that fix that one scenario. - W
