### ISSUE TITLE
Mtconnect Agent Build Errors

### ISSUE THREAD

**Issue by TCSmaint** [mtconnect/cppagent#33]
I am trying to Build an agent on a windows 7 sp1 pc with Visual Studio 2015 community, and I can not get past a few error problems.  I can configure and generate in cmake program but when to building the solution in visual studio 2015 and it generates errors.  I have tried this with version 1.3.0.16 and 1.2.0.23 and have the same result.  Is my computer being the hold up?  Here are the error I am Getting. 

Thank you for your time,
Jason Van Den Top

Severity    Code    Description Project File    Line    Suppression State

Error   C3861   'gets': identifier not found    agent_test  C:\MTConnect\cppagent-1.3.0.16\agent\service.cpp    83  
Error   C2065   'timezone': undeclared identifier   agent   C:\MTConnect\cppagent-1.3.0.16\agent\globals.cpp    241 
Error   C3861   'gets': identifier not found    agent   C:\MTConnect\cppagent-1.3.0.16\agent\service.cpp    83  
Error   C2065   'timezone': undeclared identifier   agent_test  C:\MTConnect\cppagent-1.3.0.16\agent\globals.cpp    241

**Comment by wsobel** [comment]
Did you make sure you installed the C Runtime? They separated it out in the latest version of VS and it is an option when you install Visual Studio.

Best Regards,
Will Sobel

**Comment by wsobel** [comment]
Just tested as well and reproduced the problem,. I’ll check into this.

Best Regards,
Will Sobel

**Comment by wsobel** [comment]
I have added source libxml2 and cppunit source builds so we can avoid the library mismatch we were getting with the libraries and the VS versioning issues. I have tested this build on 2015. This is not a final release, so I would like some feedback on whether it works for you.

**Comment by TCSmaint** [comment]
Thank you for the fast response.  I do not have the libxml2 source build.  My apologizes for the delay, I have tried getting the source code built and not having much success. I will let you know when I am able to accomplish that and try the build again.

Thanks again,
Jason Van Den Top

**Comment by wsobel** [comment]
You need to clone the git repo and the do a git submodule init and update. I'll provide some instructions when I get back. The source for libxml2 is a submodule meaning it references another git repo. 

(Sent from mobile)

**Comment by wsobel** [comment]
pushed a some dependent files into the libxml2 make. I rebuilt in clean 2013 environment. Hopefully this fixes the issues.

**Comment by TCSmaint** [comment]
I have build working! Thank you for the help!

Thanks,
Jason Van Den Top

**Comment by soronsoft** [comment]
TC  Smaint:

I just study the cppagent and build in VS2015. I got same build errors as you. Would mind telling me how I can solve the errors?

Thanks,
Dave Lisc
