### ISSUE TITLE
Deviceuuid param not working

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#340]
Added Device uuiid parameter in agent cfg file.  But agent uuid keeps getting auto calculated.  

AgentDeviceUUID - Set the UUID of the agent device
Default: UUID derived from the IP address and port of the agent

agent.cfg below...

Devices = Devices.xml
AgentDeviceUUID = 3519a48b-814b-3425-a12d-ef250947ab3d
DisableAgentDevice = false
PreserveUUID = true
AllowPut = true
AllowPutFrom = localhost
Port = 5000
ReconnectInterval = 1000
BufferSize = 17
MaxAssets = 1024
SchemaVersion = 2.0
ShdrVersion = 1
SuppressIPAddress = false
MonitorConfigFiles = false
WorkerThreads = 2

**Comment by neildes2** [comment]
additional note....Im using mqtt sinks settings as well

**Comment by wsobel** [comment]
I’ll check this out. Is this the latest build?

**Comment by neildes2** [comment]
Yes v2.2.0.8
