### ISSUE TITLE
Agent failing to sync the topics

### ISSUE THREAD

**Issue by skibum1869** [mtconnect/cppagent#345]
When using the following cfg file the agent will not push out the MQTT data to the broker. 

```
Devices = ./devices/MazakSample.xml
ServerIP = 0.0.0.0
Port = 5000
AllowPut = false
AllowPutFrom = localhost

ReconnectInterval = 1000
WorkerThreads = 2
# MinimumConfigReloadAge = 30
BufferSize = 17
MaxAssets = 8096
IgnoreTimestamps = true

SchemaVersion = 2.0
ShdrVersion = 2.0 # Set Default on all Adapters
JsonVerson = 2.0
SuppressIPAddress = true

MonitorConfigFiles = true
ConversionRequired = false
UpcaseDataItemValue = true
Pretty = true

## Security
TlsOnly = false

Adapters {
    Saw {
      Host = 10.0.0.4
      Port = 9800
    }
}

Sinks {
#     Push data from agent to a broker
    Mqtt2Service{
        MqttHost = 127.0.0.1
        MqttPort = 1883
#        MqttUserName = mtconnect
#        MqttPassword = mtconnect
        MqttClientId = mtc_agent

        ProbeTopic = mtconnect/probe/#
        CurrentTopic = mtconnect/current/#
        SampleTopic = mtconnect/sample/#
        AssetTopic = mtconnect/asset/#
        MqttCurrentInterval = 10000ms
        MqttSampleInterval = 500ms
        MqttSampleCount = 1000
    }
}


Files {
    schemas {
        Path = ../schema
        Location = /schemas/
    }
    styles {
        Path = ../styles
        Location = /styles/
    }
    Favicon {
        Path = ../styles
        Location = /styles/
    }
}

Ruby {
#   module =  ../ruby/module.rb
}

DevicesStyle { Location = /styles/styles.xsl }
StreamsStyle { Location = /styles/styles.xsl }

logger_config {
    logging_level = warn #trace, debug, info, warn, error, or fatal
    output = file /etc/mtconnect/log/agent.log
}
```

``` bash
Attaching to mosquitto, mtc_agent
mosquitto     | 1697491746: mosquitto version 2.0.18 starting
mosquitto     | 1697491746: Config loaded from /mosquitto/config/mosquitto.conf.
mosquitto     | 1697491746: Opening ipv4 listen socket on port 1883.
mosquitto     | 1697491746: Opening ipv6 listen socket on port 1883.
mosquitto     | 1697491746: mosquitto version 2.0.18 running
mosquitto     | 1697491751: New connection from 192.168.80.4:50758 on port 1883.
mosquitto     | 1697491751: New client connected from 192.168.80.4:50758 as mtc_agent (p2, c1, k10).
mtc_agent     | [2023-10-16 21:29:06.559535] [0x00007f19d3c87780] [debug]   Cannot file path: "/usr/local/etc/mtconnect", No such file or directory
mtc_agent     | [2023-10-16 21:29:06.559654] [0x00007f19d3c87780] [debug]   Cannot file path: "/usr/local/share/mtconnect", No such file or directory
mtc_agent     | MTConnect Agent Version 2.2.0.8 - built on Tue Oct 10 21:15:56 2023
mtc_agent     | [2023-10-16 21:29:06.559848] [0x00007f19d3c87780] [trace]   Found file '/etc/mtconnect/data/dockerAgent.cfg'  in path "/etc/mtconnect"
mtc_agent     | [2023-10-16 21:29:06.559893] [0x00007f19d3c87780] [info]    Loading configuration from: "/etc/mtconnect/data/dockerAgent.cfg"
mtc_agent     | Loading configuration from:"/etc/mtconnect/data/dockerAgent.cfg"
mtc_agent     | 2023-10-16T21:29:06.570578Z (0x00007f19d3c87780) [warning] MAIN->AgentConfiguration::initialize->AgentConfiguration::loadConfig->AgentConfiguration::loadSinks: The following path "/etc/mtconnect/data/styles/old" is not a regular file: "/etc/mtconnect/data/styles/old"
mtc_agent     | 2023-10-16T21:29:06.571182Z (0x00007f19d3c87780) [warning] MAIN->AgentConfiguration::initialize->AgentConfiguration::loadConfig->AgentConfiguration::loadSinks: The following path "/etc/mtconnect/data/styles/old" is not a regular file: "/etc/mtconnect/data/styles/old"
mtc_agent     | 2023-10-16T21:29:06.597991Z (0x00007f19d3284640) [warning] : MqttClientImpl::connect: cannot connect: Connection refused, will retry
```

**Comment by wsobel** [comment]
Looks like it’s not connecting to the broker. Does it require TLS or a password?(Sent from mobile)On Oct 16, 2023, at 14:50, Max Harris ***@***.***> wrote:﻿
When using the following cfg file the agent will not push out the MQTT data to the broker.
Devices = ./devices/MazakSample.xml
ServerIP = 0.0.0.0
Port = 5000
AllowPut = false
AllowPutFrom = localhost

ReconnectInterval = 1000
WorkerThreads = 2
# MinimumConfigReloadAge = 30
BufferSize = 17
MaxAssets = 8096
IgnoreTimestamps = true

SchemaVersion = 2.0
ShdrVersion = 2.0 # Set Default on all Adapters
JsonVerson = 2.0
SuppressIPAddress = true

MonitorConfigFiles = true
ConversionRequired = false
UpcaseDataItemValue = true
Pretty = true

## Security
TlsOnly = false

Adapters {
    Saw {
      Host = 10.0.0.4
      Port = 9800
    }
}

Sinks {
#     Push data from agent to a broker
    Mqtt2Service{
        MqttHost = 127.0.0.1
        MqttPort = 1883
#        MqttUserName = mtconnect
#        MqttPassword = mtconnect
        MqttClientId = mtc_agent

        ProbeTopic = mtconnect/probe/#
        CurrentTopic = mtconnect/current/#
        SampleTopic = mtconnect/sample/#
        AssetTopic = mtconnect/asset/#
        MqttCurrentInterval = 10000ms
        MqttSampleInterval = 500ms
        MqttSampleCount = 1000
    }
}


Files {
    schemas {
        Path = ../schema
        Location = /schemas/
    }
    styles {
        Path = ../styles
        Location = /styles/
    }
    Favicon {
        Path = ../styles
        Location = /styles/
    }
}

Ruby {
#   module =  ../ruby/module.rb
}

DevicesStyle { Location = /styles/styles.xsl }
StreamsStyle { Location = /styles/styles.xsl }

logger_config {
    logging_level = warn #trace, debug, info, warn, error, or fatal
    output = file /etc/mtconnect/log/agent.log
}

Attaching to mosquitto, mtc_agent
mosquitto     | 1697491746: mosquitto version 2.0.18 starting
mosquitto     | 1697491746: Config loaded from /mosquitto/config/mosquitto.conf.
mosquitto     | 1697491746: Opening ipv4 listen socket on port 1883.
mosquitto     | 1697491746: Opening ipv6 listen socket on port 1883.
mosquitto     | 1697491746: mosquitto version 2.0.18 running
mosquitto     | 1697491751: New connection from 192.168.80.4:50758 on port 1883.
mosquitto     | 1697491751: New client connected from 192.168.80.4:50758 as mtc_agent (p2, c1, k10).
mtc_agent     | [2023-10-16 21:29:06.559535] [0x00007f19d3c87780] [debug]   Cannot file path: "/usr/local/etc/mtconnect", No such file or directory
mtc_agent     | [2023-10-16 21:29:06.559654] [0x00007f19d3c87780] [debug]   Cannot file path: "/usr/local/share/mtconnect", No such file or directory
mtc_agent     | MTConnect Agent Version 2.2.0.8 - built on Tue Oct 10 21:15:56 2023
mtc_agent     | [2023-10-16 21:29:06.559848] [0x00007f19d3c87780] [trace]   Found file '/etc/mtconnect/data/dockerAgent.cfg'  in path "/etc/mtconnect"
mtc_agent     | [2023-10-16 21:29:06.559893] [0x00007f19d3c87780] [info]    Loading configuration from: "/etc/mtconnect/data/dockerAgent.cfg"
mtc_agent     | Loading configuration from:"/etc/mtconnect/data/dockerAgent.cfg"
mtc_agent     | 2023-10-16T21:29:06.570578Z (0x00007f19d3c87780) [warning] MAIN->AgentConfiguration::initialize->AgentConfiguration::loadConfig->AgentConfiguration::loadSinks: The following path "/etc/mtconnect/data/styles/old" is not a regular file: "/etc/mtconnect/data/styles/old"
mtc_agent     | 2023-10-16T21:29:06.571182Z (0x00007f19d3c87780) [warning] MAIN->AgentConfiguration::initialize->AgentConfiguration::loadConfig->AgentConfiguration::loadSinks: The following path "/etc/mtconnect/data/styles/old" is not a regular file: "/etc/mtconnect/data/styles/old"
mtc_agent     | 2023-10-16T21:29:06.597991Z (0x00007f19d3284640) [warning] : MqttClientImpl::connect: cannot connect: Connection refused, will retry

**Comment by skibum1869** [comment]
There shouldn't be a user or password issue. When I try using the username "mtconnect" password "mtconnect" it constantly disconnects as it states it is not authorized even though is it on the passwd file. 

The access control list file
```
# Allow anonymous access to the sys
topic read $SYS/#

# Allow anonymous to read MTConnect (change to read and deny when acl is implemented)
topic readwrite mtconnect/#

# Allow secure read-write to the broker from MTConnect using the mtconnect user
user mtconnect
topic readwrite mtconnect/#
```
Mosquitto conf
```
# Access Control
allow_anonymous true
password_file /mosquitto/data/passwd
acl_file /mosquitto/data/acl

# mqtt
listener 1883
protocol mqtt
```

**Comment by skibum1869** [comment]
Closing as it was a passwd file issue
