### ISSUE TITLE
* PONG10000

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#347]
Many OEM adapters have a hard coded setting of '10000' for 'PING/PONG' heartbeat.   Is there a way to ignore/override this setting at the agent level?  Use case...network latency more than expected.

**Comment by wsobel** [comment]
I think this would be possible. The protocol layers send the initial * PING from the agent and the adapter responds with a PONG. There are some nuances we need to handle like timeout and such. Also ignoring the response time if give.
