### ISSUE TITLE
GALLON/MINUTE to LITER/SECOND incorrect conversion

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#348]
Conversion incorrect.  Had to set nativeScale to get correct values.

<DataItem category="SAMPLE" id="FT_PS30_1" name="FT_PS30_1"  type="FLOW" nativeScale=".0630901964" units="LITER/SECOND">

Agent version 2.2.0.9

**Comment by wsobel** [comment]
I’ll check it out tomorrow.
