### ISSUE TITLE
Unable to use CMake(Beginner question)

### ISSUE THREAD

**Issue by chuayq** [mtconnect/cppagent#35]
Hi,

I am a beginner and I have encounter this problem and I have no idea how to solve it.

You have called ADD_LIBRARY for library cppunit without any source files. This typically indicates a problem with your CMakeLists.txt file

Best Regards,
Chua YQ

**Comment by wsobel** [comment]
Did you initialize and pull the submodules:

git submodule init
git submodule update

https://git-scm.com/book/en/v2/Git-Tools-Submodules

Best Regards,
Will Sobel

**Comment by chuayq** [comment]
Hi wsobel,

I am using Windows. I have downloaded the ZIP files from https://github.com/mtconnect/cppagent/releases (Version 1.3.0.17) and the files cppunit and libxml2 is empty. Have I done anything wrong?

From my knowledge, the above comments that you have given are for linux user. Am I right?


Best Regards and Wishes,
Chua YQ

**Comment by wsobel** [comment]
Yes, they are submodules and will only work if you clone the project using git and then pull the submodules. This allows the source to reference other projects without having to duplicate the repo. It also allows for tracking of changes and fixes.

Please use git to clone.

Best Regards,
Will Sobel

**Comment by chuayq** [comment]
Hi wsobel,

Thank you so much! Using Git I am able to clone this repository. However, I have failed to pull the submodule. 

$ git submodule init
Submodule 'cppunit' (git@github.com:openlvc/cppunit.git) registered for path 'cppunit'
Submodule 'libxml2' (git://git.gnome.org/libxml2) registered for path 'libxml2'

$ git submodule update
Cloning into 'cppunit'...
ssh_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:openlvc/cppunit.git' into submodule path 'cppunit' failed

Followed this guide - https://help.github.com/articles/checking-for-existing-ssh-keys/
Didn't work.


Best Regards and Wishes,
Chua YQ

**Comment by wsobel** [comment]
I'll check this out. Never had a problem, but will try to reproduce.  

(Sent from mobile)

**Comment by salder45** [comment]
For me, it works using´https://github.com/openlvc/cppunit.git´ instead of 'git@github.com:openlvc/cppunit.git' but I had to change the files that hold the cppunit submodule url.

Kind regards

**Comment by cteckkai** [comment]
Hi, I encountered the same problem, can I know has this problem been solved ?

**Comment by chuayq** [comment]
Hi cteckkai,

1) Cd to the location you want to save

2) Using git bash, key this: $ git clone https://github.com/https://github.com/mtconnect/cppagent.git

3) Press Enter to Clone

4) To download submodules key these : 
git submodule init
git submodule update

I am stuck on submodule update as cppunit works now but 

$ git submodule update
Cloning into 'libxml2'...
fatal: read error: Invalid argument
fatal: clone of 'git://git.gnome.org/libxml2' into submodule path 'libxml2' failed

Hopefully you can get as far as I am and come up with a solution possibly. 

Best Regards
CYQ
