### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by zm-wilcox** [mtconnect/cppagent#354]
I'm trying to build the 2.2 agents on an Ubuntu 20.04 server and the build fails every time at this step 

`mtconnect_agent/2.2: Running CMake.build()
mtconnect_agent/2.2: RUN: cmake --build "/root/.conan2/p/b/mtcon4051e7d013b68/b/build/static-x86_64/Release" -- -j1
[  1%] Building CXX object agent_lib/CMakeFiles/agent_lib.dir/__/src/mtconnect/agent.cpp.o
[  3%] Building CXX object agent_lib/CMakeFiles/agent_lib.dir/__/src/mtconnect/utilities.cpp.o
[  4%] Building CXX object agent_lib/CMakeFiles/agent_lib.dir/__/src/mtconnect/version.cpp.o
[  6%] Building CXX object agent_lib/CMakeFiles/agent_lib.dir/__/src/mtconnect/asset/asset.cpp.o
[  7%] Building CXX object agent_lib/CMakeFiles/agent_lib.dir/__/src/mtconnect/asset/cutting_tool.cpp.o
[  9%] Building CXX object agent_lib/CMakeFiles/agent_lib.dir/__/src/mtconnect/asset/file_asset.cpp.o
[ 10%] Building CXX object agent_lib/CMakeFiles/agent_lib.dir/__/src/mtconnect/asset/raw_material.cpp.o
[ 12%] Building CXX object agent_lib/CMakeFiles/agent_lib.dir/__/src/mtconnect/asset/qif_document.cpp.o
[ 13%] Building CXX object agent_lib/CMakeFiles/agent_lib.dir/__/src/mtconnect/asset/component_configuration_parameters.cpp.o
[ 15%] Building CXX object agent_lib/CMakeFiles/agent_lib.dir/__/src/mtconnect/buffer/checkpoint.cpp.o
[ 16%] Building CXX object agent_lib/CMakeFiles/agent_lib.dir/__/src/mtconnect/configuration/agent_config.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [agent_lib/CMakeFiles/agent_lib.dir/build.make:216: agent_lib/CMakeFiles/agent_lib.dir/__/src/mtconnect/configuration/agent_config.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:116: agent_lib/CMakeFiles/agent_lib.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

mtconnect_agent/2.2: ERROR:
Package 'a53922d84f367c1dde7ded0872c31233b6fef6b7' build failed
mtconnect_agent/2.2: WARN: Build folder /root/.conan2/p/b/mtcon4051e7d013b68/b/build/static-x86_64/Release
*********************************************************
Recipe 'mtconnect_agent/2.2' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: mtconnect_agent/2.2: Error in build() method, line 198
        cmake.build()
        ConanException: Error 2 while executing`

I've tried 2.2.0.10, 2.2.0.9, 2.2.0.8, and 2.2.0.3 and they all seem to fail with the same error.

**Comment by wsobel** [comment]
This is usually because the VM you're building on does not have sufficient memory. Add a swap drive.

**Comment by zm-wilcox** [comment]
I was able to get a successful build after doubling the vm's ram and cpu core and using the -c and -tf flags in the build script.

**Comment by wsobel** [comment]
On other trick, set the config option: -c "tools.build:jobs=2"

Or even 1. Conan uses the number of processors as the default. This can blow out memory on a quad core machine with 2gb of memory.
