### ISSUE TITLE
URGENT:  json output formatting error

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#360]
It appears that the json output is type casting when a SAMPLE.  There is an error if a SAMPLE is not a numeric value.   XML output represents the text accurately.

ex.   sensor on plc is unplugged and plc reports 'inf'   or 'NaN' instead of a temperature value.

The xml shows 'inf' / 'Nan' .    The json generates an error that even a browser detects.

![xmlerror](https://github.com/mtconnect/cppagent/assets/113067605/4e045b33-5a3c-4a55-b00a-aeb9ea6e9e76)
![jsonerror](https://github.com/mtconnect/cppagent/assets/113067605/ed524e98-b54d-4349-bb26-c119c3504944)
![browsererror](https://github.com/mtconnect/cppagent/assets/113067605/3aa6775b-9d9b-43d4-b20a-addcd8f62760)

Agent version 2.2.0.11

agent.cfg setting    ==  JsonVersion = 1

any chance we can get a hot fix for this?

**Comment by wsobel** [comment]
I'll need to check how the value is represented internally. if it is a nan. I'll get it in the next release.

**Comment by wsobel** [comment]
Do you have a sample of the incoming data?

**Comment by neildes2** [comment]
We feel that if its not a value then cast as a string.  Notice in the spec ref below that Infinity, -Infinity and Nan are acceptable values.   The shdr from the plc is getting -inf, inf, Nan

https://www.h-schmidt.net/FloatConverter/IEEE754.html

**Comment by wsobel** [comment]
I read the same docs and have converted them to Infinity and NaN. I'll see about -Infinity, did not handle that case.

**Comment by neildes2** [comment]
Assuming that the values will be the same in XML and Json?

**Comment by wsobel** [comment]
XML does not change and everything else remains the same.

**Comment by wsobel** [comment]
Now handles -Inf as -Infinity in json. So we have NaN, Infinity, and -Infinity. which handles the JSON cases for non-finite numbers.
