### ISSUE TITLE
Adapter ConnectionStatus ENUM doesnt match model

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#361]
Model list...

CLOSED, ESTABLISHED, LISTEN

Agent output...
CLOSED, ESTABLISHED, LISTENING
![connectionstatus1](https://github.com/mtconnect/cppagent/assets/113067605/01a23fe0-3cd4-4161-8628-7e4ea2c2e7d3)
![connectionstatus2](https://github.com/mtconnect/cppagent/assets/113067605/3bc6d284-ae0b-4cff-affe-2392faf87875)

**Comment by wsobel** [comment]
Will fix. Thanks
