### ISSUE TITLE
Agent 'hang' description

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#362]
What does reporting look like if the AGENT hangs?  I have the following data points to watch...

INSTANCEID
AdapterConnectionStatus
TagObservationRate
????

If the agent gets locked up, what depicts that condition?
Also, does the Agent Device AVAILABILITY ever go UNAVAILABLE other than at startup?

**Comment by wsobel** [comment]
Agent device availability is only unavailable on startup. 

Hang is a bug, so it is not covered as a behavior. Not sure what it should be.

**Comment by neildes2** [comment]
Thanks
