### ISSUE TITLE
MQTT Injest Paylod

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#365]
What is the MQTT json payload supposed to look like to map to the device file?  I tried variations of the following with no luck.

{
  "dataItemId": "avail",
  "value": "AVAILABLE"
}

I see the payload come into the agent.  It logs it.  But no mapping.

Agent v2.2.0.13
![2023-11-06_8-50-41](https://github.com/mtconnect/cppagent/assets/113067605/9e3c4668-6a2a-48d6-9fc8-d4298a7c658a)

![2023-11-06_8-50-20](https://github.com/mtconnect/cppagent/assets/113067605/e29bbba4-dd1d-4509-8507-a917f189626a)

**Comment by wsobel** [comment]
We don’t have a prescribed JSON format for Agent ingress. We support a SHDR payload, but if the payload begins with a curly brace “{“ we don’t have a way to interpret since there is no standard we are using.

See: https://mtcup.org/Pipeline_Architecture#mqtt-adapter-pipeline

The JsonMapper is currently disabled and JSON is handled via a custom transform for now. 

See: https://mtcup.org/Data-Transformation-Using-Ruby#mqtt-pipeline-fix-execution-state-of-a-device (JsonMapper example)

If someone suggests a JSON payload that we can map into the MTConnect model, we could implement it. The original issue was the number of IIoT sensor data representations was too diverse to “guess” the payload, so we punted on the first version. 

Suggestions are welcome.

**Comment by robot-ranger** [comment]
as a first shot suggestion, mapping SHDR as closely as possible would result in something like this:

Basic Events; simple key:value pairs:
```
{
	"timestamp": 123456789,
	"dataItemId1": "value1",
	"dataItemId2": "value2",
	...,
	...,
	"dataItemIdN": "valueN"
}
```

Conditions simply require all 6 fields:
```
{
	"timestamp": 123456789,
	"conditionId": [
		"HIGH",
		"nativeCode",
		"nativeSeverity",
		"qualifier",
		"msgContent"
	]
}
```

Messages:
```
{
	"timeStamp": 123456789,
	"messageId": [
		"nativeCode",
		"msgContent"
	]
}
```

**Comment by robot-ranger** [comment]
another approach to conditions and messages is a dict. better human readability at the cost of some more programatic formatting and arguably extraneous characters for the computer machines:

Conditions w/ a dict:
```
{
	"timestamp": 123456789,
	"conditionId": {
		"level": "HIGH",
		"nativeCode": "nativeCode",
		"nativeSeverity": "nativeSeverity",
		"qualifier": "qualifier",
		"messge": "message",
	}
}
```

same could be applied to messages

**Comment by wsobel** [comment]
Another option is to have two forms:

- A simple key/value pair with id and value
- An object with named fields for things that are more complex.
  - Condition
  - Message
  - DataSets, Timeseries, and Tables.

```json
[
  {
    "temp123": 22.6,
    "xpos": 1002.345,
    "exec": "ACTIVE"
  },
  {
    "dataItemId": "messageId",
    "nativeCode": "xxxxx",
    "value": "this is a message"
  },
  {
    "dataItemId": "conditionId",
    "conditionId": "XXX123",
    "nativeSeverity": "1000",
    "qualifier": "HIGH",
    "nativeCode": "ABC",
    "value": "something went wrong"
  },
  {
    "dataItemId": "avail",
    "value": "AVAILABLE"
  },
  {
    "dataItemId": "someTable",
    "value": {
      "A": {
        "cell1": 123,
        "cell2": 456
      },
      "B": {
        "cell1": 555,
        "cell2": 666        
      }      
    }
  }
]```

**Comment by wsobel** [comment]
Or a somple degenerate form: 

```json
{
   "timestamp": "2023-11-06T12:12:44Z",
    "temp123": 22.6,
    "xpos": 1002.345,
    "exec": "ACTIVE",
   "cond": {
      "conditionId": "XXX123",
      "nativeSeverity": "1000",
      "qualifier": "HIGH",
      "nativeCode": "ABC",
      "value": "something went wrong"
  }
}
```

**Comment by wsobel** [comment]
> another approach to conditions and messages is a dict. better human readability at the cost of some more programatic formatting and arguably extraneous characters for the computer machines:
> 
> Conditions w/ a dict:
> 
> ```
> {
> 	"timestamp": 123456789,
> 	"conditionId": {
> 		"level": "HIGH",
> 		"nativeCode": "nativeCode",
> 		"nativeSeverity": "nativeSeverity",
> 		"qualifier": "qualifier",
> 		"messge": "message",
> 	}
> }
> ```
> 
> same could be applied to messages

I'm gravitating towards something similar to this as well.

**Comment by wsobel** [comment]
@neildes2 What do you think of the latest suggestion from @robot-ranger ?

**Comment by robot-ranger** [comment]
im a little torn. i like using the dataItemId as the key for simple event data items with one field ('value'), 

but i also like explicit keys like "level" and "nativeCode" for the more complex types.

I figured the field names like level, native code, etc didnt appear in SHDR, so thats why i suggested a list in the conditions and messages.

**Comment by wsobel** [comment]
I think this from will give both:

```json
{
   "timestamp": "2023-11-06T12:12:44Z",
    "temp123": 22.6,
    "xpos": 1002.345,
    "exec": "ACTIVE",
   "cond": {
      "level": "fault",
      "conditionId": "XXX123",
      "nativeSeverity": "1000",
      "qualifier": "HIGH",
      "nativeCode": "ABC",
      "message": "something went wrong"
  }
}
```

**Comment by robot-ranger** [comment]
in keeping with data item id as the key, should the key for the condition simply be the condition's data item id?

> ```json
> {
>    "timestamp": "2023-11-06T12:12:44Z",
>     "temp123": 22.6,
>     "xpos": 1002.345,
>     "exec": "ACTIVE",
>     "conditonId": {
>       "level": "fault",
>
>       "nativeSeverity": "1000",
>       "qualifier": "HIGH",
>       "nativeCode": "ABC",
>       "message": "something went wrong"
>   }
> }
> ```

**Comment by neildes2** [comment]
How about...

[
{
"timestamp": "2022-10-21T17:20:41.4291Z"dataItemId": "avail",
"value": "AVAILABLE"
},
{
"timestamp": "2022-10-21T17:20:41.4291Z"dataItemId": "execution",
"value": "ACTIVE"
},
{
"timestamp": "2022-10-21T17:20:41.4291Z"dataItemId": "estop",
"value": "ARMED"
},
{
"timestamp": "2022-10-21T17:20:41.4291Z"dataItemId": "mode",
"value": "AUTOMATIC"
}
]

And for conditions


![image](https://github.com/mtconnect/cppagent/assets/113067605/e9572ffe-102e-4c57-9e8b-afa8f0d61946)

**Comment by neildes2** [comment]
what about DATASETs and TABLES?  Dictionary format?

**Comment by robot-ranger** [comment]
i think its 1x timestamp per payload. just like shdr. what would be the use case of bundling multiple events from various timestamps in one payload?

**Comment by robot-ranger** [comment]
the problem with 
```json
{
"timestamp": "2022-10-21T17:20:41.4291Z",
"dataItemId": "avail",
"value": "AVAILABLE"
}
```

is that you cant have multiple data items per payload without relying on alternating id & value. What happens if `"value":"[some data]"` is missing?

 using the data items' own id as the key would enable multiple events in one payload:
```json
{
"timestamp": 123456789,
"dataItemId1": "value1",
"dataItemId2": "value2",
 "..:..",
 "..:..",
"dataItemIdN": "valueN"
}

**Comment by neildes2** [comment]
I agree with you.   I like the id as the key. your suggestion below I like.  And, ONE timestamp with the payload of multiple tags like shdr.

```
{
   "timestamp": "2023-11-06T12:12:44Z",
    "temp123": 22.6,
    "xpos": 1002.345,
    "exec": "ACTIVE",
    "conditonId": {
      "level": "fault",

      "nativeSeverity": "1000",
      "qualifier": "HIGH",
      "nativeCode": "ABC",
      "message": "something went wrong"
  }
}
```

**Comment by robot-ranger** [comment]
ok, so lets see a full example:

```json
{
  "timestamp": "2023-11-06T12:12:44Z",
  // basic events:
  "temp123": 22.6,
  "xpos": 1002.345,
  "exec": "ACTIVE",
//conditions:
  "myConditonId": {
    "level": "fault",
    "nativeSeverity": "1000",
    "qualifier": "HIGH",
    "nativeCode": "ABC",
    "message": "something went wrong"
  },
//messages:
  "thisIsAMessageId": {
    "nativeCode": "ABC",
    "message": "this is a message"
  },
//table:
  "someTableId": {
    "A": {
      "cell1": 123,
      "cell2": 456
    },
    "B": {
      "cell1": 555,
      "cell2": 666        
    }    
  },
//data set:
  "aDataSet": {
    "v1": 123,
    "v2": 456,
    "v3": 789
  },
//time series:
  "aTimeSeriesId": {
    "count": 10,
    "frequency": 100,
    "values": [1,2,3,4,5,6,7,8,9,10]
  }
}
```

did i miss anything?

**Comment by wsobel** [comment]
That’s where I’m going. Traveling this week, will see how much I can get done. Got the basics finished using rapidjson, will push branch soon. 

- W

**Comment by wsobel** [comment]
Check out the latest release, 2.2.0.15, for the implementation. I will be added some more extensive error handling once we have agreed on this implementation.
