### ISSUE TITLE
sample does not report same value as current?

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#37]
It seems that there is an issue with sample command.
Sample command cannot report the current condition of the system type correctly as current command.

When the machine is first started and has no alarm I expect the condition of the system is Normal but it is not if using Sample command.
Current command does show the correct state.
Sample Command output from sequence 1 to the last sequence:
      <ComponentStream component="Controller" name="Controller" componentId="Mct1">
        <Events>
          <EmergencyStop dataItemId="Mestop" timestamp="2016-07-09T14:26:20.079063Z" name="estop" sequence="22">UNAVAILABLE</EmergencyStop>
          <EmergencyStop dataItemId="Mestop" timestamp="2016-07-09T14:26:31.0936936Z" name="estop" sequence="61">ARMED</EmergencyStop>
        </Events>
        <Condition>
          <Unavailable dataItemId="Msystem" timestamp="2016-07-09T14:26:20.079063Z" name="system" sequence="55" type="SYSTEM"/>
        </Condition>
      </ComponentStream>

It seems it cannot report sequence 110 for the Condition in Sample command

Current command output from sequence 1 to the last sequence:
      <ComponentStream component="Controller" name="Controller" componentId="Mct1">
        <Events>
          <EmergencyStop dataItemId="Mestop" timestamp="2016-07-09T14:26:31.0936936Z" name="estop" sequence="61">ARMED</EmergencyStop>
        </Events>
        <Condition>
          <Normal dataItemId="Msystem" timestamp="2016-07-09T14:26:31.0936936Z" name="system" sequence="110" type="SYSTEM"/>
        </Condition>
      </ComponentStream>

Thanks

[view-source_localhost_5000_from=1&to=110.zip](https://github.com/mtconnect/cppagent/files/355590/view-source_localhost_5000_from.1.to.110.zip)

**Comment by hulinning2** [comment]
It seems Sample only get 100 sequences at a time.
if I ask for 100 sequences at a time starting from 100 then I got the correct data
Is this how Sample command works - 100 sequences at a time only?

Thanks

**Comment by wsobel** [comment]
You can override the default by providing the count argument.

...?count=1000

Gives 1000 items. 

W

(Sent from mobile)

**Comment by hulinning2** [comment]
got it. Thanks
Note: I use _to_ instead of _count_ but no error from agent
I guess agent just ignores "to"
