### ISSUE TITLE
Need to create last will for MQTT Sink 

### ISSUE THREAD

**Issue by wsobel** [mtconnect/cppagent#371]
There is no last will and testament for the MQTT Sink. We can create a simple current and sample with all values set to unavailable for the documents.

**Comment by wsobel** [comment]
@robot-ranger  @MRIIOT 

Any ideas regarding the topic of the LWT for the agent? There is only one LWT per connection, so not sure what it should be. 

The payload could be a current with everything unavailable or something else?

Ideas welcome.

**Comment by robot-ranger** [comment]
> @robot-ranger @MRIIOT
> 
> Any ideas regarding the topic of the LWT for the agent? There is only one LWT per connection, so not sure what it should be.
> 
> The payload could be a current with everything unavailable or something else?
> 
> Ideas welcome.

I read this comment last night in bed, and at first i was thinking the agent sets the adapters dataitems to unavailable when it looses connection, but I see now that you are talking about the agent itself exiting the broker (whether by error or not)

are we moving to the mqtt2service? will the original mqttservice eventually go away?

**Comment by wsobel** [comment]
The first version had major issues with scalability. Too many pubs/s and the broker overloads pretty fast. The second scales well and gives a similar approach to spb. 

I can say the second version will be the only one we support. I have idled the first version and it will go away. We can make it a plugin if someone really wants it. 

I can also alias the second version if necessary.

**Comment by robot-ranger** [comment]
thats great. noted and we will move to mqtt2.

Is there value in LWT being a complete current response? (ie does it have to be an 'mtconnect compliant' response?)

I assume any end application breaks if the agent gets disconnected anyways. should the entire topic `MTConnect/Current/Agent` just read "Unavailable" (instead of the long form Json)? regardless of erroneous or intentional disconnect, the whole thing including /probe and /sample is technically unavailable without an agent; let alone the /current response

**Comment by wsobel** [comment]
What is the idiom for MQTT LWT topics? Is there a special topic name like, MTConnect/LastWill or something else? 

From what I read, it is usually a `status` topic with some context. We could do something like `MTConnect/Agent/Availability` which could have the value `AVAILABLE` or `UNAVAILABLE`

**Comment by robot-ranger** [comment]
> What is the idiom for MQTT LWT topics? Is there a special topic name like, MTConnect/LastWill or something else?
> 
> From what I read, it is usually a `status` topic with some context. We could do something like `MTConnect/Agent/Availability` which could have the value `AVAILABLE` or `UNAVAILABLE`

yes, status topic is common, but i havent seen any standard.

There already is an "availability" dataitem in `MTConnect/Current/Agent` topic. wouldnt that be the purpose of it? 

I did always wonder what the point of agent availability was w/ http... the agent either loads the page and agent is "Available" or it doesnt load the page/timeout/404 and obviously its unavailable.

**Comment by wsobel** [comment]
We are limited to a single topic and message for the LWT. This means we cannot change all the devices' probe, current, and sample to unavailable. 

I can do one of the following:

- create a new topic under the agent device for availability. It would need to be subscribed to. (Current implementation for test)
- I could set the agent device probe message to unavailable. 

Or some other special topic?

The LWT is pretty limited, so we need to choose how to approach. 

Best
W

**Comment by wsobel** [comment]
With http the agent is similar to a broker. If an adapter or data source disconnects, it will set all data items to unavailable. 

The agent itself will either respond or you cannot connect. If you request a non-existent device, you will get a 404 and an error body. 

Currently there is no topic for availability in the mqtt 2 service. I created one for the latest build.
