### ISSUE TITLE
Could we remove the `styles/old` folder?

### ISSUE THREAD

**Issue by ottobolyos** [mtconnect/cppagent#375]
@wsobel, I have just noticed that [`styles/old`](https://github.com/mtconnect/cppagent/tree/4dff880368043afcdd0477c65ce49ca6f96b6bad/styles/old) folder is copied to the Docker image. I think we should remove it. We could remove it either from the codebase (if not needed anymore) or add it to `.dockerignore`.

I could create a PR if you want, just tell me which solution (removal or updating `.dockerignore`) you want me to do. :pray:

**Comment by wsobel** [comment]
Please create a PR for dockerignore. Good idea. BestW(Sent from mobile)On Dec 9, 2023, at 09:33, Otto Bolyós ***@***.***> wrote:﻿
@wsobel, I have just noticed that styles/old folder is copied to the Docker image. I think we should remove it. We could remove it either from the codebase (if not needed anymore) or add it to .dockerignore.
I could create a PR if you want, just tell me which solution (removal or updating .dockerignore) you want me to do. 🙏
