### ISSUE TITLE
[`v2.2.0.16 Docker`] - Multiple MQTT Sources

### ISSUE THREAD

**Issue by MRIIOT** [mtconnect/cppagent#377]
What am I doing in the below config?  The result is that I only get one of the MQTT sources DataItems populating, but not the other three.

```
Adapters {
   HCN001 {
     Url = http://mtconnect.mazakcorp.com:5719
     SourceDevice = HCN001
   }

   48e7290b1184 {
     #Device = 48e7290b1184
     Protocol = mqtt
     MqttHost = wss.sharc.tech
     MqttPort = 1883
     MqttClientId = ox003_sharc_48e7290b1184
     Topics = mtc/ingest/48e7290b1184
   }

   e831cd9a4020 {
     #Device = e831cd9a4020
     Protocol = mqtt
     MqttHost = wss.sharc.tech
     MqttPort = 1883
     MqttClientId = ox003_sharc_e831cd9a4020
     Topics = mtc/ingest/e831cd9a4020
   }

   e831cd9a6564 {
     #Device = e831cd9a6564
     Protocol = mqtt
     MqttHost = wss.sharc.tech
     MqttPort = 1883
     MqttClientId = ox003_sharc_e831cd9a6564
     Topics = mtc/ingest/e831cd9a6564
   }

   409151d72b38 {
     #Device = 409151d72b38
     Protocol = mqtt
     MqttHost = wss.sharc.tech
     MqttPort = 1883
     MqttClientId = ox003_sharc_409151d72b38
     Topics = mtc/ingest/409151d72b38
   }
}
```

```xml
<Device id="48e7290b1184" name="SHARC_48e7290b1184" uuid="00000000-0000-0000-1337-48e7290b1184">
	<Description manufacturer="Frenzy Engineering" serialNumber="48e7290b1184">SHARC</Description>
	<DataItems>
		<DataItem category="EVENT" id="48e7290b1184_avail" type="AVAILABILITY"></DataItem>
		<DataItem category="EVENT" id="48e7290b1184_pcc" type="PART_COUNT" subType="COMPLETE"></DataItem>
	</DataItems>
</Device>
<Device id="e831cd9a4020" name="SHARC_e831cd9a4020" uuid="00000000-0000-0000-1337-e831cd9a4020">
	<Description manufacturer="Frenzy Engineering" serialNumber="e831cd9a4020">SHARC</Description>
	<DataItems>
		<DataItem category="EVENT" id="e831cd9a4020_avail" type="AVAILABILITY"></DataItem>
		<DataItem category="EVENT" id="e831cd9a4020_pcc" type="PART_COUNT" subType="COMPLETE"></DataItem>
	</DataItems>
</Device>
<Device id="e831cd9a6564" name="SHARC_e831cd9a6564" uuid="00000000-0000-0000-1337-e831cd9a6564">
	<Description manufacturer="Frenzy Engineering" serialNumber="e831cd9a6564">SHARC</Description>
	<DataItems>
		<DataItem category="EVENT" id="e831cd9a6564_avail" type="AVAILABILITY"></DataItem>
		<DataItem category="EVENT" id="e831cd9a6564_pcc" type="PART_COUNT" subType="COMPLETE"></DataItem>
	</DataItems>
</Device>
<Device id="409151d72b38" name="SHARC_409151d72b38" uuid="00000000-0000-0000-1337-409151d72b38">
	<Description manufacturer="Frenzy Engineering" serialNumber="409151d72b38">SHARC</Description>
	<DataItems>
		<DataItem category="EVENT" id="409151d72b38_avail" type="AVAILABILITY"></DataItem>
		<DataItem category="EVENT" id="409151d72b38_pcc" type="PART_COUNT" subType="COMPLETE"></DataItem>
	</DataItems>
</Device>
```

Data at broker:
<img width="374" alt="image" src="https://github.com/mtconnect/cppagent/assets/48079336/98dbd94c-60ab-49e6-817b-7fae21d77d8c">

Data at agent:
<img width="1181" alt="image" src="https://github.com/mtconnect/cppagent/assets/48079336/eba24970-3e7d-410b-bdd1-a2b30e1b51b6">

**Comment by MRIIOT** [comment]
I tried this as well but neither work.

```
Adapters {
   ox003_sharcs {
     #Device = 48e7290b1184
     Protocol = mqtt
     MqttHost = wss.sharc.tech
     MqttPort = 1883
     MqttClientId = ox003_sharcs
     Topics = mtc/ingest/48e7290b1184 mtc/ingest/e831cd9a4020 mtc/ingest/e831cd9a6564 mtc/ingest/409151d72b38
   }
```

```
Adapters {
   ox003_sharcs {
     #Device = 48e7290b1184
     Protocol = mqtt
     MqttHost = wss.sharc.tech
     MqttPort = 1883
     MqttClientId = ox003_sharcs
     Topics = mtc/ingest/#
   }
```

**Comment by wsobel** [comment]
There is one client id for all the adapters. Currently all adapters have their own connection so these would conflict. 

The latest version randomizes the client ids so it should work if you just remove the config item for the client id or make each unique. 

I was thinking of mqtt connection pooling as a new feature across sources and sinks. We can consider it since they all use common infrastructure.

**Comment by MRIIOT** [comment]
Should wildcards or multiple topics in a single adapter work?
A single adapter for multiple devices should work right, if it's based on DataItem id?

**Comment by MRIIOT** [comment]
> The latest version randomizes the client ids so it should work if you just remove the config item for the client id or make each unique.

Last Docker image is 4 days old.  When does it build?

**Comment by MRIIOT** [comment]
> I was thinking of mqtt connection pooling as a new feature across sources and sinks. We can consider it since they all use common infrastructure.

Makes sense.  If I have four sources and two sinks, going from 6 connections to 1.

**Comment by wsobel** [comment]
The latest version is 4 days old.

**Comment by wsobel** [comment]
> Should wildcards or multiple topics in a single adapter work?
> A single adapter for multiple devices should work right, if it's based on DataItem id?

A wild card, `.../#` works as a topic. Also, you can provide a topic list. 

The value is a data item source, name, or id. Since the ids have to be unique, names and sources make it easier. 

I think I'm resolving the device before resolving the data item id. I'll check. 

Each device can publish using the device name or uuid as a key and then the data item within as another option.
