### ISSUE TITLE
program header characters?

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#38]
I sent the following characters from part program header to agent but agent only reports some as shown below:

Adapter data:
p1ProgramHeader|(Comment: <>~!@#$%^&_`{}|:"<>?[]\;',./)|(second comment line)|(SPECIAL !@#$%^&_~)|

Agent data:
<ProgramHeader dataItemId="Lp1ProgramHeader" timestamp="2016-09-15T17:57:59.701Z" name="p1ProgramHeader" sequence="2815">(Comment: &lt;&gt;~!@#$%^&amp;*`{}</ProgramHeader>

Agent drops everything after these characters:
(Comment: <>~!@#$%^&*`{}

Thanks

**Comment by hulinning2** [comment]
remove "|" work ok now.

**Comment by hulinning2** [comment]
Is that possible to support this character "|" in program comment or header?
I can see that if we pass this character to agent it will think it is a key value pair and it will drop everything after this.
This could happen in any tag that includes this character as its value

**Comment by ZhouBox** [comment]
https://github.com/mtconnect/cppagent#adapter-agent-protocol-version-13，‘|’ is a part of agent protocol.

**Comment by hulinning2** [comment]
I do understand that it is part of agent protocol using SHDR to receive data from adapter. I just would like know if we have a special escape sequence to recognize this character. If our adapter needs to capture every keystroke on NC then it is not possible in this case when user presses "|".

**Comment by wsobel** [comment]
Linh,

This is a good point. We don't currently have an escape character, but we could add something. There is multi line support, but is meant for assets. I'll take a look at the agent and get back with some ideas. 

Best
W

(Sent from mobile)

**Comment by wsobel** [comment]
There is a new capability in the 1.5 branch submitted by lorenzhaas to allow for escaping characters. This will probably address the issue. I will build into next RC or you can pull from version_1.5 head. It has also been merged to master as well.
