### ISSUE TITLE
MQTT out viewed in Ignition

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#381]
Team asking why the format is this way with what appears to be ordinal positions.  Seems a bit Too verbose, no?  Or is this an Ignition MQTT ENGINE parsing issue?  Would hate to have to write a new interpreter/transformer.

![ignitionview](https://github.com/mtconnect/cppagent/assets/113067605/47b6f675-47d4-4750-8477-cdd14e1d7a8c)

**Comment by neildes2** [comment]
I think we are looking for a device hierarchy  model/ tree rather than a CONDITION / SAMPLES / EVENTS groupings.

**Comment by wsobel** [comment]
I think the simple answer is, that ignition is based on SpB and does not handle structured data very well. It is making a mess out of the JSON and giving a full JPath associated with each element. This is a näive approach assuming simple JSON coming in. 

The format is the MTConnect semantic streams model in JSON. It is what you get when you make a current or sample request and organize the data accordingly.  

We can provide SpB as another sink (there is one available from now) that would be more ignition-friendly. We could also have an ignition-specific mqtt/json sink that structured the data in a different way that differs from the existing model. 

There is a lot that "could" be done. It deserves a discussion.

**Comment by MRIIOT** [comment]
The other issue you will experience with vanilla JSON in Ignition is that when incoming array size changes, it will leave orphans in your Ignition tag provider.  Meaning, if you start with an array of 5, and then that array changes to size of 2 from source, you will still have 5 in Ignition.

**Comment by wsobel** [comment]
Another option is to raise an issue with ignition to have more robust json parsing support. Since they are a licensed product, this should be something they can do.

**Comment by neildes2** [comment]
understood.  Thanks
