### ISSUE TITLE
MQTT Ingress testing results

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#384]
Used the sample payloads provided in other issue.  All worked great except for Datasets.  You had TABLE and DATASets using the same payload.  I created a successful DATASETS payload.  Here are the ones I used for this successful testing...

events/samples
{
  "execution": "ACTIVE",
  "mode": "AUTOMATIC"
}

----------------------------------------------------
Conditions and messages

{
  "timestamp": "2023-11-09T11:20:00Z",
  "cond": {
    "level": "fault",
    "nativeCode": "256",
    "nativeSeverity": 1000,
    "qualifier": "HIGH",
    "value": "high temperature fault"
  },
  "b": {
    "nativeCode": "874",
    "value": "some text"
  }
}

----------------------------------------------
Timeseries

{
  "timestamp": "2023-11-09T11:20:00Z",
  "a": {
    "sampleRate": 8000,
    "value": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  }
}

----------------------------------------------------
DataSets

{
  "timestamp": "2023-11-09T11:20:00Z",
  "a": {
    "resetTriggered": "NEW",
    "value": {"r1":"val1", "r2":"val2", "r3":"val3" }
    }
 }

-------------------------------------------------
tables

[{
  "timestamp": "2023-11-09T11:20:00Z",
  "a": {
    "r1": {
      "k1": 123.45
    },
    "r2": {
      "k2": "ABCDEF",
      "k3": 6789
    }
  }
},
{
  "timestamp": "2023-11-09T11:20:00Z",
  "a": {
    "resetTriggered": "NEW",
    "value": {
      "r1": {
        "k1": 123.45,
        "k3": 6789
      },
      "r2": null
    }
  }
}]

**Comment by neildes2** [comment]
Just as an fyi / benchmark...

Early testing show 5800 obs/sec rate for payloads through a broker and subscribed to by the agent....no resource values yet.

-likely the limit is the sending app.  But impressing none the less.

Mosquitto Broker
v2.2.0.16 agent

**Comment by wsobel** [comment]
Thanks for the test. I ramped the agent up to 250k obs/sec. I agrée, prob either sender or broker. Thx W(Sent from mobile)On Dec 22, 2023, at 21:28, neildes2 ***@***.***> wrote:﻿
Just as an fyi / benchmark...
Early testing show 5800 obs/sec rate for payloads through a broker and subscribed to by the agent....no resource values yet.
-likely the limit is the sending app.  But impressing none the less.
Mosquitto Broker
v2.2.0.16 agent
