### ISSUE TITLE
AGENT Device Observationrate stops reporting

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#388]
We have witnessed the agent stop reporting Observation rate.  It reports every 10 secs.  after some days, it seems to stop.  Is there a reason for this?  By Design?

The device was offline and the adapter reporting last known values to the agent every minute.  Agent clearly filters out dups.

Agent v2.2.0.14

**Comment by wsobel** [comment]
The agent should keep reporting. It does duplicate removal, that may be why–the value never changes from 0. I can test it out. 

The rates are not reported by the adapter; they are posted by a separate async activity in the pipeline that measures the observation delivery rate. It then posts the rate back into the pipeline.

- W

**Comment by neildes2** [comment]
The buffer had numerous "ZERO" values sequencially.  Doesnt look like it was stopping dups.  Then it stopped.   Is it possible that the agent is round to zero?  Then when it actually stay ZERO it stops the dups?

**Comment by wsobel** [comment]
I’ll check this out. It is odd behavior. Are there any conditions when it stops reporting? (Sent from mobile)On Jan 5, 2024, at 18:35, neildes2 ***@***.***> wrote:﻿
The buffer had numerous "ZERO" values sequencially.  Doesnt look like it was stopping dups.  Then it stopped.   Is it possible that the agent is round to zero?  Then when it actually stay ZERO it stops the dups?

**Comment by wsobel** [comment]
Can you attach the log files? It should log if it stops. (Sent from mobile)On Jan 5, 2024, at 20:38, William Sobel ***@***.***> wrote:﻿I’ll check this out. It is odd behavior. Are there any conditions when it stops reporting? (Sent from mobile)On Jan 5, 2024, at 18:35, neildes2 ***@***.***> wrote:﻿
The buffer had numerous "ZERO" values sequencially.  Doesnt look like it was stopping dups.  Then it stopped.   Is it possible that the agent is round to zero?  Then when it actually stay ZERO it stops the dups?

**Comment by wsobel** [comment]
Any luck finding the agent logs?

**Comment by neildes2** [comment]
No luck on the logs.  waiting for it to happen again.   But attached is a pic of a buffer capture.  Notice it does fill up with ObservationRate all zeros every ten secs.  The issue that happened showed this had stopped.
![image](https://github.com/mtconnect/cppagent/assets/113067605/eb17827e-144c-4c2c-9413-8a5c6512ae6e)

**Comment by wsobel** [comment]
Looks ok. There are a few reasons it can stop, the adapter dies or the pipeline is restarted. This can happen when the adapter reconnects and some commands are sent from the adapter to change the configuration. 

I'm wondering if there is a race of the stop-and-start or something else that could cause it. I tried to reproduce and could not make it happen. It does log connection status and stats timer, so i need to check what's happening.

**Comment by wsobel** [comment]
Any progress on getting the logs?

**Comment by wsobel** [comment]
I wonder if this was related to issue #419. Try to retest with build 2.3.0.4.

**Comment by neildes2** [comment]
Have not witnessed it lately.  I will close it out for now.  If I witnes again, I will find out the root cause and report an issue
