### ISSUE TITLE
UUID Adapter Configuration Item

### ISSUE THREAD

**Issue by rwuthric** [mtconnect/cppagent#394]
I am trying to understand how works the `UUID` adapter configuration item of the agent configuration file.

The documentation says: `UUID` - Replaces the UUID attribute in the device XML.

I tried the following agent config file with the latest agent version:
```
Devices = device.xml
Port = 5000
SchemaVersion = 2.0

Adapters {

    Adapter {
       UUID = NEW-UUID
       Host = ....
       Port = 7878
    }

}
```
but the agent keeps reporting the UUID taken fromt he device XML file.

I tried as well combinations with adding `PreserveUUID = true` or `PreserveUUID = false` but still the agent keeps reporting the UUID taken from the device XML file. Obviously I do something wrong.

How one is supposed to use correctly the `UUID` item in order to overwrite the device UUID from the device XML file?

**Comment by wsobel** [comment]
Can you upload your device.xml and agent.xml so I can check. The only thing I can think of is the `Adapter` should be the device name or specify the `Device` in the adapter block. That way the agent knows which device to modify.

If there is only one device, the UUID _may_ apply to the default device. I'll check if it is more explicit in the initialization phase. 

```
Adapters {

    Adapter {
       UUID = NEW-UUID
       Host = ....
       Port = 7878
    }

}
```

**Comment by wsobel** [comment]
This does appear to be an issue. It appears that the changes in the initialization and dynamic update of the device blew away the static UUID replacement. I have added a test and will fix the issue.

**Comment by rwuthric** [comment]
In case still required and helpful.

Here the content of `device.xml`:
```
<MTConnectDevices>
  <Devices>
    <Device uuid="DHT-GEN" id="dht" name="ESP8266-DHT">

      <!-- General information -->
      <Description>
         Humidity and Temperature Sensor (DHT)
      </Description>
      <DataItems>
        <DataItem category="EVENT" id="avail" type="AVAILABILITY"/>
      </DataItems>

      <!-- Components -->
      <Components>

        <!-- Sensor -->
        <Sensor id="sensor">

          <!-- Configuration -->
          <Configuration>
            <SensorConfiguration>
              <FirmwareVersion>0.1</FirmwareVersion>
              <Channels>
                 <Channel number="1" name="Temperature">
                   <Description>Temperature in celcius</Description>
                 </Channel>
                 <Channel number="2" name="Humidity">
                   <Description>Relative humidity</Description>
                 </Channel>
              </Channels>
            </SensorConfiguration>
          </Configuration>

          <!-- DataItems -->
          <DataItems>
            <DataItem category="SAMPLE" id="Temp" type="TEMPERATURE" units="CELCIUS"/>
            <DataItem category="SAMPLE" id="Humi" type="HUMIDITY_RELATIVE" units="PERCENT"/>
          </DataItems>

        </Sensor>

      </Components>
    </Device>
  </Devices>
</MTConnectDevices>
```
and the agent config file:
```
AgentDeviceUUID = $MTC_AGENT_UUID
Devices = device.xml
Port = 5000
SchemaVersion = 2.0

Adapters {

    Adapter {
       UUID   = DHT-001
       Host   = $ADAPTER_IP
       Port   = $ADAPTER_PORT
    }

}

Files {
    schemas {
        Path = /mtconnect/data/schemas
        Location = /schemas/
    }
    styles {
        Path = /mtconnect/data/styles
        Location = /styles/
    }
    Favicon {
        Path = /mtconnect/data/styles/favicon.ico
        Location = /favicon.ico
    }
}

DevicesStyle {
    Location = /styles/styles.xsl
}
StreamsStyle {
    Location = /styles/styles.xsl
}

logger_config
{
    logging_level = info
    output = file /home/agent/log/mtc_agent.log
}
```
The agent keeps reporting `DHT-GEN` instead of the expected `DHT-001`.

Our use case is that the device information model `device.xml` is a generic one (in a device model repository) for a DHT type sensor, and as the actual devices are deployed, the agents are configured with their unique UUIDs.

**Comment by wsobel** [comment]
Thanks, I'll fix the issue and verify with the files.
