### ISSUE TITLE
PERIODS in tag names (MQTT Egress)

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#398]
1) Ignition doesn't like periods in tag names.
2) Canary uses periods as separators.
Can these be changed to 'underscores'?  

ex.         Agent.3519a48b-814b-3425-a12d-ef250947ab3d

**Comment by wsobel** [comment]
We can change it. Any other characters?Ignition is a pain. BestW(Sent from mobile)On Jan 22, 2024, at 19:36, neildes2 ***@***.***> wrote:﻿

Ignition doesn't like periods in tag names.
Canary uses periods as separators.
Can these be changed to 'underscores'?

ex.         Agent.3519a48b-814b-3425-a12d-ef250947ab3d

**Comment by neildes2** [comment]
All else seems to be good.  Thanks for the quick response.

**Comment by wsobel** [comment]
We should check to make sure this is ok with the WG before merging.

**Comment by wsobel** [comment]
Or we can use a pattern. Not sure what is the best approach. I don't think anyone's depending on this at the moment except BO.

**Comment by neildes2** [comment]
ANy discussions in the Agent WG about this?  I have an immediate  need to get this resolved.

**Comment by wsobel** [comment]
I will try to attend the next agent WG meeting. We should prioritize this discussion as the change can be released at any time. On Feb 7, 2024, at 16:48, neildes2 ***@***.***> wrote:﻿
ANy discussions in the Agent WG about this?  I have an immediate  need to get this resolved.

**Comment by dwickelhaus** [comment]
I added issue 3219 to address this issue.  I will bring it up Friday.
https://projects.mtconnect.org/issues/3219
