### ISSUE TITLE
Make 'sender' configurable to support docker

### ISSUE THREAD

**Issue by scottmwyant** [mtconnect/cppagent#409]
I have multiple containerized agents running at the edge, the value of the `sender` attribute in the `<Header>` of response documents is the container which is not meaningful as containers are ephemeral.  It would be more meaningful to identify the docker host here. Doing this via configuration (agent.cfg) is perfectly fine.  Having environment variables evaluated before applied to agent config would be good here, sounds like that's already supported.

Do you use the cfg file to map an environment variable to the agent config? Or do you just need to use a naming convention for the env variable itself, similar to `NODE_OPTIONS`, or `DOTNET_ENVIRONMENT`?

---
An email from @wsobel, December 2, 2023:

> Sender is currently the primary NIC IP address with a name lookup.  
>
> It should be the same as what’s in hostname in *NIX. Not too much attention has been paid to it in the past. 
>
> It could be configurable, never had the request before. If we add it to the configuration file it can be set from an environment variable. Environment variable handling is already supported.

**Comment by wsobel** [comment]
This would be easy to implement. The agent cfg file already supports environment variables. 

We could add:

`Sender = $SENDER_NAME`

Where SENDER_NAME is an environment variable that can be passed to the container. 

Does that work?

**Comment by scottmwyant** [comment]
Yes, you got it.  Thank you!
