### ISSUE TITLE
Add * uuid: to the README and make sure all the other adapter commands are documented

### ISSUE THREAD

**Issue by wsobel** [mtconnect/cppagent#412]
Some of the adapter commands are not documented in the README.md. We need to review the code and make sure they are all documented properly. There are two places they are implemented. The adapter related commands are in the SHDR adapter and the agent related commands are in the agent.cpp in the receiveCommand method.

**Comment by dwickelhaus** [comment]
I will volunteer to do this if it will help out.

**Comment by wsobel** [comment]
Thanks Dave. Tell me if you need more pointers. (Sent from mobile)On Feb 14, 2024, at 16:15, Dave Wickelhaus ***@***.***> wrote:﻿
I will volunteer to do this if it will help out.

**Comment by dwickelhaus** [comment]
Will, there were only two command that I found that are not documented in the README.md file.
The * UUID: command you mentioned and the * deviceModel:.  Both of these are processed in agent::receiveCommand method.

I will add these to the README.md file.  Everything in the shdr_adapter appears to be documented.

**Comment by wsobel** [comment]
Good catch. The deviceModel command can also have a multiline content. I’ll paste a sample a little later. ThanksW(Sent from mobile)On Feb 22, 2024, at 21:03, Dave Wickelhaus ***@***.***> wrote:﻿
Will, there were only two command that I found that are not documented in the README.md file.
The * UUID: command you mentioned and the * deviceModel:.  Both of these are processed in agent::receiveCommand method.
I will add these to the README.md file.  Everything in the shdr_adapter appears to be documented.

**Comment by wsobel** [comment]
Closed by @dwickelhaus
