### ISSUE TITLE
Unclear logging at startup when using Docker

### ISSUE THREAD

**Issue by scottmwyant** [mtconnect/cppagent#417]
As far as I can tell, this is not a functional issue, but potentially makes things confusing for those less experienced with containers (yours truly).  I'm writing, only to offer feedback on newer features I'm looking to use; prioritize accordingly.

Docs [here ](https://hub.docker.com/r/mtconnect/agent) show mounting `/mtconnect/config` to the host.

- Agent appears to look in a few other places for config files first, before getting to `/mtconnect/config`.  Would it be more natural to drop the config in `/etc/mtconnect/...`?
- There are two lines that indicate config is being loaded from `/mtconnect/config/agent.cfg` but one line giving conflicting information, saying config is being loaded from `/mtconnect/config/agent.cfg` _in path_ `/home/agent`.  The config is in fact, not relative to the user's home directory.

![image](https://github.com/mtconnect/cppagent/assets/29161635/8519407a-336a-4e03-8e0c-9b58ce6fbc17)

**Comment by wsobel** [comment]
It looks in some default locations. The logging level probably should be changed to debug. I get where it can be confusing. 

The search order is preset, but can be overridden by specifying the cfg file with full path as the third argument. 

I'll change the logs level to debug.
