### ISSUE TITLE
Can agent support Unicode?

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#42]
Our adapter can receive JIS characters without a problem; however, when I check agent output stream all Japanese characters are displayed as question mark only as seen in the captured image

![image](https://cloud.githubusercontent.com/assets/4930742/20985105/03f8a8fc-bc91-11e6-99e2-27f789a0c043.png)

Can agent support Unicode?

Thanks

**Comment by wsobel** [comment]
Can you re-encode as UTF-8?

Best Regards,
Will Sobel
