### ISSUE TITLE
MQTT INGRESS connection not working on V2.3.0.4

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#438]
V2.3.0.2 works fine.  Updated to v2.3.0.4 and it will not connect to broker.

cfg excerpt
--------------------------------------------
Adapters {
    
 device {
        
        Url = mqtt://mybroker.com/
        MqttPort = 1883
        MqttUserName = user
        MqttPassword = password
        Topics = "test/ingest/testmachine/#"
        MqttClientId = test1
		
 }
 
}

**Comment by wsobel** [comment]
Please include logs from the agent. I will take a look.

**Comment by wsobel** [comment]
Also, what configuration are you using on your broker?

Username, password, TLS? Certificates?

**Comment by neildes2** [comment]
[agent.log](https://github.com/mtconnect/cppagent/files/14951932/agent.log)

Broker only using username and pwd.

**Comment by wsobel** [comment]
Found the issue. Created PR and will fix in 2.3.0.7

**Comment by wsobel** [comment]
Found issue, but now getting failures in testing. Looks like it fails during shutdown. Will fix soon.
