### ISSUE TITLE
How to set initial dataitem value in the stream

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#440]
How can i get a value loaded into a dataitem that never changes.  Like a Constant.   I tried initial value in the example below but it doesn't seem to be its intention.

Specification values are not reported in the stream.

```xml
           <DataItem id="Pcount" type="PART_COUNT" category="SAMPLE" units="COUNT">
              <InitialValue>125</InitialValue>  
            </DataItem>
```

**Comment by wsobel** [comment]
We need to decide on the behavior. When the device is unavailable it should be unavailable. When the device becomes available it will assume the initial value.
