### ISSUE TITLE
Check why asset counts are not being reported in agent

### ISSUE THREAD

**Issue by wsobel** [mtconnect/cppagent#446]

**Comment by robot-ranger** [comment]
asset count seems to work for me:
![image](https://github.com/mtconnect/cppagent/assets/93950632/b06b71f2-cc66-4dc1-a34c-ed432e2dfcb4)
 (posted w/ REST via curl, anyways, we havent tried assets over SHDR yet)
or are you referring to something else?

**Comment by wsobel** [comment]
Yes, we discussed in the EC and it is working. Not sure what this issue is about.

**Comment by wsobel** [comment]
Closing issues since it appears to be working.
