### ISSUE TITLE
Issue with cloning submodules

### ISSUE THREAD

**Issue by NLandry91** [mtconnect/cppagent#45]

**Comment by wsobel** [comment]
I'll check the submodule URI and make sure it can be cloned... I think I remember this appearing before.

**Comment by NLandry91** [comment]
I'm having an issue with cloning the cppagent. I searched the prior issues and I'm still not sure what the problem is. I enter the following code in the windows command prompt:
git clone https://github.com/mtconnect/cppagent.git
cd cppagent
git submodule init
git submodule update

I get this error (attached)
![issue](https://cloud.githubusercontent.com/assets/8760347/22567735/2230ca66-e95f-11e6-8af7-8ce974bde149.JPG)

**Comment by wsobel** [comment]
Just pushed a change that uses https://git.gnome.org/browse/libxml2 <https://git.gnome.org/browse/libxml2> as the url instead of the git: protocol that seems to have issues on windows. Try to pull and see if it works…

Best,
W

**Comment by NLandry91** [comment]
![issue2](https://cloud.githubusercontent.com/assets/8760347/22568407/c8c6ebf6-e961-11e6-9f59-93bb6f7ffd05.JPG)

Not sure if this is what you meant...

**Comment by wsobel** [comment]
pull the latest version of the agent code and see if the changes in the .gitmodules file fixes the submodule update issue.

**Comment by NLandry91** [comment]
Hi Will,

Just tried it. Perfect! Thanks for looking into that!

Nick
