### ISSUE TITLE
MQTT Adapter disconnect

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#460]
I have an v2.3.0.2 agent connected to a broker for mqtt ingress.  Working great.  But when it loses connection, shouldn't the agent set all tags to UNAVAILABLE?  I have stale data for days.

**Comment by wsobel** [comment]
Which version of the MQTT sink are you using? I am deprecating the first because of issues like this.

**Comment by neildes2** [comment]
Devices = Devices.xml
AllowPut = true
AllowPutFrom = localhost
Port = 5000
ReconnectInterval = 1000
BufferSize = 17
MaxAssets = 1024
SchemaVersion = 2.3
ShdrVersion = 1
SuppressIPAddress = false
MonitorConfigFiles = false
WorkerThreads = 2
JsonVersion = 1
DisableAgentDevice = false
ConversionRequired = true
IgnoreTimestamps = true
Pretty = true
PreserveUUID=true
FilterDuplicates=yes

Adapters {
   # Log file has all machines with device name prefixed
   machine1 {
   		  Url = mqtt://127.0.0.1/
        MqttPort = 1883
        MqttUserName = user1
        MqttPassword = "p1"
        Topics = "machine1/ingress/#"
        MqttClientId = client-1

   }
}

# Logger Configuration
logger_config
{
    logging_level = trace
}

**Comment by neildes2** [comment]
shdr adapter disconnect sets all tags to UNAVAILABLE. 

2024-06-13T14:50:00.973341Z (0x000057d4) [debug] Connector::reader->Connector::reconnect->Connector::close: Disconnected from adapter, setting all values to UNAVAILABLE

But mqtt adapter (Broker) disconnect does not.

**Comment by neildes2** [comment]
Should this be a param? ON/OFF    Use case...broker is 2nd adapter for sensors?  USe case...Broker is primary adapter and should set all tags to UNAVAILABLE.

Maybe an adapter level parameter 'Primary=true'
Which ever adapter is the primary, if it gets disconnected, it sets all tags to UNAVAILABLE

**Comment by wsobel** [comment]
This sounds reasonable behavior. I will take a look and see what it is doing now. May be a couple of days.

**Comment by wsobel** [comment]
The disconnect behavior is built into the agent. Must not be forwarding disconnect from broker signal. 

Is this when the broker disconnects or when the source disconnects from the broker?

**Comment by neildes2** [comment]
In this test case, I pulled the network cable causing the disconnect from the broker.  For the shdr test, I just turned off my local adapter.

**Comment by wsobel** [comment]
Thanks. I'll disconnect my broker and test the behavior.

**Comment by wsobel** [comment]
@neildes2 Please test

**Comment by neildes2** [comment]
Downloading and testing now....

**Comment by neildes2** [comment]
This issue is NOT resolved.

tested on Agent v2.3.0.11

All tags do NOT reset to UNAVAILABLE upon mqtt broker ingest disconnect.

**Comment by wsobel** [comment]
Only the observations from the adapter will be set to unavailable. Check to see if any are reset. I tested it and when I killed the broker they reset to unavailable.

**Comment by neildes2** [comment]
when I tested the shdr adapter, the device AVAILABILITY tag went UNAVAILABLE.  When I tested with broker adapter, it did not.

**Comment by wsobel** [comment]
Did the shdr adapter set the availability item to AVAILABLE? I will check to see if how auto available is handled.

**Comment by wsobel** [comment]
I think I found the issue.

**Comment by neildes2** [comment]
Just tested v2.3.0.13.   When I disable my wireless connection, the broker adapter disconnects and the agent states...."] MqttClientImpl::disconnected: Disconnected from adapter, setting all values to UNAVAILABLE".    But the device Tags all remain stale at AVAILABILITY=AVAILABLE and EXECUTION = ACTIVE.  Even the AGENT device AVAILABILITY remains AVAILABLE

**Comment by neildes2** [comment]
Devices = Devices.xml
AgentDeviceUUID = "3519a48b-814b-3425-a12d-ef250947ab3d"
PreserveUUID = true
Port = 5000
BufferSize = 17
MaxAssets = 1024
SchemaVersion = 2.2
ShdrVersion = 1
SuppressIPAddress = false
DisableAgentDevice = false
MonitorConfigFiles = false
WorkerThreads = 2
JsonVersion = 1
ConversionRequired = true
IgnoreTimestamps = true
Pretty = true
HeartBeat = 60000

**Comment by wsobel** [comment]
Are you using the docker hub image?

**Comment by neildes2** [comment]
No.  Downloading the WINDOWS compiled agent from this repo

**Comment by wsobel** [comment]
Agent device should be available. If the agent is running.

**Comment by neildes2** [comment]
If I have TWO adapters defined that feed to one device, and only ONE of them gets disconnected, what happens?
If I have TWO adapters defined that feed to SEPARATE devices, and only ONE of them gets disconnected, what happens?

**Comment by wsobel** [comment]
If two adapters are associated with the device, the data items set by each adapter will become unavailable if it disconnects. The others will not. Availability is controlled by the first adapter using AutoAvailable=true (default). This will allow the adapter to control the Availability data item. 

I think any adapter with AutoAvailable true will try to set Availability when it disconnects. If availability is directly set by an adapter, then it will be associated with only that adapter. 

The source of the data and the disconnect only effect the data items associated with the adapter. The code marks all data items and the last adapter they received data from.

**Comment by wsobel** [comment]
Use `AutoAvailable = true` in the adapter config to make the Availability change to `UNAVAILABLE` when disconnected.

I found some issues with the adapter data item connection. Just created a new PR.

**Comment by neildes2** [comment]
works as expected now!  Great work.
