### ISSUE TITLE
Broken header link to mtconnect.org

### ISSUE THREAD

**Issue by russwaddell** [mtconnect/cppagent#47]
`<MTConnectDevices xmlns:m="urn:mtconnect.org:MTConnectDevices:1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mtconnect.org:MTConnectDevices:1.1" xsi:schemaLocation="urn:mtconnect.org:MTConnectDevices:1.1 http://www.mtconnect.org/schemas/MTConnectDevices_1.1.xsd">`

Links at line 2 referencing schema XSD on mtconnect.org are no longer valid. The same files are on GitHub at https://github.com/mtconnect/schema

**Comment by wsobel** [comment]
http://schemas.mtconnect.org/schemas/... 

All the schema will be posted there. Syncs with GitHub.

**Comment by MZorzy** [comment]
404

**Comment by wsobel** [comment]
The link should be:

http://schemas.mtconnect.org/schemas/MTConnectDevices_1.3.xsd

Replace the Devices with the other schema names. This is the default link in 1.4 agent. 

(Sent from mobile)
