### ISSUE TITLE
Agent to Agent Connection: Filtering not working

### ISSUE THREAD

**Issue by nickamenda** [mtconnect/cppagent#475]
When trying to use filters on an agent to agent connection, the filters are not taking effect.

Example Code: 
`<DataItem category="SAMPLE" id="xxxxx" name="currentRunTime" nativeUnits="SECOND" type="ms:CURRENT_RUN_TIME" units="SECOND">
    <Filters>
        <Filter type="PERIOD">1</Filter>
    </Filters>
</DataItem>`
Still comes in as milliseconds, does not filter down to once a second.

![Screenshot 2024-06-28 at 12 31 06 PM](https://github.com/mtconnect/cppagent/assets/104174057/08fe4c42-f642-4b1a-8d85-60aa27f27d01)

**Comment by wsobel** [comment]
Please test this in the latest build.

**Comment by MRIIOT** [comment]
Thanks.  We will test later this week.
