### ISSUE TITLE
Question about extend coordinatesystem?

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#48]
Hi, 
I tried to extend coordinateSystem as shown below but it fails to validate in the probe command.  
I knew that coordinateSystem currently support Machine and Work coordinate systems. 
I need to add axes using different coordinate systems. 

Is that possible?

coordinateSystem="x:I_MACHINE"
coordinateSystem="x:I_WORK"

Thanks

            
            <Linear  name="YI1" nativeName="YIA" id="LYI1">
              <DataItems>
                <DataItem  type="POSITION" subType="ACTUAL" category="SAMPLE"
                  name="YI1actm" units="MILLIMETER" nativeUnits="MILLIMETER" coordinateSystem="x:I_MACHINE" id="LYI1actm" />
                <DataItem  type="POSITION" subType="ACTUAL" category="SAMPLE"
                  name="YI1actw" units="MILLIMETER" nativeUnits="MILLIMETER" coordinateSystem="x:I_WORK" id="LYI1actw" />
                <DataItem  type="LOAD"  category="SAMPLE" name="YS1load"
                units="PERCENT" nativeUnits="PERCENT" id="LYS1load"/>
              </DataItems>
            </Linear>

**Comment by wsobel** [comment]
The coordinate system was not created as an extensible vocabulary. It would be possible to do so. Please tell me what you are trying to do so we can evaluate the solution and understand if this is something we should try to incorporate into the next version of the standard. 

Also, from an application perspective, we'd need to understand the meaning of the extended vocabulary. 

Thanks
W

(Sent from mobile)

**Comment by hulinning2** [comment]
Will, 
A machine can have more than 2 coordinate systems.   I try to use the same Axis component to report axis data (positions, load, etc.) with a different coordinate system. There is no error in current or sample data stream when validating. Probe command is an issue.  Our customer will validate all commands. I really do not want to create an extended tag for this since it makes it difficult for end users.  I would rather use Axis component but it needs to be able to specify in which coordinate system.

Thanks

**Comment by wsobel** [comment]
This is really a schema issue rather than a agent issue. I will raise this with the TSC and get back soon. 

Best
W

(Sent from mobile)

**Comment by hulinning2** [comment]
Will, 
Have you addressed this issue in the schema for 1.5 release yet?

Thanks

**Comment by wsobel** [comment]
The schema for 1.5 is in the development version of the agent cppagent_dev until it has passed the 90 day review. 

The latest schemas will always be in the schema_dev repo which is also private. The dev versions are available for pre-release review to anyone in the SC. 

(Sent from mobile)

**Comment by wsobel** [comment]
Just updated to 1.5
