### ISSUE TITLE
Windows XP builds of Agent 1.4 Release Candidates don't find Devices XML file

### ISSUE THREAD

**Issue by bcampbell-ts** [mtconnect/cppagent#49]
I've tried RC1-RC4 and they all produce the following:

```
C:\agent>agent.exe run
MTConnect Agent Version 1.4.0.2RC2 - built on Mon Jun 12 15:01:36 2017
Agent failed to load: Please make sure the Devices XML configuration file Devices.xml 
is in the current path
Usage: agent  [<file>]
    <file>               : The configuration file
```

There is a Devices.xml file in the same directory as the agent.exe and I even added that directory to the path. Dropping in 1.3 agent.exe works fine.

**Comment by wsobel** [comment]
Can you attach the agent.cfg file? If there is a specification of the location of the Devices.xml file that will make a difference.  There is no change between 1.3 and 1.4. 

Also, if you could send the Devices.xml file I can try to reproduce the problem. 

Thanks
Will

(Sent from mobile)

**Comment by bcampbell-ts** [comment]
This is the agent.cfg I was using:
```
ServiceName = MTConnect Agent
Devices = Devices.xml
Port = 5001
BufferSize = 17
IgnoreTimestamps=true
AllowPut = true
# CheckpointFrequency = 1000

# In UNIX
# PidFile = agent.pid

Adapters
{
    TEST
    {
        Device=TEST
        Host=127.0.0.1
        Port=7878
    }
}

# Logger Configuration
logger_config
{
    logging_level = trace
    output = file agent.log
}
```

I tried removing the Devices line, but just received the same error about not finding probe.xml or Devices.xml.

It doesn't matter what is in the Devices.xml file - you always get the same error. I tested with the one from agent.mtconnect.org.

Running on Windows XP SP3

**Comment by wsobel** [comment]
The devices.xml file must be an MTConnect devices xml file. Can you upload that file as well?

(Sent from mobile)

**Comment by bcampbell-ts** [comment]
Attached with .txt extension so GitHub would take it.

[Devices.xml.txt](https://github.com/mtconnect/cppagent/files/1257286/Devices.xml.txt)

**Comment by wsobel** [comment]
The name of the device should match the adapter device name. But, that will give a different error. I'll check this out once I get in and get back. 

Best
W

(Sent from mobile)

**Comment by johnmichaloski** [comment]
I added this in the exe to the start of the agent, so it would search in the correct directory for the agent.cfg and devices.xml files:.

#ifdef _WINDOWS
    TCHAR buf[1000];
    GetModuleFileName(NULL, buf, 1000);
    std::string path(buf);
    path = path.substr(0, path.find_last_of('\\') + 1);
    SetCurrentDirectory(path.c_str( ) );
#endif

Assumes windows.h included. Before:

return config.main(argc, (const char **) argv);

**Comment by wsobel** [comment]
Thanks. I'll merge

(Sent from mobile)

**Comment by bcampbell-ts** [comment]
This may actually be a Microsoft bug (https://connect.microsoft.com/VisualStudio/feedback/details/1600505/stat-not-working-on-windows-xp-using-v14-xp-platform-toolset-vs2015)

Its presence probably depends on what compiler is being used.

**Comment by wsobel** [comment]
Added code to check current as well as executable directories for the configuration file as well as the Device.xml file.

**Comment by bcampbell-ts** [comment]
This did not fix the issue since the problem appears to be with using `stat` on Windows XP (see link above).

```
C:\Documents and Settings\tester\Desktop\cppagent_win32_XP_1.4.0.5_RC7_bin\bin>agent.exe run

Configuration search path: current directory and C:\Documents and Settings\tester\Desktop\cppagent_win32_XP_1.4.0.5_RC7_bin\bin
\MTConnect Agent Version 1.4.0.7RC7 - built on Fri Sep 22 12:20:15 2017
Cannot find agent.cfg in current directory, searching exe path: C:\Documents and Settings\tester\Desktop\cppagent_win32_XP_1.4.
0.5_RC7_bin\bin\Could not locate file: Devices.xml
Could not locate file: C:\Documents and Settings\tester\Desktop\cppagent_win32_XP_1.4.0.5_RC7_bin\bin\Devices.xml
Could not locate file: Devices.xml
Could not locate file: C:\Documents and Settings\tester\Desktop\cppagent_win32_XP_1.4.0.5_RC7_bin\bin\Devices.xml
Could not locate file: probe.xml
Could not locate file: C:\Documents and Settings\tester\Desktop\cppagent_win32_XP_1.4.0.5_RC7_bin\bin\probe.xml
Agent failed to load: Please make sure the configuration file probe.xml or Devices.xml is in the current directory or specify th
e correct file in the configuration file C:\Documents and Settings\tester\Desktop\cppagent_win32_XP_1.4.0.5_RC7_bin\bin\agent.c
fg using Devices = <file>
Usage: agent  [<file>]
    <file>               : The configuration file
	
C:\Documents and Settings\tester\Desktop\cppagent_win32_XP_1.4.0.5_RC7_bin\bin>dir
 Volume in drive C has no label.
 Volume Serial Number is 24FE-A31E

 Directory of C:\Documents and Settings\tester\Desktop\cppagent_win32_XP_1.4.0.5_RC7_bin\bin

25/09/2017  08:01    <DIR>          .
25/09/2017  08:01    <DIR>          ..
20/09/2017  08:23               265 agent.cfg
22/09/2017  03:21         1,777,152 agent.exe
25/09/2017  08:06             6,397 agent.log
01/09/2017  11:33             1,567 Devices.xml
               4 File(s)      1,785,381 bytes
               2 Dir(s)  120,873,549,824 bytes free	
```

**Comment by johnmichaloski** [comment]
I use this code. It assumes agent.cfg and devices.xml in the same folder as the agent.exe.

#ifdef _WINDOWS
       TCHAR buf[1000]; // assumes windows.h loaded
       GetModuleFileName(NULL, buf, 1000);
       std::string path(buf); // assume MBS app
       path=path.substr( 0, path.find_last_of( '\\' ) +1 );
       SetCurrentDirectory(path.c_str());
#endif
       return config.main(argc, (const char **) argv);


Only tested on XP, Win7.

**Comment by wsobel** [comment]
I only tested on windows 10, Mac, and Linux. I'll test on XP and fix. Thanks  - W

(Sent from mobile)
