### ISSUE TITLE
V2.4.0.3 Missing Module

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#493]
Tried testing V2.4.0.3 for MQTT payload ingest fix.  Get 'Cannot load plugin '  'Reason: boost::dll::shared_library::load() failed: The specified module could not be found [system:126]'
Tested on Windows 10
test files attached

[Test_V2.4.0.3.zip](https://github.com/user-attachments/files/17249588/Test_V2.4.0.3.zip)

**Comment by wsobel** [comment]
Did this ever work?

```
Adapters {
   
     device{
		Url = 127.0.0.1:1883
        Topics = "testmx/ingest/#"
		MqttUserName = user
        MqttPassword = password
        
   }
}
```

It is missing the protocol section of the URL:

```
Adapters {
   
     device{
		Url = mqtt://127.0.0.1:1883
        Topics = "testmx/ingest/#"
		MqttUserName = user
        MqttPassword = password
        
   }
}
```

**Comment by neildes2** [comment]
connected fine with protocol section.  shame on me.
Beginning testing
