### ISSUE TITLE
Custom Macros in Fanuc adapter

### ISSUE THREAD

**Issue by smtpl-iiotian** [mtconnect/cppagent#496]
Hi, 
I updated adapter.ini for each individual adapter as

[macros]
[cycletime=803]

and devices.xml with event

DataItem category="EVENT" id="dev_01_cycletime_01" name="cycletime" type="CYCLETIME"

But I get UNAVAILABLE data on http://localhost:5000/current

**Comment by robot-ranger** [comment]
this repo is for the ccpagent; it looks like you are trying to run one of the old adapters. first you should be aware that those adapters are pretty old and may not be compatible with current mtconnect. 

but back to your issue - are you running an mtconnect agent?

**Comment by wsobel** [comment]
Try:

```
[macros]
cycletime=803

```

The syntax is wrong.

**Comment by smtpl-iiotian** [comment]
@wsobel I tried with above syntax but the adapter remains in Stopped state after the initial Running state. Refering fanuc_adapter.cpp as in below link.
https://github.com/mtconnect/adapter/blob/76a04e19f6d37f4f36516978dc1a8526a3439a02/fanuc/fanuc_adapter.cpp#L172

For an event i.e., path macro, adapter.ini was kept as 
[macros]
[cycletime=803]
devices.xml was kept as
<DataItem category="EVENT" id="dev_01_cycletime_01" name="cycletime" type="CYCLETIME"/>

For a sample, adapter.ini was updated to 
[macros]
cycletime=803
devices.xml was updated as
<DataItem category="SAMPLE" id="dev_01_cycletime_01" name="cycletime" subType="ACTUAL" type="CYCLETIME" />

I tested above 2 cases but the adapter in the Fanuc-MTConnect-Agent changes to Stopped state for both.

**Comment by wsobel** [comment]
can we move th9s discussion to the adapter repository since it has nothing to do with the agent?

**Comment by smtpl-iiotian** [comment]
@wsobel fine I will close this issue and put it in the adapter
