### ISSUE TITLE
Unable to remove/hide asset

### ISSUE THREAD

**Issue by Unstable-Robert** [mtconnect/cppagent#50]
The corresponding asset isn't being removed/hidden when the agent receives the following from an adapter: ![adapter output](https://user-images.githubusercontent.com/4021348/30126217-4a7be59c-9309-11e7-9c56-07a2f8822d4a.png) 

After some digging I was able to figure out that the asset wasn't being removed because the assetId the agent was using as the search-key had a ` CR ` at the end which doesn't match the stored key. 

![github-remove asset issue cropped](https://user-images.githubusercontent.com/4021348/30125649-143a21d0-9307-11e7-9024-cb7e2d178a5c.png)

**Comment by wsobel** [comment]
I'll check this out once I have a chance. Traveling now. 

(Sent from mobile)

**Comment by wsobel** [comment]
Added trim in adapter to remove whitespace from ID. This is in version 1.4 only. Can be back ported if necessary.
