### ISSUE TITLE
Brother CNC adapter support.

### ISSUE THREAD

**Issue by mrfy** [mtconnect/cppagent#502]
Hello team,

First, thank you for your hard work and dedication to this project—it’s greatly appreciated!

I would like to kindly request the addition of an adapter to support CNC Brother (C00). May I ask if there are any plans to include support for this in the near future?

![image](https://github.com/user-attachments/assets/bffcc972-6d2e-4212-9ffa-e44d4d278748)

Thank you for considering this request. I look forward to hearing from you.

**Comment by wsobel** [comment]
Hi!

I don't recognize the application you are installing from. Where did you download it from? The c++ agent is an application that works with OEM or 3rd party vendor solutions. This is not part of the std install. 

Best
Will

**Comment by mrfy** [comment]
Hi @wsobel, thanks for answer, this application is available in this repository, under `install/Windows` directory:

![image](https://github.com/user-attachments/assets/de02c8a9-2b39-48ef-bb58-17e602427ebf)

**Comment by wsobel** [comment]
This is very old and I thought we had removed it. If we have not, I will take care of it. Sorry for the confusion.

**Comment by mrfy** [comment]
Got it! So, if I understand right, you used to support and develop an adapter for these manufacturers some time ago? 

In my case, I’ve set up communication with a Brother CNC machine over FTP, but it’s not the most convenient way to grab data. Ideally, I’d like to use MTConnect. What would I need to get started on building an adapter for this?

**Comment by wsobel** [comment]
Someone put this together as an example. We have a few adapters in the adapter repo, but these were examples. Two of them are priority, so I'm not sure how it even worked. Forgot all about it.
