### ISSUE TITLE
Some cppagent Event values are blank on change

### ISSUE THREAD

**Issue by rickflanders** [mtconnect/cppagent#53]
I have a small adapter which is able to change some Event MESSAGE values, but for others the cppagent sets them to blank..  The configuration for both in my Devices.xml looks identical.  I have confirmed that my adapter is sending out the changes correctly.  When the adapter first connects, all the values are correct.  But when I send out a change, certain become blank.
Here is a picture of the partial output in my browser right after connecting my adapter.
![mach500events1b](https://user-images.githubusercontent.com/15709768/34750320-5aee31c8-f55b-11e7-923a-9307a658f856.jpg)

Here is a picture of the output after I changed the System.State to ESTOP.  The State is correct and the ESTop event also changed correctly.
![mach500events2b](https://user-images.githubusercontent.com/15709768/34750330-66aa5e10-f55b-11e7-942f-76ab25a89217.jpg)

However, if I change any of the values for System.Name, System.Type or System.Operator, the Values are always blank.
![mach500events3b](https://user-images.githubusercontent.com/15709768/34750376-9db386c0-f55b-11e7-8a06-a70523c1f659.jpg)

My Devices.xml file defines all of the Event MESSAGE types the same way.  Why do some work and others do not?
![mach500devices](https://user-images.githubusercontent.com/15709768/34750493-295fc738-f55c-11e7-83b6-35d8656364c0.JPG)

What am I doing wrong?

**Comment by wsobel** [comment]
Can you show me the adapter data?

(Sent from mobile)

**Comment by rickflanders** [comment]
Yes, the adapter data from the dump utility looks like the following.  The initial data is shown on the first line.  Then I added a letter to each field to cause it to change.
```
2018-01-10T01:42:43.7861145Z|Machine.Availability|AVAILABLE|Machine.EStop|ARMED|
System.Name|P1|System.Type|Mach500|System.Operator|Betty Smith|System.State|MANU
AL|Controller.Mode|MANUAL
2018-01-10T01:43:00.0321145Z|System.State|AUTOMATIC|Controller.Mode|AUTOMATIC
2018-01-10T01:43:11.1851145Z|System.Name|P1A
2018-01-10T01:43:21.3251145Z|System.Type|Mach500a
2018-01-10T01:43:33.4911145Z|System.Operator|Wilma Rubble
2018-01-10T01:43:40.5891145Z|Machine.EStop|TRIGGERED|System.State|ESTOP|Controll
er.Mode|ESTOP
```

**Comment by bcampbell-ts** [comment]
Note the following information concerning MESSAGE type from https://github.com/mtconnect/cppagent

> The next special format is the Message. There is one additional field, native_code, which needs to be included:
> 
> `2014-09-29T23:59:33.460470Z|message|CHG_INSRT|Change Inserts`

You are not including a native_code, so I would guess the agent is getting confused over the missing value. It seems like it is working if multiple values come in at once (like your EStop and State), but not if they are alone on a line.
If you don't have a native_code, but still want to use the MESSAGE type, try outputting a blank value for it.
e.g.
`2018-01-10T01:43:11.1851145Z|System.Name||P1A`

**Comment by bcampbell-ts** [comment]
@rickflanders Are you still having issues?

**Comment by rickflanders** [comment]
You were correct.  I was not including the native code for the Message type.  So I switched to using more specific types and it is working fine now.  Thanks for your help.

**Comment by wsobel** [comment]
Since this has been resolved, I will close the issue. Thanks - W
