### ISSUE TITLE
MTConnect CPP Agent on LinuxCNC(PocketNC)

### ISSUE THREAD

**Issue by nombreinvicto** [mtconnect/cppagent#54]
Hi everyone

New to programming here so any help would be much appreciated.

I am trying to deploy the MTConnect CPP agent on a LinuxCNC machine (a PocketNC to be precise). I am following everything from this link for building the agent on an Ubuntu based machine. (http://mtcup.org/wiki/Installing_C%2B%2B_Agent_on_Ubuntu).

However, after executing the "make" command, I am having an error as follows:
______________________________________________________________________________________________________________
[  1%] Building CXX object agent/CMakeFiles/agent.dir/cppagent.cpp.o
In file included from /home/pocketnc/agent/cppagent/agent/adapter.hpp:29:0,
                 from /home/pocketnc/agent/cppagent/agent/agent.hpp:31,
                 from /home/pocketnc/agent/cppagent/agent/cppagent.cpp:17:
/home/pocketnc/agent/cppagent/agent/connector.hpp:98:22: error: ISO C++ forbids initialization of member 'mHeartbeats' [-fpermissive]
/home/pocketnc/agent/cppagent/agent/connector.hpp:98:22: error: making 'mHeartbeats' static [-fpermissive]
/home/pocketnc/agent/cppagent/agent/connector.hpp:98:22: error: ISO C++ forbids in-class initialization of non-const static member 'mHeartbeats'
/home/pocketnc/agent/cppagent/agent/connector.hpp:99:29: error: ISO C++ forbids initialization of member 'mHeartbeatFrequency' [-fpermissive]
/home/pocketnc/agent/cppagent/agent/connector.hpp:99:29: error: making 'mHeartbeatFrequency' static [-fpermissive]
/home/pocketnc/agent/cppagent/agent/connector.hpp:99:29: error: ISO C++ forbids in-class initialization of non-const static member 'mHeartbeatFrequency'
/home/pocketnc/agent/cppagent/agent/connector.hpp:100:24: error: ISO C++ forbids initialization of member 'mLegacyTimeout' [-fpermissive]
/home/pocketnc/agent/cppagent/agent/connector.hpp:100:24: error: making 'mLegacyTimeout' static [-fpermissive]
/home/pocketnc/agent/cppagent/agent/connector.hpp:100:24: error: ISO C++ forbids in-class initialization of non-const static member 'mLegacyTimeout'
make[2]: *** [agent/CMakeFiles/agent.dir/cppagent.cpp.o] Error 1
make[1]: *** [agent/CMakeFiles/agent.dir/all] Error 2
make: *** [all] Error 2
_______________________________________________________________________________________________________________

I understand, there is an error in making the mHeartbeats file but at this point am totally clueless as to how to get around this issue. Could anyone help me in this? Thank you!

**Comment by wsobel** [comment]
What version of g++ are you using? Looks like there is a problem with initialization of static members in the header. There seems to be two options. You can add the -fpermissive flag or the code can change. 

Once I have the g++ version I can reproduce and patch.

Thanks,
Will sobel

**Comment by nombreinvicto** [comment]
Hi Will
Thank you for the reply.
It looks like I have version 4.6.3 running on the PocketNC. It does compile on another beagleboard which is running 4.9.2. So far I am using that board as an agent as a workaround. I will try compiling it on the PocketNC with the -fpermissive flag once I get back to it. 

Thanks for the suggestions.
