### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by Unstable-Robert** [mtconnect/cppagent#55]
When sending cutting tool data repeatedly to the agent, the memory usage looks to keep expanding even once the asset buffer is full. We have the asset buffer size set to 74 so it's filled from the start of the adapter output.

I've attached the adapter output below.
[ToolData.txt](https://github.com/mtconnect/cppagent/files/1738505/ToolData.txt)

**Comment by wsobel** [comment]
I'll begin looking into this today.

**Comment by wsobel** [comment]
I have tested the ref counting of assets and cleanup after the buffer fills. So far the refcounting is working properly with the primary and secondary indexes. The next level of analysis is to dig deeper into the memory management of the XML Parser and the Cutting Tool asset itself.

**Comment by wsobel** [comment]
Please re-open if this is not closed.
