### ISSUE TITLE
Spaces in Device names

### ISSUE THREAD

**Issue by joshd23** [mtconnect/cppagent#56]
We ran into a scenario where the device name had a space in it in the device.xml, such as: 
<Device id="Machine 122010" name=" Machine 122010" uuid=" Machine 122010">

The issue is that the agent returns an error code of NO_DEVICE in this case
‘Could not find the device ‘Machine%20122010’.

**Comment by hulinning2** [comment]
Device name cannot have empty spaces since it will not be valid on the browser

**Comment by bcampbell-ts** [comment]
Per Part 2 of the standard section 4.2.2 Attributes for Device, the name attribute is defined as `an NMTOKEN XML type`

You can see here (http://www.datypic.com/sc/xsd/t-xsd_NMTOKEN.html) that NMTOKEN cannot contain spaces.
