### ISSUE TITLE
Problems with PERIOD Filter of DataItem

### ISSUE THREAD

**Issue by bcampbell-ts** [mtconnect/cppagent#58]
When attempting to use a Filter of type PERIOD with 1.4 agent, there are some issues:

1. The filter only works if the adapter is configured with `RelativeTime = true` in the agent configuration file. Otherwise, the offset value is never set and the check in `isFiltered` always fails because the time offsets are `NAN`

2. The Standard says that PERIOD is defined in seconds, but the agent is doing the comparisons with microseconds.
For example, `mBaseOffset = parseTimeMicro(time);`

I can submit a PR to fix issue 2, but I'm not sure if the `RelativeTime` constraint is intended or not.

**Comment by MatthewPowley** [comment]
Can you create a pull request for your second issue?
I am converting the code to C++ and one thing I am looking at is using std::chrono for time values. This allows conversion of time implicitly (i.e. pass seconds to a function accepting milliseconds it will be converted).
