### ISSUE TITLE
Event being created without CDATA - run_scenario.rb

### ISSUE THREAD

**Issue by paulorb** [mtconnect/cppagent#60]
I  used the cppagent with the run_scenario.rb  (run_scenario.rb -l VMC-3Axis-Log.txt -v) and I noticed that if you monitor the current values in some special moment the Event comes without CDATA value

Most of the time it stays like this:
` <Block dataItemId="cn2" timestamp="2018-04-26T03:11:19.439519Z" name="block" sequence="533877">X-1.460622 Y0.842128</Block>`

During like 15 seconds:

```
<Events>
<Block dataItemId="cn2" timestamp="2018-04-26T03:04:20.929205Z" name="block" sequence="458026"/>
....
```

It comes without value, according to the protocol:
620 5.5.5 Valid Data Values for Event
621 Event elements reported in an MTConnectStreams XML document **MUST provide a value
622 in the CDATA of the Data Entity.**
623 The value reported in the CDATA MUST be reported as either a Valid Data Value representing
624 the information reported from a piece of equipment or UNAVAILABLE when a Valid Data Value
625 cannot be determined. 

I am implementing a client (parsing the XMLs) so I would like to understand if it is something expected or a possible bug.

Thanks

**Comment by bcampbell-ts** [comment]
In your case, the value of Block is an empty string (""), so I assume you think it might be:
`<Block dataItemId="cn2" timestamp="2018-04-26T03:04:20.929205Z" name="block" sequence="458026"></Block>`
That would be considered an empty element and the XML specification allows empty elements to be specified as self closing tags (as you show above). See https://www.w3.org/TR/xml/#sec-starttags

I'm not sure what the standard is attempting to specify by saying a CDATA must have a value. I don't believe the intent is for the output to look like this:
`<Block dataItemId="cn2" timestamp="2018-04-26T03:04:20.929205Z" name="block" sequence="458026"><![CDATA[]]></Block>`

**Comment by paulorb** [comment]
My question in fact is, can we have empty data as a Data value? Is it correct (according to the protocol specification) for an agent  to send Event DataValues with empty value?

623 The value reported in the CDATA MUST be reported as either a **Valid Data Value** representing
624 the information reported from a piece of equipment or UNAVAILABLE when a Valid Data Value

It says that the value should be a "Valid  Data Value" or UNAVAILABLE,  is empty value a Valid Data Value?

**Comment by paulorb** [comment]
Make sense, Tks
