### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by sundaskhansk** [mtconnect/cppagent#63]
I found this error when I configure the file CMakelists. and this file is present in the registry.
CMake Error: File /agent/version.rc.in does not exist.
CMake Error at CMakeLists.txt:39 (configure_file):
  configure_file Problem configuring file

**Comment by MatthewPowley** [comment]
I can't see why this is happening. The CMakeLists.txt and the version are present in the master branch.
Are you using the CMake UI? What settings are you passing to CMake?

**Comment by sundaskhansk** [comment]
Yes Im using CMake UI. 
for source code: cppagent-master/agent
for where to build binaries: cppagent-master/build
Visual studio 11 2012
use default native compilers

**Comment by MatthewPowley** [comment]
Can you try something for me?
Clone my fork of the repository: https://github.com/MatthewPowley/cppagent.git
Checkout the CPP_11_Conversion branch and then try again.
I have made a lot of refactoring and bug fixes to the build system.

**Comment by sundaskhansk** [comment]
still the issue is there

**Comment by sundaskhansk** [comment]
my settings are correct ?

**Comment by MatthewPowley** [comment]
Try these steps from a command prompt:
mkdir c:\cppagent_test
cd c:\cppagent_test
git clone https://github.com/mtconnect/cppagent.git
git submodule --init
cd cppagent
mkdir build
cd build
cmake -G "Visual Studio 11 2012" ..

**Comment by sundaskhansk** [comment]
its not working

**Comment by sundaskhansk** [comment]
when I remove these lines from cmakelists file in agent then it runs.
 configure_file(
    ${PROJECT_SOURCE_DIR}/version.rc.in
    ${resource_file})

**Comment by sundaskhansk** [comment]
when I remove these lines from cmakelists file in agent then it runs.
configure_file(
${PROJECT_SOURCE_DIR}/agent/version.rc.in
${resource_file})

**Comment by MatthewPowley** [comment]
What version of CMake are you using?
Can add these lines?

message(STATUS "PROJECT_SOURCE_DIR=${PROJECT_SOURCE_DIR}")
configure_file(
${PROJECT_SOURCE_DIR}/agent/version.rc.in
${resource_file})

What does the output say your value of PROJECT_SOURCE_DIR is?

**Comment by sundaskhansk** [comment]
I'm using 3.10.3 version of CMake.
there is no cpp file for version rc. this can cause the issue?
I tried these lines but issue is still there

**Comment by MatthewPowley** [comment]
What was the output of the message?

**Comment by sundaskhansk** [comment]
ROJECT_SOURCE_DIR=
CMake Error: File /agent/version.rc.in does not exist.
CMake Error at CMakeLists.txt:41 (configure_file):
  configure_file Problem configuring file


Configuring incomplete, errors occurred!
See also "C:/Users/sundus/Desktop/cppagent-master/build/CMakeFiles/CMakeOutput.log".

**Comment by MatthewPowley** [comment]
I'm not sure I can help. The CMake variable ${PROJECT_SOURCE_DIR} is set by the CMake system to the location of the source tree when the cache is first created. In your case this is empty.
I would use the CMake UI to delete the cache and create it again.
If the message still have an empty value for this property, then try updating to the latest CMake version.

**Comment by sundaskhansk** [comment]
yes i delete the cache and again configure the file but issue is not removed.
can you tell me it can be caused because of no cpp file is there for version rc

**Comment by sundaskhansk** [comment]
can you tell me the steps to compile the code of mtconnect agent may be I'm missing something

**Comment by MatthewPowley** [comment]
The function that is not working for you is a CMake function that is trying to create the file 'version.rc' from an input file 'version.rc.in'. The input file will have CMake properties within it that will be replaced with their values when the CMake command executes.
It has nothing to do with any cpp files.

**Comment by MatthewPowley** [comment]
I suggest you upgrade CMake to the latest version.

**Comment by sundaskhansk** [comment]
oh okay great.
thankyou

**Comment by sundaskhansk** [comment]
which version you will prefer

**Comment by MatthewPowley** [comment]
I am using 3.11 at the moment with no problems.

**Comment by sundaskhansk** [comment]
and you are using the same file

**Comment by sundaskhansk** [comment]
not working :( 
issue is still there

**Comment by MatthewPowley** [comment]
If you open a Visual Studio developer console window (shortcut is in the Window Start menu) and change to your C:\ drive root directory.

I would use the following commands:

git clone --progress https://github.com/mtconnect/cppagent.git
git submodule --init
cd cppagent
mkdir build
cd build
cmake -G "Visual Studio 11 2012" ..
msbuild cppagent.sln /t:build /p:configuration=Debug /p:platform="Win32" /m

This works for me on a fresh virtual machine.

**Comment by MatthewPowley** [comment]
I think I know what your problem is.
In the CMake UI have you set the source directory to the 'agent' subfolder?

![github-agent_2](https://user-images.githubusercontent.com/14095538/39427075-55f7a656-4c7a-11e8-932f-fb859db0f5b2.png)

This should be the root folder:
![github-agent_1](https://user-images.githubusercontent.com/14095538/39427102-728274d6-4c7a-11e8-9c89-1e209266ddd2.png)

This would account for your CMake variable ${PROJECT_SOURCE_DIR} being empty; as this is set when a 'project' statement is encountered.

**Comment by sundaskhansk** [comment]
I want to run the code of Agent

**Comment by MatthewPowley** [comment]
You need to build a Visual Studio solution from the root of the code, this will then create you a C++ project item for the 'agent'. This is how all CMake systems are configured, you can't simply create a project for a subset of the code as dependencies and configuration may be defined at a higher-level.

Have you been able to generate a solution without error by setting the CMake source folder to the toot folder of the GIT repository?

**Comment by sundaskhansk** [comment]
okay issue is solved I changed the directory but when I run the project in visual studio there are some errors

**Comment by MatthewPowley** [comment]
I will close this issue. If you have compiler errors then you should raise another issue.
I suggest you look at any existing issues / pull requests first to see if they have been addressed.
