### ISSUE TITLE
agent_test.cpp

### ISSUE THREAD

**Issue by sundaskhansk** [mtconnect/cppagent#64]
I'm having issues in file agent_test.cpp.
	206	IntelliSense: identifier "R" is undefined	c:\Users\sundus\Desktop\cppagent-master\test\agent_test.cpp	1272
	205	IntelliSense: expression preceding parentheses of apparent call must have (pointer-to-) function type	
	208	IntelliSense: expression preceding parentheses of apparent call must have (pointer-to-) function type	
	210	IntelliSense: expression preceding parentheses of apparent call must have (pointer-to-) function type	
	212	IntelliSense: expression preceding parentheses of apparent call must have (pointer-to-) function type	
	214	IntelliSense: expression preceding parentheses of apparent call must have (pointer-to-) function type	
	216	IntelliSense: expression preceding parentheses of apparent call must have (pointer-to-) function type	
	207	IntelliSense: expected a ')'		
	209	IntelliSense: expected a ')'	
	211	IntelliSense: expected a ')'	
	213	IntelliSense: expected a ')'	
	215	IntelliSense: expected a ')'	
	217	IntelliSense: expected a ')'	
	204	IntelliSense: "map" is ambiguous
Error	180	error C2143: syntax error : missing ')' before 'string'	
Error	183	error C2143: syntax error : missing ')' before 'string'	
Error	186	error C2143: syntax error : missing ')' before 'string'	
Error	189	error C2143: syntax error : missing ')' before 'string'	
Error	192	error C2143: syntax error : missing ')' before 'string'	
Error	195	error C2143: syntax error : missing ')' before 'string'	
Error	179	error C2065: 'R' : undeclared identifier	
Error	182	error C2065: 'R' : undeclared identifier	
Error	185	error C2065: 'R' : undeclared identifier	
Error	188	error C2065: 'R' : undeclared identifier	
Error	191	error C2065: 'R' : undeclared identifier	
Error	194	error C2065: 'R' : undeclared identifier	
Error	181	error C2059: syntax error : ')'	
Error	184	error C2059: syntax error : ')'	
Error	187	error C2059: syntax error : ')'	
Error	190	error C2059: syntax error : ')'	
Error	193	error C2059: syntax error : ')'	
Error	196	error C2059: syntax error : ')'

**Comment by bcampbell-ts** [comment]
`R` in front of a string (such as on line 1272 of agent_test.cpp) is the format for a raw string literal (http://www.stroustrup.com/C++11FAQ.html#raw-strings). This feature is from C++11. What compiler version are you using and does it support C++11?

**Comment by sundaskhansk** [comment]
I am using vs 2012

**Comment by MatthewPowley** [comment]
You will require Visual Studio 2015 (Update 3) for this C++11 code to compile.

**Comment by bcampbell-ts** [comment]
Per this link (https://msdn.microsoft.com/en-us/library/hh567368.aspx), Visual Studio 2012 does not support raw string literals.
You will need to convert all of the strings that start with `R"` to be properly escaped.

For example, line 1272 changes from this :
  ```
adapter->parseBuffer(R"ASSET(2018-02-19T22:54:03.0738Z|@ASSET@|M8010N9172N:1.0|CuttingTool|--multiline--SMOOTH
<CuttingTool toolId="0" serialNumber="0" removed="False" assetId="M8010N9172N:1.0"><CuttingToolLifeCycle><ToolLife type="MINUTES" countDirection="UP" initial="0" limit="">1</ToolLife><ToolLife type="PART_COUNT" countDirection="UP" initial="0" limit="">1</ToolLife><Location type="POT" positiveOverlap="0" negativeOverlap="0">1</Location><ProgramToolGroup>0</ProgramToolGroup><ProgramToolNumber>1.0</ProgramToolNumber><CutterStatus><Status>USED</Status><Status>ALLOCATED</Status><Status>AVAILABLE</Status></CutterStatus><Measurements><FunctionalLength code="LF" nominal="0">0</FunctionalLength><CuttingDiameterMax code="DC" nominal="0">200</CuttingDiameterMax></Measurements></CuttingToolLifeCycle></CuttingTool>
--multiline--SMOOTH
)ASSET");
```

to something like this:
```
  adapter->parseBuffer("ASSET(2018-02-19T22:54:03.0738Z|@ASSET@|M8010N9172N:1.0|CuttingTool|--multiline--SMOOTH\n\
<CuttingTool toolId=\"0\" serialNumber=\"0\" removed=\"False\" assetId=\"M8010N9172N:1.0\"><CuttingToolLifeCycle><ToolLife type=\"MINUTES\" countDirection=\"UP\" initial=\"0\" limit=\"\">1</ToolLife><ToolLife type=\"PART_COUNT\" countDirection=\"UP\" initial=\"0\" limit=\"\">1</ToolLife><Location type=\"POT\" positiveOverlap=\"0\" negativeOverlap=\"0\">1</Location><ProgramToolGroup>0</ProgramToolGroup><ProgramToolNumber>1.0</ProgramToolNumber><CutterStatus><Status>USED</Status><Status>ALLOCATED</Status><Status>AVAILABLE</Status></CutterStatus><Measurements><FunctionalLength code=\"LF\" nominal=\"0\">0</FunctionalLength><CuttingDiameterMax code=\"DC\" nominal=\"0\">200</CuttingDiameterMax></Measurements></CuttingToolLifeCycle></CuttingTool>\n\
--multiline--SMOOTH\n\
)ASSET");

```

(Note that we have escaped all of the quotes in the string by changing `"` to `\"` and adding newlines and line continuation character at the end of each line.

**Comment by MatthewPowley** [comment]
I have a pull request outstanding (#57) that has converted the code to C++11 and I have added flags to CMake that require a C++11 compliant compiler (of which VS2012 is not) and you will get an error before compiling.

**Comment by MatthewPowley** [comment]
I would suggest that you upgrade to Visual Studio 2015 at least. You can still use the latest IDE to compile with the Visual Studio 2012 toolset for any of your existing code.

**Comment by sundaskhansk** [comment]
![whatsapp image 2018-05-07 at 11 21 41 am](https://user-images.githubusercontent.com/38851014/39687791-6148c188-51e9-11e8-8ab3-14aa4e909fe1.jpeg)
I am getting this error now and I am using visual studio 2015
