### ISSUE TITLE
nativeName attribute not Streaming

### ISSUE THREAD

**Issue by NeilDes** [mtconnect/cppagent#67]
On an Axis Component, if "nativeName=" attribute is provided, it is available in the probe but not sample/stream.

**Comment by bcampbell-ts** [comment]
It is not required to be in the Streams document.
Section 4.3.2 of Part 3 Streams says:
> If nativeName is defined for a specific Structural Element in the
> MTConnectDevices document, it **MAY** be provided for the
> corresponding ComponentStream element in the
> MTConnectStreams document.
> 

So, the agent isn't deficient, but I don't know that there is a reason for it not to be included.

If the project had tags, this would be a feature request vice bug.

**Comment by wsobel** [comment]
The nativeName was static and it seemed redundant when implementing part 3. It is in part 2, which seemed sufficient. We should think about revising the standard as well. Would not mind depreciating from part 3. 

I'll add an issue fits 1.5. 

Best 
W

(Sent from mobile)
