### ISSUE TITLE
debugging error

### ISSUE THREAD

**Issue by sundaskhansk** [mtconnect/cppagent#68]
![whatsapp image 2018-05-07 at 11 21 41 am](https://user-images.githubusercontent.com/38851014/39698971-92a533f2-5210-11e8-9a7c-1c8847d77073.jpeg)
when I debug MTconnect Agent. I get this error.

**Comment by bcampbell-ts** [comment]
You are trying to run the `ALL_BUILD` project, which is not a program you can run.
You need to change the startup project to `agent` instead of `ALL_BUILD`

Also, make sure you specify debug command line parameters or the agent will run and quit immediately.

**Comment by sundaskhansk** [comment]
what parameters should I add in debug command line to run my application smoothly
