### ISSUE TITLE
start with mtconnect

### ISSUE THREAD

**Issue by sundaskhansk** [mtconnect/cppagent#99]
can anyone tell me how to start with mtconnect and how to link agent with application please :(

**Comment by bcampbell-ts** [comment]
Can you please explain your question more clearly? What do you mean "link"?

**Comment by sundaskhansk** [comment]
link means how to build a connection between agent and application?

**Comment by bcampbell-ts** [comment]
I recommend you read Part 1 of the standard which explains how the Agent stores and provides data.
You can also watch this video from the MTConnect Institute: https://youtu.be/87vnkHc-zd8

**Comment by sundaskhansk** [comment]
okay can you help me with the adapter code

**Comment by MatthewPowley** [comment]
What is it that you are trying to achieve?
If you want to write an adapter to put data into this agent via SHDR format, you can look at examples in the adapter repository, here: https://github.com/mtconnect/adapter

If you want to consume data from the agent, for a simple dashboard or something then there are open-source examples of this, such as https://github.com/TrakHound/MTConnect.NET.

**Comment by sundaskhansk** [comment]
I want that adapter collect dummy data and then put data in to this agent

**Comment by MatthewPowley** [comment]
There is a Fake adapter project as part of the adapter repository, You can modify this to achieve what you want. You will have to define a devices.xml file for the fake adapter and then start the agent using this file.

**Comment by sundaskhansk** [comment]
where I can find that repository

**Comment by MatthewPowley** [comment]
Link is above.

**Comment by sundaskhansk** [comment]
Thank you so much. okay now please tell me what should I change in devices.xml file

**Comment by MatthewPowley** [comment]
This depends on what data you are intending to fake?
If you wanted to fake a 3-axis machine tool, then you could use an example file for this machine and strip it down to just it's bare essentials; such as position for each axis. In the fake adapter simply fake a stream of axis data. Then the agent would show this fake axis data through the 'sample' command.

**Comment by MatthewPowley** [comment]
I would suggest that you do more background reading into MTConnect. Mazak hold regular training sessions on the subject (MTConnect Bootcamp) with practical examples and classes that may be advantageous to you. See: https://www.mazakusa.com/machines/technology/digital-solutions/mtconnect/

This agent acts as a middle-man; collecting/storing/converting data from an adapter in the SHDR format and presenting/serving the data to a client as defined by the MTConnect standard.

What you are requesting is help beyond this scope.

Are you comfortable programming with sockets? If so then creating your own fake adapter may be easier. You can read the specs for the SHDR format, here: https://github.com/mtconnect/adapter/blob/master/MTC_SHDR.docx

**Comment by sundaskhansk** [comment]
My task is to show dummy data on agent through adapter, I'm using this agent and I don't know how to integrate agent and adapter

**Comment by sundaskhansk** [comment]
the data could be any thing. for example status of machine 
machine is on

**Comment by wsobel** [comment]
The adapter open a server socket and the agent connects to the adapter. The adapter sends pipe delisted data as documented in the README:

 <https://github.com/mtconnect/cppagent#adapter-agent-protocol-version-14> <https://github.com/mtconnect/cppagent#adapter-agent-protocol-version-14> <https://github.com/mtconnect/cppagent#adapter-agent-protocol-version-14> <https://github.com/mtconnect/cppagent#adapter-agent-protocol-version-14>https://github.com/mtconnect/cppagent#adapter-agent-protocol-version-14

There are many configuration examples here:

https://github.com/mtconnect/cppagent#specifying-the-xml-document-style

The port is the port number the server binds to. There are software examples on the site as well in ruby, python, C++, and C#.

**Comment by sundaskhansk** [comment]
https://www.youtube.com/watch?v=pvz2d3WrsS8&feature=youtu.be
can you give me the link of project directory discussed in this video
